[UT] Capture runtime env in reports
intel/intel-xpu-backend-for-triton pull request #1072
Opened 2024-05-09 06:31 UTC by AshburnLee

## Functionality

This PR meets request from https://github.com/intel/intel-xpu-backend-for-triton/issues/979

There will be a .txt file in the report folder for each runtime env parameter when users pass `--reports` while executing `test-triton.sh`:
`bash ./scripts/test-triton.sh --reports`.

## Result

Users will find the following files under `$HOME/reports/$TIMESTAMP/`

IPEX_version.txt
agam_driver_version.txt
cmplr_version.txt
gpu.txt
level-zero_version.txt
libigc1_version.txt
mkl_version.txt
python_version.txt
pytorch_version.txt
triton_version.txt

2024-05-09 13:52 UTC, vlad-penkin requested changes

2024-05-09 13:52 UTC, vlad-penkin commented on scripts/pytest-utils.sh
Please reuse the results of
- #1036

2024-05-10 02:03 UTC, AshburnLee commented on scripts/pytest-utils.sh
Reused, thanks ~

2024-05-10 11:48 UTC, vlad-penkin requested changes

2024-05-10 11:48 UTC, vlad-penkin commented on scripts/pytest-utils.sh
@AshburnLee this change will work only in conda based env. It should work in both scenarios - with and without conda. 

We don't use conda packages for pytorch, torchvision, torchaudio, ipex. Please use pip list instead of conda list.

2024-05-11 02:26 UTC, AshburnLee commented on scripts/pytest-utils.sh
done~ thanks

2024-05-13 14:49 UTC, pbchekin commented on scripts/pytest-utils.sh
> +            echo "Triton wheel is not found" > $TRITON_TEST_REPORTS_DIR/triton_commit_id.txt
I think the script needs to fail rather than print this to `triton_commit_id.txt`.

2024-05-13 14:49 UTC, pbchekin commented on scripts/pytest-utils.sh
> +        echo "Triton wheel directory is not found" > $TRITON_TEST_REPORTS_DIR/triton_commit_id.txt
I think the script needs to fail rather than print this to `triton_commit_id.txt`.

2024-05-13 14:49 UTC, pbchekin commented on scripts/pytest-utils.sh
> +        echo "Not installed" > $TRITON_TEST_REPORTS_DIR/triton_version.txt
I think the script needs to fail rather than print this to `triton_version.txt`.

2024-05-16 09:24 UTC, AshburnLee commented
Two comments:
1. I presume that `test-triton.sh` execution needs dependencies, not only python & triton, but also IPEX and torch, so script should fail as long as one of those could not be found.
2. Currently there are not workloads that generated reports while run `test-triton.sh`, so the change in this PR only works under two conditions: 1. Users will build wheel file under `/python/dist/`, 2. Users call `test-triton.sh` with report: `./scritps/test-triton.sh --reports`

@pbchekin @vlad-penkin Please make sure I understand it right.

2024-05-16 09:24 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +            echo "Triton wheel is not found" > $TRITON_TEST_REPORTS_DIR/triton_commit_id.txt
that makes sense, done~

2024-05-16 09:26 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +        echo "Triton wheel directory is not found" > $TRITON_TEST_REPORTS_DIR/triton_commit_id.txt
done ~

2024-05-16 09:26 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +        echo "Not installed" > $TRITON_TEST_REPORTS_DIR/triton_version.txt
done~

2024-05-16 09:26 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    if pip list | grep triton &> /dev/null; then
done ~

2024-05-16 09:28 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    if pip list | grep intel-extension-for-pytorch &> /dev/null; then
done ~
comment: `import intel_extension_for_pytorch` dose not rely on `torch`,  right?

2024-05-28 03:42 UTC, whitneywhtsang commented
@pbchekin @vlad-penkin Please take another look, thanks!

2024-05-29 10:13 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +        WHEEL=$(find ${SCRIPTS_DIR}/../python/dist -type f -name *.whl)
`WHEEL="${SCRIPTS_DIR}/../python/dist/*.whl"` does not perform file matching operation, `WHEEL` is just a string.

2024-05-29 10:13 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +        if [[ ! -z "$WHEEL" ]]; then
done ,thanks

2024-05-29 10:13 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +            echo "$WHEEL" | sed -n 's/.*git\([a-zA-Z0-9]*\)[^a-zA-Z0-9].*/\1/p' > $TRITON_TEST_REPORTS_DIR/triton_commit_id.txt
In your case, use the commit in Triton source code from local. Done thanks

2024-05-29 10:13 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    elif [ ! -z "$TRITON_PROJ" ]; then
done, thanks~

2024-05-29 10:13 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    fi
done, thanks~

2024-05-29 10:13 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    fi
done, thanks~

2024-05-29 10:13 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    fi
done, thanks~

2024-05-29 10:13 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    fi
done, thanks~

2024-05-29 10:15 UTC, AshburnLee commented
> * Triton needs all dependencies, should fail to execute the script if any of dependencies is not found.
> * For triton build commit id, the report should be able to generated in all scenarios. So if there is no wheel, use the commit id from the local source code.
>   
>   * [check] scenario 1: Install triton from pre-built wheel.
>   * [check] scenario 2: Install triton from compile-triton.sh.
>   * [] Others? no other scenarios found.

* [check] scenario 1: Install triton from pre-built wheel.
* [check] scenario 2: Install triton from compile-triton.sh.
* [check] scenario 3: Install triton from a wheel, in which no commit info is found.

2024-05-29 14:40 UTC, pbchekin commented on scripts/pytest-utils.sh
> +        WHEEL=$(find ${SCRIPTS_DIR}/../python/dist -type f -name *.whl)
> `WHEEL` is just a string

It is a string that interpolated by Bash, `$SCRIPTS_DIR` is a bash variable, `*.whl` is a bash glob. Try it. Even if you replaced `find` with `ls` you still use an external program to get a matching file. You can use bash globbing instead.

2024-05-29 14:49 UTC, pbchekin commented on scripts/pytest-utils.sh
> +    fi
This is simpler and also handles a case when there is more than one *.whl file (possible in a development environment):
```suggestion
    WHEEL=$SCRIPTS_DIR/../python/dist/*.whl
    if [[ -f "$WHEEL" ]]; then
        TRITON_COMMIT=$(echo "$WHEEL" | sed -n 's/.*git\([a-zA-Z0-9]*\)[^a-zA-Z0-9].*/\1/p')
    fi
```

2024-05-30 06:17 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +        WHEEL=$(find ${SCRIPTS_DIR}/../python/dist -type f -name *.whl)
Yes, that's correct, Bash will do Glob in some context.
But in `if` statement, Bash will not do Glob, because `if` statements expects specific values or expressions, rather than a value with `*` that may expand into multiple values. (tried and verified)
So this will not work at least in `if`.

2024-05-30 06:53 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    fi
I wonder how this change solves a case when there exists more then one *.whl? Like `Triron+git1s2d3f.whl` and `Triron+git4g5h6j.whl` ? 
Which commit is the one?
How about this change:
```suggestion
    WHEELS=($SCRIPTS_DIR/../python/dist/*.whl)
    if [[ "${#WHEELS[@]}" -gt 1 ]]; then
        echo "WARNING: Found multiple Triton whls, please leave the one on which Triton was build"
        exit 1
    fi
    if [[ "${#WHEELS[@]}" -eq 1 ]]; then
        TRITON_COMMIT=$(echo "${WHEELS[0]}" | sed -n 's/.*git\([a-zA-Z0-9]*\)[^a-zA-Z0-9].*/\1/p')
    fi
```

2024-05-30 13:40 UTC, pbchekin commented on scripts/pytest-utils.sh
> +    if [[ -n "$TRITON_PROJ" && ! -n "$TRITON_COMMIT" ]]; then
What about
```suggestion
    if [[ $TRITON_PROJ && ! $TRITON_COMMIT ]]; then
```

2024-05-30 13:40 UTC, pbchekin commented on scripts/pytest-utils.sh
> +    if [[ ! -n "$TRITON_COMMIT" ]]; then
```suggestion
    if [[ ! $TRITON_COMMIT ]]; then
```

2024-05-30 13:40 UTC, pbchekin commented on scripts/pytest-utils.sh
> +    if [[ "${#WHEELS[@]}" -eq 1 ]]; then
If there is no *.whl files, then the array has 1 element, you still need to check that the file exists

2024-05-30 13:40 UTC, pbchekin commented on scripts/pytest-utils.sh
> +    if [[ "${#WHEELS[@]}" -eq 1 ]]; then
What about this (haven't tested)?
```
    local TRITON_COMMIT=""
    for wheel in $SCRIPTS_DIR/../python/dist/*.whl; do
        if [[ -f $wheel ]]; then
            if [[ $TRITON_COMMIT ]]; then
                echo "Multiple wheels found"
                exit 1
            fi
            TRITON_COMMIT=$(echo $wheel | sed -n 's/.*git\([a-zA-Z0-9]*\)[^a-zA-Z0-9].*/\1/p')
        fi
    done
```

2024-05-31 05:38 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    if [[ -n "$TRITON_PROJ" && ! -n "$TRITON_COMMIT" ]]; then
Done, thanks ~

2024-05-31 05:38 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    if [[ ! -n "$TRITON_COMMIT" ]]; then
Done, thanks~

2024-05-31 05:38 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    if [[ "${#WHEELS[@]}" -eq 1 ]]; then
> If there is no *.whl files, then the array has 1 element, you still need to check that the file exists

That's true, but in that case TRITON_COMMIT will be empty, which is expected.

2024-05-31 05:38 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +    if [[ "${#WHEELS[@]}" -eq 1 ]]; then
> What about this (haven't tested)?

I've tested it, 
in case `Triton-3.0.0.whl` + `Triton-git1a2s3d.whl`, your change returns `1a2s3d`, but it should fail,
in case `Triton-git1a2s3d-py39.whl` + `Triton-git1a2s3d-310.whl`, your change fail, but as they have the same commit id, so it should return `1a2s3d`.

So I prefer my may, but if you think those cases I've mentioned is probably not real cases, we can use your change.

2024-05-31 15:20 UTC, pbchekin commented on scripts/test-triton.sh
> +    echo "$GPU_DEVICE" > $TRITON_TEST_REPORTS_DIR/gpu.txt
What about moving this to `capture_runtime_env`? We need a single entry point that can be used in CI workflows as well, so it would be convenient to do this:
```
source scripts/pytest-utils.sh
capture_runtime_env
```

2024-05-31 15:20 UTC, pbchekin approved these changes
Looks good, only one minor enhancement left.

2024-06-03 05:18 UTC, AshburnLee commented on scripts/test-triton.sh
> +    echo "$GPU_DEVICE" > $TRITON_TEST_REPORTS_DIR/gpu.txt
> We need a single entry point that can be used in CI workflows as well
Done, good to know, thanks~

2024-06-03 13:06 UTC, AshburnLee commented
@vlad-penkin only need your approval. Thanks~

2024-06-04 02:14 UTC, vlad-penkin approved these changes

2024-06-04 02:38 UTC, merged