[ElementwiseOpToLLVM] Replace bitwise fp32 to bf16 conversion with Intel SPIR-V Extension
intel/intel-xpu-backend-for-triton pull request #1074
Opened 2024-05-09 11:58 UTC by FMarno

Related to issue #1001.

This pass is already lowering `arith::TruncFOp` and `arith::ExtFOp`, so there was the original suggesting of lowering to arith operators didn't make sense, but I have replace most of the bit operations with calls to an Intel SPIR-V extension that translates to a MOV instruction in vISA.
I couldn't remove the round to zero mode of `convertFp32ToBf16`, since the extension only supports round to closest even. The code that calls `convertFp32ToBf16` uses round to closest even by default, so that's fine.

2024-05-09 15:18 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +    return call.getResult();
```
third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp:1291:47: error: conversion from ‘mlir::LLVM::CallOp’ to non-scalar type ‘mlir::Value’ requested
       1291 |     Value call = intel::createSPIRVBuiltinCall(loc, rewriter, ext_func, v);
```
Doesn't compile. I guess you expected there to be some kind of implicit conversion? If that doesn't exist then the current code seems fine to me.

2024-05-09 15:28 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +      StringRef name = "_Z32intel_convert_bfloat16_as_ushortf";
addressed in https://github.com/intel/intel-xpu-backend-for-triton/pull/1074/commits/2b484594623b42313d7c6054839f5c80a827588e

2024-05-09 15:28 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +    StringRef name = "_Z31intel_convert_as_bfloat16_floatt";
addressed in https://github.com/intel/intel-xpu-backend-for-triton/pull/1074/commits/2b484594623b42313d7c6054839f5c80a827588e

2024-05-09 15:49 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +    return call.getResult();
Okey, LGTM :smile:

2024-05-09 15:55 UTC, whitneywhtsang commented
> I couldn't remove the round to zero mode of convertFp32ToBf16, since the extension only supports round to closest even. 

Instead of generating a series of LLVM operations, can it be lowered to `arith::TruncFOp`?

2024-05-09 16:00 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
What do you think of having a GEN operator that perform fp conversion of Bf16ToFp32, Fp16ToFp32, Fp32ToBf16, etc?
It can hide the actual lowering in the GEN to LLVM lowering.

2024-05-09 16:17 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +      StringRef name = "_Z32intel_convert_bfloat16_as_ushortf";
Super minor NIT: `StringLiteral` is preferred for constant strings

2024-05-09 16:17 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +    StringRef name = "_Z31intel_convert_as_bfloat16_floatt";
Super minor NIT: `StringLiteral` is preferred for constant strings

2024-05-09 16:30 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUToLLVM/Utility.h
> +}
Since those other mentioned usages are in a different directory, is it still cool to use the utility function from `TritonIntelGPUTOLLVM`? Do you know if there is some higher level I could put this "utility" function at?

2024-05-09 16:34 UTC, FMarno commented
> > I couldn't remove the round to zero mode of convertFp32ToBf16, since the extension only supports round to closest even.
> 
> Instead of generating a series of LLVM operations, can it be lowered to `arith::TruncFOp`?

This is the stage where we are lowering `arith::TruncFOp` to LLVM, so we just need to deal with it! I tried lowering to `llvm::ftrunc` but that wasn't translated properly by `llvm-spirv`.

2024-05-09 16:39 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
I would say it's not super useful for us, since we will just have to do the same lower but later?
Maybe there is an argument that this could be useful for users of upstream GEN. Sorry, I'm still kind of getting my head around MLIR.

2024-05-09 16:43 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +      StringRef name = "_Z32intel_convert_bfloat16_as_ushortf";
addressed in https://github.com/intel/intel-xpu-backend-for-triton/commit/7c51381212ac0cef4f09b746aa89268ba02aa2cb

2024-05-09 16:43 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +    StringRef name = "_Z31intel_convert_as_bfloat16_floatt";
addressed in https://github.com/intel/intel-xpu-backend-for-triton/commit/7c51381212ac0cef4f09b746aa89268ba02aa2cb

2024-05-09 16:43 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
Right, I am thinking that it could be useful for other projects that want to target Intel platforms. And have all lowering to intel intrinsic calls concentrate in one place.

2024-05-09 16:47 UTC, whitneywhtsang commented
> > > I couldn't remove the round to zero mode of convertFp32ToBf16, since the extension only supports round to closest even.
> > 
> > 
> > Instead of generating a series of LLVM operations, can it be lowered to `arith::TruncFOp`?
> 
> This is the stage where we are lowering `arith::TruncFOp` to LLVM, so we just need to deal with it! I tried lowering to `llvm::ftrunc` but that wasn't translated properly by `llvm-spirv`.

The lowering is not specific to Triton.
I assume other projects will find it useful to convertFp32ToBf16, if we do it here, then other projects cannot benefit from this. If we do it in e.g., `arith::TruncFOp`, then the lowering to LLVM can be reused.

2024-05-10 08:27 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/Utility.h
> +}
Maybe `third_party/intel/include/Dialect/TritonIntelGPU/Transforms/Utility.h`? @whitneywhtsang ?

2024-05-10 08:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
Till we figure out if/what/how GEN will be, I'd keep this as is, but we may want to keep this into account. WDYT?

2024-05-10 08:32 UTC, victor-eds commented
> I assume other projects will find it useful to convertFp32ToBf16, if we do it here, then other projects cannot benefit from this. If we do it in e.g., `arith::TruncFOp`, then the lowering to LLVM can be reused.

I think Finlay means this pattern is lowering `arith.truncf` to `X`. We cannot have `arith.truncf -> arith.truncf`

2024-05-10 08:33 UTC, victor-eds approved these changes
LGTM after reusing `lookupOrCreateSPIRVFn`

2024-05-10 08:42 UTC, victor-eds requested changes
Sorry, missing tests... Can we add where I meantioned? Also add tests for vector conversion.

2024-05-10 11:45 UTC, FMarno commented
> Sorry, missing tests... Can we add where I meantioned? Also add tests for vector conversion.

Tests added. I think added vectorizing is going to be too much work for now.

2024-05-10 11:46 UTC, FMarno commented
I've converted this to a draft so I can investigate the microbenchmark

2024-05-10 13:22 UTC, victor-eds approved these changes
LGTM modulo fixing CI (format of new test)

2024-05-13 10:27 UTC, FMarno commented
@whitneywhtsang I believe this is ready for merging now. I've got a branch ready with a microbench (https://github.com/intel/intel-xpu-backend-for-triton/compare/liyang/microbench...finlay/bfconversion-microbench?expand=1), but I'd like to get this in now and move onto some more work!

2024-05-13 12:25 UTC, whitneywhtsang commented on third_party/intel/lib/GPUToTritonGEN/OpToFuncCallLowering.h
> +#include "third_party/intel/include/Dialect/TritonIntelGPU/Transforms/Utility.h"
```suggestion
#include "intel/include/Dialect/TritonIntelGPU/Transforms/Utility.h"
```

2024-05-13 12:26 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
That's fine with me.

2024-05-13 16:21 UTC, whitneywhtsang commented
@FMarno As discussed in the meeting, please create an issue for the remaining work.

2024-05-13 16:45 UTC, FMarno commented
@whitneywhtsang issue has been created. Thanks for do that fix.

2024-05-13 18:03 UTC, merged