[UT] add skiplist for PVC w/ rolling driver
intel/intel-xpu-backend-for-triton pull request #1093
Opened 2024-05-11 08:03 UTC by AshburnLee

## Functionality
This PR add a skiplist for pytest enabling skip cases in script/skiplist/pvc_rolling when the platform is PVC with Rolling driver.
Request: https://github.com/intel/intel-xpu-backend-for-triton/issues/985

## Result
There are **953** fail tests before this PR, and **0** fail tests after this PR.

2024-05-11 19:26 UTC, gshimansky commented on scripts/capture-hw-details.sh
> +            echo "ltd"
echo "lts"

2024-05-13 00:57 UTC, AshburnLee commented on scripts/capture-hw-details.sh
> +            echo "ltd"
done, thanks~

2024-05-13 14:26 UTC, pbchekin commented on scripts/pytest-utils.sh
> +        fi
The skiplist can be changed by setting `TRITON_TEST_SKIPLIST_DIR`, no need to overwrite the exiting files in the current skiplist.

2024-05-13 14:30 UTC, pbchekin reviewed
I think we do not need to put the existing xfailed tests to the skiplist. We use skiplist for skipped tests instead. Also the default skiplist is for PVC with the rolling driver, no need to create a new one, instead consider renaming default to pvc-rolling.

2024-05-13 17:52 UTC, vlad-penkin requested changes

2024-05-13 17:52 UTC, vlad-penkin commented on scripts/capture-hw-details.sh
> +    local rolling=(821 775)
Please do not hardcode the Rolling driver version numbers.

2024-05-14 02:47 UTC, AshburnLee commented
> I think we do not need to put the existing xfailed tests to the skiplist. We use skiplist for skipped tests instead. Also the default skiplist is for PVC with the rolling driver, no need to create a new one, instead consider renaming default to pvc-rolling.

Oh, I may understand it wrong, I should have put **skipped** tests in the skiplist, not the **xfailed**. OK, will change that and renaming default file.

How about the xfailed cases? do we just leave it as it is? thansks @pbchekin

2024-05-14 13:43 UTC, pbchekin commented
> How about the xfailed cases? do we just leave it as it was?

Yes

2024-05-17 14:21 UTC, AshburnLee commented on scripts/capture-hw-details.sh
> +    local rolling=(821 775)
Remove these two conversion functions as the default platform is PVC with Rolling.

2024-05-20 02:03 UTC, AshburnLee commented on scripts/pytest-utils.sh
> +        fi
Renamed `/default` to `/pvc_rolling`, removed `PVC_DRIVER_SKIPLIST_DIR`

2024-06-10 14:15 UTC, AshburnLee commented
How about approving this PR? Just change the skip list default name as 'pvc_rolling'? @vlad-penkin

2024-06-10 15:17 UTC, pbchekin approved these changes

2024-06-11 14:37 UTC, pbchekin commented
@AshburnLee please sync the PR with the target branch, there is a change to the skip list in #1310.

2024-06-11 15:50 UTC, AshburnLee commented
> @AshburnLee please sync the PR with the target branch, there is a change to the skip list in #1310.

Done, thanks~

2024-06-11 19:21 UTC, vlad-penkin commented
@AshburnLee similar comment, please take into the account this PR:
- #1319

2024-06-12 02:31 UTC, AshburnLee commented
> @AshburnLee similar comment, please take into the account this PR:
> 
> * [[UT] Enable more convert2d tests #1319](https://github.com/intel/intel-xpu-backend-for-triton/pull/1319)

Updated, thanks~

2024-06-13 03:57 UTC, AshburnLee commented
Please give approval @vlad-penkin thanks~

2024-07-10 04:34 UTC, pbchekin commented
No longer needed.

2024-07-10 04:34 UTC, closed without merging