[UT] add skiplist in pvc w/ lts for skipped cases
intel/intel-xpu-backend-for-triton pull request #1156
Opened 2024-05-20 13:07 UTC by AshburnLee

## Functionality
This PR add all SKIPPED  cases to a skiplist in `scripts/skiplist/pvc_lts/`
Solves issue https://github.com/intel/intel-xpu-backend-for-triton/issues/986

## Result
Now there are no SKIPPED cases on PVC w/ LTS driver

## Notes
1. This PR only skips SKIPPED cases, no FAILED cases
2. Agama version is captured form `intel-level-zero-gpu`, because I found the original way won't work on my local PVC w/ LTS, the change in my PR works.

2024-05-20 13:10 UTC, AshburnLee commented
About the convert function from agama to driver type, I can not think of another way but hard code the agama version in the function. @vlad-penkin could you give some tips if this is not a good practice?

2024-05-28 16:49 UTC, pbchekin commented on scripts/skiplist/pvc_lts/language.txt
> +# https://github.com/intel/intel-xpu-backend-for-triton/issues/986
Why this skip list contains more test cases that the existing default skip list? The run (https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9214379486) shows that we do not need to skip more tests than the current skip list has.

2024-05-28 16:49 UTC, pbchekin commented on scripts/capture-hw-details.sh
> +agama_to_driver_type() {
I think we do not need to detect what driver (rolling or lts) is currently installed. Instead, a specific runner should set an environment variable either to select a skip list or to select a release stream (if you still need it for some reason).

2024-05-28 19:33 UTC, vlad-penkin requested changes

2024-05-28 19:33 UTC, vlad-penkin commented on scripts/capture-hw-details.sh
> +agama_to_driver_type() {
@AshburnLee could you please address @pbchekin comments?

2024-05-31 08:03 UTC, AshburnLee commented on scripts/capture-hw-details.sh
> +agama_to_driver_type() {
Thanks~ I'm working on other PR's comments.

2024-06-13 03:11 UTC, AshburnLee commented on scripts/capture-hw-details.sh
> +agama_to_driver_type() {
So from what I understand, in this PR, I just need to: 
1. remove `agama_to_driver_type()` and `xpu_is_pvc()`, 
2. Run `test_triton.sh` and collect `FAILED` cases from the log, and put those `FAILED` in a skiplist `pvc_lts/....txt`

Please confirm that I am right @pbchekin , thank you.

2024-06-13 05:02 UTC, AshburnLee commented on scripts/capture-hw-details.sh
> +agama_to_driver_type() {
And the automation script https://github.com/intel/intel-xpu-backend-for-triton/pull/1196 is not in this scope

2024-06-14 02:34 UTC, pbchekin commented on scripts/capture-hw-details.sh
> +agama_to_driver_type() {
Yes, you can use test report from https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9507147050. This is a run where all errors are ignored and full test report is attached as artifact.

```
all: passed: 17460, failed: 129, skipped: 400, xfailed: 1240, total: 19229, fixme: 12 pass rate (w/o xfailed): 97.06%
```

2024-06-14 15:23 UTC, AshburnLee commented on scripts/capture-hw-details.sh
> +agama_to_driver_type() {
working on it.

2024-06-14 16:31 UTC, AshburnLee commented on scripts/capture-hw-details.sh
> +agama_to_driver_type() {
done~

2024-06-14 17:35 UTC, pbchekin approved these changes

2024-06-24 13:47 UTC, pbchekin commented
Implemented in #1456.

2024-06-24 13:47 UTC, closed without merging