Rewrite RewriteTensorPointer pass to support 2D block store
intel/intel-xpu-backend-for-triton pull request #1193
Opened 2024-05-27 13:25 UTC by mfrancepillois

Prevents `StoreOp`s from being rewritten if it is not suitable for 2D block store.

Addresses Issue: #1143

2024-05-27 13:27 UTC, mfrancepillois commented
Note that the forwarding of the data encoding to the `StoreOp` and the the actual lowering to the 2d block store intrinsic will come in separate PRs.

2024-05-27 15:35 UTC, FMarno requested changes
I think it would be nice to take some inspiration from the changes to rewrite-tensor-pointer.mlir in this PR https://github.com/intel/intel-xpu-backend-for-triton/pull/1187

2024-05-27 15:35 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUTransforms/Utility.cpp
> +  if (auto Enc = tensorType.getEncoding())
I don't think `Enc` follows the style, maybe `enc` or better yet imo `encoding`.

2024-05-27 15:35 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUTransforms/RewriteTensorPointer.cpp
> +///   and not have a DpasEncoding
```suggestion
///   and does not have DpasEncoding
```

2024-05-27 15:35 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUTransforms/RewriteTensorPointer.cpp
> +          }
```suggestion
          auto makeTensorPtrOp = src.getDefiningOp<tt::MakeTensorPtrOp>();
          if (!makeTensorPtrOp || shouldRemove(makeTensorPtrOp, arch)) {
            valueToRemove.insert(src);
          }
```

2024-05-28 01:06 UTC, chengjunlu commented on test/TritonIntelGPU/rewrite-tensor-pointer.mlir
> +// COM: - the block pointers is advanced in row major order: strides[order[0]] == 1
From the experience, the row major order is just `strides[1]==1`, which for 2D case, for general case should be `strides[-1]==1`.

Check the use case here of the `order`.
https://github.com/intel/intel-xpu-backend-for-triton/blob/da631c7b442151182ff4f395193e75df15dcc2ea/python/triton/ops/flash_attention.py#L47

2024-05-28 01:07 UTC, chengjunlu commented on test/TritonIntelGPU/rewrite-tensor-pointer.mlir
> +// COM: - the block pointer pitch is divisible by QW: strides[order[1]] % (64 / elemTypeBitWidth) == 0
The row stride should be `strides[0]` which for 2D case, for general case should be `strides[-2]`.

2024-05-28 10:46 UTC, mfrancepillois commented on third_party/intel/lib/TritonIntelGPUTransforms/Utility.cpp
> +  if (auto Enc = tensorType.getEncoding())
The code has been updated this way.

2024-05-28 10:46 UTC, mfrancepillois commented on third_party/intel/lib/TritonIntelGPUTransforms/RewriteTensorPointer.cpp
> +///   and not have a DpasEncoding
I corrected it. Thanks

2024-05-28 10:46 UTC, mfrancepillois commented on third_party/intel/lib/TritonIntelGPUTransforms/RewriteTensorPointer.cpp
> +          }
Nice suggestion. The code has been updated this way.

2024-05-28 10:50 UTC, mfrancepillois commented on test/TritonIntelGPU/rewrite-tensor-pointer.mlir
> +// COM: - the block pointers is advanced in row major order: strides[order[0]] == 1
You're right. The code only checks the contiguous property for strides[1]. I just copied and pasted the comment from `Case 1`, without paying attention. The comment has now been updated this way.

2024-05-28 10:50 UTC, mfrancepillois commented on test/TritonIntelGPU/rewrite-tensor-pointer.mlir
> +// COM: - the block pointer pitch is divisible by QW: strides[order[1]] % (64 / elemTypeBitWidth) == 0
Same as above. The comment has been updated this way.

2024-05-28 12:53 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUTransforms/RewriteTensorPointer.cpp
> +        }
We can remove the `tt::StoreOp` condition and add it to `LoadOp` case,
```cpp
} else if (llvm::isa<tt::AdvanceOp, tt::LoadOp, tt::StoreOp>(op)) {
        markTensorPointerForRemoval(op->getOperand(0));
} 
```

2024-05-28 15:04 UTC, FMarno approved these changes

2024-05-28 23:58 UTC, whitneywhtsang approved these changes

2024-05-28 23:58 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUTransforms/Utility.cpp
> +  return false;
```suggestion
  return isa_and_nonnull<ttgi::DpasEncodingAttr>(tensorType.getEncoding());
```

2024-06-11 18:30 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUTransforms/RewriteTensorPointer.cpp
>      };
This is a bit more readable.
[Suggestion]: 
```
auto usedByStoreOp = [](Value val) { 
   return llvm::any_of(val.getUsers(), [](Operation *user){ return isa<tt.StoreOp>(user); });
};

2024-06-24 15:18 UTC, etiotto approved these changes

2024-06-24 15:19 UTC, merged