Optimize PrefetchBlock pass
intel/intel-xpu-backend-for-triton pull request #1240
Opened 2024-06-04 06:41 UTC by LiyangLingIntel

2024-06-04 14:24 UTC, whitneywhtsang commented on third_party/intel/backend/compiler.py
> +                intel.passes.ttgpuir.add_prefetch_block(pm, opt.prefetch_distance, opt.inject_split_barrier)
Why not use `opt.num_stages` directly?

2024-06-05 01:18 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUTransforms/PrefetchBlock.cpp
> +    LoadInfo(tt::DotOp dot, tt::AdvanceOp advance, SmallVector<Value> offsets,
this pass is meant to be general, not bound to dot op. 
so try to move prefetch after load.

2024-06-05 01:56 UTC, LiyangLingIntel commented on third_party/intel/backend/compiler.py
> +                intel.passes.ttgpuir.add_prefetch_block(pm, opt.prefetch_distance, opt.inject_split_barrier)
In my understanding `opt.num_stages` is used by `SoftwarePipeline` pass, it's designed for scheduling inner loop operations by stages, on semantic it's different with `prefetch_distance`. Use `opt.prefetch_distance` here is to reduce confusion.

2024-06-05 01:57 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUTransforms/PrefetchBlock.cpp
> +    LoadInfo(tt::DotOp dot, tt::AdvanceOp advance, SmallVector<Value> offsets,
OK, I'll update it soon. Thanks for the suggestion.

2024-06-05 03:48 UTC, whitneywhtsang commented on third_party/intel/backend/compiler.py
> +    inject_split_barrier: bool = os.getenv("TRITON_INTEL_SPLIT_BARRIER", "0") == "1"
Let's try to be consistent with our usages of `os.getenv` and `os.environ.get`. Unless there is a reason to be different?

2024-06-05 05:29 UTC, LiyangLingIntel commented on third_party/intel/backend/compiler.py
> +    inject_split_barrier: bool = os.getenv("TRITON_INTEL_SPLIT_BARRIER", "0") == "1"
`os.getenv` is a shortcut to `os.environ.get` with `None` default value. Change them to `os.environ.get` for consistency.
Thanks for the suggestion.

2024-06-05 10:42 UTC, Dewei-Wang-sh approved these changes
lgtm

2024-06-05 10:46 UTC, whitneywhtsang approved these changes

2024-06-05 13:43 UTC, etiotto requested changes

2024-06-05 13:43 UTC, etiotto commented on third_party/intel/backend/compiler.py
> +    inject_split_barrier: bool = os.environ.get("TRITON_INTEL_SPLIT_BARRIER", "0") == "1"
I do not think this is necessary. Introducing too many tuning flags is confusing. What is the difference in performance for cases that benefit from injecting the split barrier ? And how much does injecting a split barrier by default hurts for some configurations?

2024-06-05 13:43 UTC, etiotto commented on third_party/intel/backend/compiler.py
> +                intel.passes.ttgpuir.add_prefetch_block(pm, opt.prefetch_distance, opt.inject_split_barrier)
We do not need both num_stages and prefetch_distance. Remove "num_stages" then.

2024-06-05 13:43 UTC, etiotto commented on third_party/intel/backend/compiler.py
> +        args["prefetch_distance"] = opts.get("num_stages", 2)
remove num_stages please and replace it with prefetch_distance. Having both is not necessary.

2024-06-05 18:41 UTC, whitneywhtsang reviewed
https://github.com/intel/intel-xpu-backend-for-triton/pull/1256 should be able to address Ettore's comments. @LiyangLingIntel Please check if that PR is ok with you.

2024-06-06 02:38 UTC, whitneywhtsang commented on third_party/intel/backend/compiler.py
> +            extern_libs['libdevice'] = os.environ.get("TRITON_LIBDEVICE_PATH",
Let's change back to use `os.getenv` in this case, to be consistent with nvidia and amd.

2024-06-06 02:38 UTC, whitneywhtsang approved these changes

2024-06-06 02:43 UTC, LiyangLingIntel commented on third_party/intel/backend/compiler.py
> +            extern_libs['libdevice'] = os.environ.get("TRITON_LIBDEVICE_PATH",
Updated.

2024-06-06 02:52 UTC, LiyangLingIntel commented on third_party/intel/backend/compiler.py
> +    inject_split_barrier: bool = os.environ.get("TRITON_INTEL_SPLIT_BARRIER", "0") == "1"
There only 2 cases benefit from split barrier with around 20% performance gain, for most cases there are 5-10% performance drop.
I removed `prefetch_distance` and `inject_split_barrier` from this pull request for sake of simplicity. keep use `num_stages` to represent `prefetch_distance` to make the interface consistent with upstream.

2024-06-06 02:56 UTC, LiyangLingIntel commented on third_party/intel/backend/compiler.py
> +        args["prefetch_distance"] = opts.get("num_stages", 2)
`num_stages` is necessary for `SoftwarePipeline` pass, so I remove the option `prefetch_distance` and keep it as it was. In this way we can make our interface consistent with upstream as well.

2024-06-06 14:11 UTC, etiotto commented on third_party/intel/backend/compiler.py
> +    inject_split_barrier: bool = os.environ.get("TRITON_INTEL_SPLIT_BARRIER", "0") == "1"
why 5-10% degradation ? Have you reported the issue to IGC ?

2024-06-06 14:12 UTC, etiotto commented on third_party/intel/backend/compiler.py
> +        args["prefetch_distance"] = opts.get("num_stages", 2)
ok

2024-06-06 14:13 UTC, etiotto approved these changes

2024-06-06 14:13 UTC, merged