Use sub group reduce operation in warp reduce.
intel/intel-xpu-backend-for-triton pull request #1262
Opened 2024-06-06 03:42 UTC by chengjunlu

Use the Triton Gen subgroup reduce operator for the warp reduce.

2024-06-06 03:55 UTC, whitneywhtsang commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
>      callOp.setCConv(LLVM::cconv::CConv::SPIR_FUNC);
Attributes on function and call op should match, can you please add convergent to the call op as well?

2024-06-06 03:55 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TargetInfo.cpp
> +  // horizontal reduce with interleave stride not support.
```suggestion
  // Horizontal reduce with interleave stride not support.
```

2024-06-06 03:55 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TargetInfo.cpp
> +  if (isa<arith::AddFOp>(reduceOp))
can use TypeSwitch?

2024-06-06 03:55 UTC, whitneywhtsang commented on test/Conversion/intel/tritongpu_to_gen.mlir
> +    // CHECK: %[[HELPER_LANE:.*]] = llvm.mlir.constant(0 : i32) : i32
missing a check to WaveAll here?

2024-06-06 05:36 UTC, chengjunlu commented on third_party/intel/lib/TritonIntelGPUToLLVM/TargetInfo.cpp
> +  if (isa<arith::AddFOp>(reduceOp))
Yes

2024-06-06 05:36 UTC, chengjunlu commented on test/Conversion/intel/tritongpu_to_gen.mlir
> +    // CHECK: %[[HELPER_LANE:.*]] = llvm.mlir.constant(0 : i32) : i32
Added

2024-06-06 13:04 UTC, etiotto submitted a review, later dismissed

2024-06-06 13:04 UTC, etiotto commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
>      callOp.setCConv(LLVM::cconv::CConv::SPIR_FUNC);
Let's use `createDeviceFunctionCall` and the new Attribute builder facilities to create all of the device function please.

2024-06-06 14:33 UTC, etiotto requested changes

2024-06-06 14:33 UTC, etiotto commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
>      callOp.setCConv(LLVM::cconv::CConv::SPIR_FUNC);
why did you resolve this comment without addressing it ? Reopening, please address the comment. Thanks.

2024-06-06 15:21 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUToLLVM/TargetInfo.cpp
> +          [&](auto) { reduceKind = TritonGEN::ReduceKind::PROD; });
```suggestion
```suggestion
    std::optional<TritonGEN::ReduceKind> reduceKind =  llvm::TypeSwitch<mlir::Operation *, TritonGEN::ReduceKind>(reduceOp)
      .Case<arith::AddFOp>(
          []{ return TritonGEN::ReduceKind::FSUM; })
      .Case<arith::MaxNumFOp>(
          [] { return TritonGEN::ReduceKind::FMAX; })
      .Case<arith::MinNumFOp>(
          [] { return TritonGEN::ReduceKind::FMIN; })
      .Case<arith::MulFOp>(
          [] { return TritonGEN::ReduceKind::FPROD; })
      .Case<arith::AddIOp>(
          [] { return TritonGEN::ReduceKind::SUM; })
      .Case<arith::AndIOp>(
          [] { return TritonGEN::ReduceKind::AND; })
      .Case<arith::OrIOp>([] { return TritonGEN::ReduceKind::OR; })
      .Case<arith::XOrIOp>(
          [] { return TritonGEN::ReduceKind::XOR; })
      .Case<arith::MinSIOp>(
          [] { return TritonGEN::ReduceKind::IMIN; })
      .Case<arith::MinUIOp>(
          [] { return TritonGEN::ReduceKind::UMIN; })
      .Case<arith::MaxSIOp>(
          [] { return TritonGEN::ReduceKind::IMAX; })
      .Case<arith::MaxUIOp>(
          [] { return TritonGEN::ReduceKind::UMAX; })
      .Case<arith::MulIOp>(
          [] { return TritonGEN::ReduceKind::PROD; })
       .Default(std::nullopt);
```
```

2024-06-06 22:30 UTC, whitneywhtsang commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
>      callOp.setCConv(LLVM::cconv::CConv::SPIR_FUNC);
Done in https://github.com/intel/intel-xpu-backend-for-triton/pull/1277.

2024-06-07 00:04 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TargetInfo.cpp
> +          [&](auto) { reduceKind = TritonGEN::ReduceKind::PROD; });
done.

2024-06-07 02:14 UTC, whitneywhtsang approved these changes
@chengjunlu Please confirm you are ok with the new changes.

2024-06-07 02:53 UTC, chengjunlu commented
> @chengjunlu Please confirm you are ok with the new changes.

Yes. LGTM

2024-06-07 02:55 UTC, merged

2024-06-07 14:02 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TargetInfo.cpp
> +  Operation *reduceOp = yield->getOperand(0).getDefiningOp();
Is it always true that the first operand of the terminator instruction is a reduce operation in this context?
The variable name imply so. If this is the case one should add an assert. It it is not always true the variable name should be generic.