Optimize for small M gemm
intel/intel-xpu-backend-for-triton pull request #1291
Opened 2024-06-07 16:56 UTC by quintinwang5

For some small m shape, skip prefetch A .

2024-06-10 13:51 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUTransforms/PrefetchBlock.cpp
> +  char *envPrefetch = std::getenv("TRITON_INTEL_SKIP_PREFETCH_A");
Why do we need an env. variable ?  Isn't skipping prefetch for small shapes always profitable ?

2024-06-10 14:21 UTC, etiotto reviewed
I do not think we should use env. variables to either prefetch or not. We need a heuristic enabled by default.

2024-06-10 14:28 UTC, etiotto requested changes

2024-06-10 14:28 UTC, etiotto commented on python/triton/language/semantic.py
> -    assert lhs.shape[-2].value >= 16 and lhs.shape[-1].value >= 16 \
We cannot just remove code from files used upstream.  The first question is why do we need to remove this assert ? Is it because you want to test shapes that have a small M ?  If Triton consider this matmul shape invalid then I do not think we can handle it until the language remove this semantic constraint on the tl.dot operation.

2024-06-10 17:49 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUTransforms/PrefetchBlock.cpp
Please add a lit test.

2024-06-10 17:49 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUTransforms/PrefetchBlock.cpp
> +    sizePerWarp[1] = std::max((unsigned)32, ceil<unsigned>(n, warpsPerCTA[1]));
Why these need to be changed when skipping prefetch?

2024-06-11 01:15 UTC, quintinwang5 commented on third_party/intel/lib/TritonIntelGPUTransforms/PrefetchBlock.cpp
> +  char *envPrefetch = std::getenv("TRITON_INTEL_SKIP_PREFETCH_A");
No. For most small-m shapes, this will benefit performance. But we found a big drop(95%+ to 80%-) on one shape (mxnxk=8x16384x128). We've not investigated into the reason.

2024-06-12 17:11 UTC, etiotto commented on python/triton/language/semantic.py
> -    assert lhs.shape[-2].value >= 16 and lhs.shape[-1].value >= 16 \
For this we could open an issue to upstream this change to OpenAI is they accept it.

2024-06-17 07:47 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUTransforms/PrefetchBlock.cpp
> +    RankedTensorType rtTy = cast<RankedTensorType>(load.getResult().getType());
this pass aims to be general and not limited to gemm case unless proven necessary.

2024-06-19 15:23 UTC, whitneywhtsang commented
@quintinwang5 Should we close this PR?

2024-06-21 02:20 UTC, quintinwang5 commented
Close this PR per our disscusions before.
Reasons:
1. Hard to upstream the semantic restirction of tt.dot's shape
2. Need more insight about the mechanism of 'Not prefetch A'. Maybe an analysis pass is needed.

2024-07-09 18:37 UTC, etiotto commented
I think this can be closed now.

2024-07-09 18:37 UTC, closed without merging