Add Intel-specific development instructions
intel/intel-xpu-backend-for-triton pull request #1392
Opened 2024-06-18 16:50 UTC by alexbaden

2024-06-18 16:58 UTC, YarShev commented on DEVELOPMENT.md
> +This short guide covers creating a basic development environment, installing needed dependencies, and best practices for building and running Triton on different Intel platforms.
```suggestion
This short guide covers creating a basic development environment, installing needed dependencies, and
best practices for building and running Triton on different Intel platforms. 
```
To not have long lines I would break these and all below.

2024-06-18 16:58 UTC, YarShev commented on DEVELOPMENT.md
> +The LTS, Production, and Rolling Stable release streams are supported. Some performance optimizations may not be available with the LTS driver package. For development, we recomend rolling stable.
```suggestion
The LTS, Production, and Rolling Stable release streams are supported. Some performance optimizations may not be available with the LTS driver package. For development, we recommend rolling stable. 
```

2024-06-18 20:59 UTC, YarShev commented on DEVELOPMENT.md
> +This short guide covers creating a basic development environment, installing needed dependencies, and best practices for building and running Triton on different Intel platforms.
@alexbaden, would you split the long lines into multiple ones to keep the text compact?

2024-06-18 21:54 UTC, vlad-penkin requested changes
@alexbaden good job on a first cut! Let's add a little bit more detail.

In my opinion the overall first principles for the instruction on dev environment creation are:
- keep it simple
- minimal number of the installation steps and choices user needs to make
- no underlying assumption on what is installed on user machine
- minimal number of the system wide installs using Linux package managers (apt in our case)
- ease of installation clean up and reversal to the baseline state (for example by recreating everything from scratch)

2024-06-18 21:54 UTC, vlad-penkin commented on DEVELOPMENT.md
> +# Developer Guide
I suggest to add a section dedicated to the python base envs and suggest two alternatives:
- virtualenv
- conda 

For conda the recommended setup is `conda create -n xpu -c conda-forge python=3.10 gh jq` and then do pip install if needed for everything else.

2024-06-18 21:54 UTC, vlad-penkin commented on DEVELOPMENT.md
> +The primary software dependency is oneAPI. The best way to get oneAPI for PyTorch / Triton development is to use the [Intel PyTorch Dependency Bundle](https://www.intel.com/content/www/us/en/develope
1) I suggest to provide the recommendation on the packaging option. My preference is offline installer - it's much more easier to maintain, delete from the system. Offline installer will also allow you to have multiple installs on the same machine (PTDB and Regular oneAPI Base Kit).

2) Lets add recommended env activation sequence, for example
- `source ~/miniforge/bin/activate`
- `conda activate xpu`
- `source /opt/intel/oneapi/setvars.sh`

2024-06-18 21:54 UTC, vlad-penkin commented on DEVELOPMENT.md
> +* Pre-installed wheels can be fetched with the GitHub CLI tool `gh`. The default version on Ubuntu 22.04 is too old to support some flags we use, so install the latest from GitHub APT repo using [the
conda-forge binaries are usually up-to-date and a viable option to - `conda -c conda-forge install gh`

2024-07-09 18:37 UTC, etiotto commented
@alexbaden  is this work still onging ?

2024-07-11 13:34 UTC, vlad-penkin commented
@etiotto this PR is needed, not a first priority for July though. For more details see linked issue:
- #1393

2024-07-11 16:32 UTC, alexbaden commented on DEVELOPMENT.md
> +# Developer Guide
I think it is better to leave conda as an exercise to the reader. AFAIK the core Intel development team does not used conda, so it will be difficult to maintain these instructions.

2024-07-11 16:34 UTC, alexbaden commented on DEVELOPMENT.md
> +* Pre-installed wheels can be fetched with the GitHub CLI tool `gh`. The default version on Ubuntu 22.04 is too old to support some flags we use, so install the latest from GitHub APT repo using [the
See above re:conda.

2024-07-11 16:35 UTC, alexbaden commented on DEVELOPMENT.md
> +This short guide covers creating a basic development environment, installing needed dependencies, and best practices for building and running Triton on different Intel platforms.
I applied our formatting script.

2024-07-11 16:35 UTC, alexbaden commented
I have made the requested updates - I suggest we merge and refine as needed.

2024-07-12 08:01 UTC, YarShev commented on DEVELOPMENT.md
> +* Pre-installed wheels can be fetched with the GitHub CLI tool `gh`. The default version on Ubuntu 22.04 is too old to support some flags we use, so install the latest from GitHub APT repo using [the
Maybe we should clarify what pre-installed wheels are meant here?

2024-07-12 12:58 UTC, YarShev commented on DEVELOPMENT.md
> +The primary software dependency is oneAPI. The best way to get oneAPI for PyTorch / Triton development is to use the [Intel PyTorch Dependency Bundle](https://www.intel.com/content/www/us/en/develope
Why are we missing "Step 1: Install Intel Data Center GPU Drivers"?

2024-07-12 14:52 UTC, alexbaden commented on DEVELOPMENT.md
> +* Pre-installed wheels can be fetched with the GitHub CLI tool `gh`. The default version on Ubuntu 22.04 is too old to support some flags we use, so install the latest from GitHub APT repo using [the
It should probably read "pre-built". I will make the change.

2024-07-12 14:53 UTC, alexbaden commented on DEVELOPMENT.md
> +The primary software dependency is oneAPI. The best way to get oneAPI for PyTorch / Triton development is to use the [Intel PyTorch Dependency Bundle](https://www.intel.com/content/www/us/en/develope
We prefer to provide our own driver install instructions. They are functionally equivalent but more appropriate for Triton development.

2024-07-17 20:42 UTC, pbchekin approved these changes

2024-07-18 02:04 UTC, pbchekin commented
What about using wiki (https://github.com/intel/intel-xpu-backend-for-triton/wiki) for documents like this? The editing process is simpler (no CI runs, reviews) and more user-friendly (UI editor in the browser).

2024-08-01 14:23 UTC, merged