Prepare for using GPU to LLVMSPV upstream pass
intel/intel-xpu-backend-for-triton pull request #1572
Opened 2024-07-05 14:42 UTC by FMarno

This PR introduces a few changes that should cause no functional changes, but will make the transition to the upstream gpu-to-llvmspv pass.
One change is removing most attributes from function calls. An example of the removed attributes could be: `{function_type = !llvm.func<i64 (i32)>, linkage = #llvm.linkage<external>, passthrough = ["nounwind", "willreturn", ["memory", "0"]], sym_name = "_Z12get_group_idj", visibility_ = 0 : i64}`. Here the passthrough attributes `nounwind` is redundant because there are no exceptions in the SPIRV execution model. `willreturn` and `memory` are not needed to be functionally correct. There other attributes are just copied from the function declaration and are not needed I believe.
The other big change is return type of the TritonGEN id ops. There were a few extra truncation and extension operations in there that are not needed. Translating GetProgramId will already return a 32-bit value because of the index cast here: https://github.com/intel/intel-xpu-backend-for-triton/blob/7358f79c43d7948dd282c237e73787b9b15cbd19/third_party/intel/lib/TritonIntelGPUToLLVM/TargetInfo.cpp#L73-L85

2024-07-08 09:40 UTC, victor-eds reviewed
Note you're right there is no need to specify `nounwind` in SPIR-V, but we're still at LLVM level. All functions should be `nounwind` to express SPIR-V semantics in LLVM.

I'd revert the attribute changes and keep the `index` type ones. We should also check there is no performance regression running CI on this PR (after reverting the attribute changes).

2024-07-08 12:09 UTC, etiotto commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> -        ctx);
We should not remove any attribute because the call LLVM's `opt` at -O3. The attribute convey semantic information that the optimizer can leverage to perform transformations. For example, if a function does not throw an exception it should have the `nounwind` attribute or else it cannot be hoisted outside of a loop because it may have side effects.

2024-07-08 20:02 UTC, etiotto requested changes
The attributes attached to the function the compiler generates should be preserved.

2024-07-15 13:28 UTC, victor-eds commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> -        ctx);
We should probably have the following attributes:
- `subgroup_shuffle`, `barrier`: `convergent`, `nounwind`
- Builtins: `nounwind`, `willreturn`, memoryeffects: `none`

We would need to add `nounwind` and `willreturn` to `llvm.func`. Then set all of the attributes I mention here in the pass.


Note all OCL functions are `nounwind`, so we can set that unconditionally in the pass.

2024-07-15 14:17 UTC, victor-eds commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> -        ctx);
Note this should not be part of this PR, but followup ones upstream

2024-07-16 10:55 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +    return {rewriter.create<LLVM::SExtOp>(op.getLoc(), elemTy, operands[0][0])};
That function can return `arith::IndexCastOP`, which is what we are trying to lower here. That seems like it could cause problems.

2024-07-16 16:05 UTC, FMarno commented on test/TritonIntelGPU/store-to-llvm-2dstore.mlir
> +    // CHECK:           %[[SUB_GROUP_ID_RAW:.*]] = llvm.call spir_funccc @_Z25__spirv_BuiltInSubgroupIdv()
There was no clear way for me to get rid of this `sext` followed by `trunc`, since `gpu.subgroup_id` is expected to return the index type (64 after the change to `third_party/intel/lib/TritonIntelGPUToLLVM/TritonGPUToLLVM.cpp`), and `triton_gen.subgroup.id` always returns a 32-bit value so truncates the index.

2024-07-16 16:08 UTC, FMarno commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> -        ctx);
The attributes have been restored to the function declaration, but are removed from the call site. From my reading of the llvm reference manual, that should be equivalent.

2024-07-16 16:54 UTC, etiotto commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> -        ctx);
I'd rather have them also on the call site, like the existing implementation. This *might* be conservative but is safer (otherwise we need to do a performance run and also test the POC branches for FlashAttention + GEMM).

2024-07-17 12:08 UTC, FMarno commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> -        ctx);
To have the attributes on the call sites, I will need to add them to the llvm ir dialect upstream. I don't think it makes sense to do that for `nounwind` and `willreturn` since both of the description in the [llvm reference manual](https://llvm.org/docs/LangRef.html#function-attributes) read like they are about the function declaration, not the call site. `memory(none)` could be added to the call site and the reference manual does mention that, but I don't think it's needed.

2024-07-17 12:43 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/ElementwiseOpToLLVM.cpp
> +    return {rewriter.create<LLVM::SExtOp>(op.getLoc(), elemTy, operands[0][0])};
Oh, my bad. LGTM then

2024-07-17 16:17 UTC, etiotto commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> -        ctx);
@whitneywhtsang which LLVM pass was looking at call site attributes  (and not working if only the function attribute was set) ? I recall there was some LLVM pass that did that, do you recall ?

2024-07-17 18:04 UTC, whitneywhtsang commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> -        ctx);
e.g., JumpThreading determine if callsite is convergent by looking at the call instruction: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/Scalar/JumpThreading.cpp#L487
InstCombine would remove the convergent attribute from the call, if the callee is not marked convergent: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp#L3856
So for convergent attribute, it needs to be in both callsite and callee.

2024-07-17 18:10 UTC, whitneywhtsang commented on test/TritonIntelGPU/store-to-llvm-2dstore.mlir
> +    // CHECK:           %[[SUB_GROUP_ID_RAW:.*]] = llvm.call spir_funccc @_Z25__spirv_BuiltInSubgroupIdv()
How about changing triton_gen.subgroup.id to return indextype?

2024-07-18 13:36 UTC, FMarno commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> -        ctx);
Ok, I'm convinced that doing the upstream LLVM work is worth it. I will add all the attributes we might need (`convergent`, `willreturn`, `nounwind`, `memory(none)` on `llvm.call` at the same time, I don't think it will do any harm for everyone to have the option.

2024-07-18 13:58 UTC, victor-eds commented on test/TritonIntelGPU/store-to-llvm-2dstore.mlir
> +    // CHECK:           %[[SUB_GROUP_ID_RAW:.*]] = llvm.call spir_funccc @_Z25__spirv_BuiltInSubgroupIdv()
I assume further optimization passes will handle this (`trunc(ext(x)) -> x` is safe), so I wouldn't worry much.

2024-07-18 15:44 UTC, whitneywhtsang commented on test/TritonIntelGPU/store-to-llvm-2dstore.mlir
> +    // CHECK:           %[[SUB_GROUP_ID_RAW:.*]] = llvm.call spir_funccc @_Z25__spirv_BuiltInSubgroupIdv()
I don't worry much about this too, just pointing out in case is an alternative easy change.

2024-07-18 16:03 UTC, victor-eds commented on test/TritonIntelGPU/store-to-llvm-2dstore.mlir
> +    // CHECK:           %[[SUB_GROUP_ID_RAW:.*]] = llvm.call spir_funccc @_Z25__spirv_BuiltInSubgroupIdv()
The issue's we wanna use `gpu.subgroup_id` and that will return `index`. If index is `i64`, we will still do:
```
%call_res = call : i32
%operation_res = ext %call_res : i32 to i64
// We will operate on i32 with this, so
%sid = trunc %operation_res : i64 to i32
```

So I'm not sure we can do much here.

2024-07-19 01:09 UTC, whitneywhtsang commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
>      LLVM::CallOp callOp = createDeviceFunctionCall(rewriter, funcName, retType,
Should we change `retType` from `i64` to `index` type?

2024-07-19 08:18 UTC, victor-eds commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
>      LLVM::CallOp callOp = createDeviceFunctionCall(rewriter, funcName, retType,
`typeConverter->getIndexType()` should be it.

2024-07-19 18:56 UTC, whitneywhtsang commented on test/TritonIntelGPU/store-to-llvm-2dstore.mlir
> +    // CHECK:           %[[SUB_GROUP_ID_RAW:.*]] = llvm.call spir_funccc @_Z25__spirv_BuiltInSubgroupIdv()
I am thinking https://github.com/intel/intel-xpu-backend-for-triton/pull/1659, WDYT?

2024-07-30 10:29 UTC, FMarno commented
Closing in favour of #1734

2024-07-30 10:29 UTC, closed without merging