Attn convert llvm
intel/intel-xpu-backend-for-triton pull request #1574
Opened 2024-07-08 09:41 UTC by Dewei-Wang-sh

2024-07-19 09:31 UTC, victor-eds reviewed
Please, can we have test for every pattern we're changing here?

2024-07-19 09:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +// fixme: support it in upstream constantOpLowering
This case should not be upstream as tensors cannot be directly converted to LLVM dialect.

2024-07-19 09:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        VectorType::get(vecType.getNumElements(), vecType.getElementType());
Isn't `dstAttrType` the same type as `vecType`?

2024-07-19 09:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    rewriter.replaceOp(op, result);
```suggestion
    auto poison = rewriter.create<LLVM::PoisonOp>(loc, vecTy);
    auto splat = rewriter.create<LLVM::InsertElementOp>(
        loc, vecTy, poison, adaptor.getSrc(),
        rewriter.create<LLVM::ConstantOp>(loc, rewriter.getI32Type(), 0));
    auto convertedTy = typeConverter->convertType(resultType);
    auto num = cast<VectorType>(convertedTy).getNumElements();
    SmallVector<int32_t> indices(num, 0);
    auto attr = rewriter.getDenseI32ArrayAttr(indices);
    Value result = rewriter.create<LLVM::ShuffleVectorOp>(loc, convertedTy,
                                                          splat, poison, attr);
    rewriter.replaceOp(op, result);
```

Slightly better

2024-07-19 09:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    rewriter.replaceOp(op, adaptor.getSrc());
Will we always get `adaptor.getSrc().getType() == op.getType()`?

2024-07-19 09:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      assert(0 && "add more support");
Can we just add the rest of the cases here now?

2024-07-19 09:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +class ReduceOpConversion
Is this reduction pattern correct? Wouldn't we end up having each subgroup reduce a slice, but not the whole tensor?

2024-07-19 09:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +class BroadcastOpConversion
I'm not sure this and `tt.expand_dims` patterns are correct.

2024-07-19 09:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +};
Why do we need this?

2024-07-19 09:31 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TypeConverter.cpp
> +      if (!type.getEncoding())
Dot operand encoding should go here too?

2024-07-19 15:45 UTC, etiotto requested changes

2024-07-19 15:45 UTC, etiotto commented on third_party/intel/backend/compiler.py
> +        def make_llir(mod, metadata, opt):
Can we use the default pass pipeline "make_llir" code ? We are producing TritonGPU IR and the existing "make_llir" should work fine. 

What is the reason it does not ?

2024-07-23 01:53 UTC, Dewei-Wang-sh commented on third_party/intel/lib/GPUToTritonGEN/GPUToTritonGENPass.cpp
> +              "uniformly (entire subgroup).");
not for now.
great, we can use spirv-v if needed.

2024-07-23 01:53 UTC, Dewei-Wang-sh commented on third_party/intel/lib/GPUToTritonGEN/GPUToTritonGENPass.cpp
> +    }
as discussed in the meeting, we can leave this to future development.

2024-07-23 02:04 UTC, whitneywhtsang commented on third_party/intel/lib/GPUToTritonGEN/GPUToTritonGENPass.cpp
> +              "uniformly (entire subgroup).");
FYI, our subgroup reduce all lowering already uses the OCL non_uniform version.
If we want to use that, we need to change tritongen subgroup reduce to remove convergent attribute.

2024-07-23 02:16 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    } break;
insert element is scalable, we can change the condition to "default" instead of 8

2024-07-23 02:17 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +// fixme: support it in upstream constantOpLowering
if upstream do not accept it for now, we keep it local.
in the future, maybe upstream will change, just have this fixme for attention

2024-07-23 02:27 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +class ReduceOpConversion
yes, it's correct.
in advanced path, we already split it to a tensor that works on this warp.

2024-07-23 02:36 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +class BroadcastOpConversion
yes, it's correct, other wise FA2 can not work.
after we add more lit test, you can see that more directly.

2024-07-23 02:38 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +};
upstream do not replace "fdiv" with "rcp + fmul", right?

2024-07-23 13:12 UTC, LiyangLingIntel commented on third_party/intel/backend/compiler.py
> +        def make_llir(mod, metadata, opt):
This change was because we do not want `add_allocate_shared_memory` pass in flash attention lowering.
I have removed this change from this PR, this PR we can just focus on the passes which are lowering to LLVM. 
When the preconditions are all merged, we can decide if it's really necessary in last stage of productization PR.

2024-07-23 13:14 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TypeConverter.cpp
> +      if (!type.getEncoding())
Added the Dot operand encoding check, thanks for pointing this out.

2024-07-23 13:15 UTC, LiyangLingIntel commented on third_party/intel/lib/GPUToTritonGEN/GPUToTritonGENPass.cpp
> +  matchAndRewrite(mlir::gpu::SubgroupReduceOp op, OpAdaptor adaptor,
Updated.

2024-07-23 13:17 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +class BroadcastOpConversion
I'm preparing some lit tests for the new added pattern. Will upload them later.

2024-07-23 13:18 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    } break;
Done.

2024-07-23 13:18 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        offsetY = tmp;
Done.

2024-07-23 13:24 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      // fixed f16 for now
Because we currently only handle 16 bitwidth datatype for FlashAttn cases. Same as fulfilling `reduce` modes, I left a `FIXME` here. We can add support for datatype like tf32, fp8 in following PR when we do have these requirements.

2024-07-23 13:31 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonGPUToLLVM.cpp
> +          mlir::IntegerAttr::get(mlir::IntegerType::get(context, 32), 0));
Because we do not use shared local memory for FlashAttn lowering. Here we simply set it to 0.

2024-07-23 14:54 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonGPUToLLVM.cpp
> +          mlir::IntegerAttr::get(mlir::IntegerType::get(context, 32), 0));
Yes, I understand. It just seems like a limitation having to specify this explicitly. LGTM.

2024-07-25 15:45 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +};
Moved these 2 custom Arith ops lowering to [lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp](https://github.com/intel/intel-xpu-backend-for-triton/pull/1574/files#diff-74d7de43eec8505eb41b6601905cf22d650af1b24ab3d6329199d45a62112ebc)

2024-07-25 15:50 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    assert((isa<VectorType, RankedTensorType>(srcType)));
Updated.

2024-07-25 16:01 UTC, whitneywhtsang commented on test/Conversion/intel/arith_to_llvm.mlir
> -// RUN: env TRITON_INTEL_ADVANCED_PATH=1 triton-opt %s -split-input-file --convert-triton-intel-gpu-to-llvm | FileCheck %s --check-prefixes=CHECK,CHECK-VECTOR
Why is this removed?

2024-07-26 08:45 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        transpose ? ptrOp.getStrides()[1] : ptrOp.getStrides()[0], true);
I did not quite get your point here. Do you mean if it's a 1D tensor will fail here?
If so, yes, I changed the assertion from `tensorType.getRank() <= 2` to `tensorType.getRank() == 2`. Basically this conversion only works for 2D blocked IO operations.

2024-07-26 08:55 UTC, LiyangLingIntel commented on third_party/intel/lib/GPUToTritonGEN/GPUToTritonGENPass.cpp
> +    int sgSize = mod->getAttrOfType<IntegerAttr>("triton_intel_gpu.min_sg_size")
Updated.

2024-07-26 08:55 UTC, LiyangLingIntel commented on third_party/intel/lib/GPUToTritonGEN/GPUToTritonGENPass.cpp
> +#include <optional>
Removed.

2024-07-26 08:57 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    // ShapedType dstAttrType = dstElementsAttr.getType();
This change is based on the comment here https://github.com/intel/intel-xpu-backend-for-triton/pull/1574#discussion_r1684076831

2024-07-26 08:57 UTC, LiyangLingIntel commented on third_party/intel/backend/compiler.py
> +    def make_llir(src, metadata, options, properties):
Removed.

2024-07-26 08:59 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonGPUToLLVM.cpp
> +      mod->setAttr("triton_gpu.shared", builder.getI32IntegerAttr(0));
Done.

2024-07-26 09:00 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +// FIXME: remove this when upstream ConstantOpLowering has such lowering
@Dewei-Wang-sh Do we have any plan to upstream the custom Arith Op lowering?

2024-07-26 09:01 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    // arith.constant should only have vector or tenor types.
This change is based on the comment here https://github.com/intel/intel-xpu-backend-for-triton/pull/1574#discussion_r1684076831

2024-07-26 09:01 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    // ShapedType dstAttrType = dstElementsAttr.getType();
Done.

2024-07-26 09:02 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        VectorType::get(vecType.getNumElements(), vecType.getElementType());
Updated.

2024-07-26 09:55 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +// FIXME: remove this when upstream ConstantOpLowering has such lowering
Upstream already supports vector constants lowering, that's why I'm surprised we need that: https://github.com/intel/llvm/blob/847f4ddb6c3e1697248b6442775513acbd55b7ac/mlir/test/Conversion/ArithToLLVM/arith-to-llvm.mlir#L375

Regarding the tensor lowering, there's no `tensor -> llvm` conversion because tensors are supposed to be converted before the LLVM conversion. Different projects may represent tensors in a different way anyway and may not play well with each other.

2024-07-26 09:56 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +class ArithDivFOpLowering
I'd say we don't need this as IGC should be handling it.

2024-07-29 06:46 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +class ArithDivFOpLowering
the problem is that current IGC can not handle it.

2024-07-29 08:05 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +// FIXME: remove this when upstream ConstantOpLowering has such lowering
yes, we need tensor -> llvm, so keep it here for now.

2024-07-29 08:09 UTC, Dewei-Wang-sh commented
LGTM

2024-07-29 21:22 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    if (!isa<VectorType, RankedTensorType>(srcType))
@LiyangLingIntel please check if you are ok with the change in https://github.com/intel/intel-xpu-backend-for-triton/pull/1574/commits/163dc38bb6de0a2527b9f86a7cc2394763e4fd52.

2024-07-29 21:22 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +/// proper lowering stratefy for these ops.
done.

2024-07-30 00:49 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +class ArithConstantOpLowering
Can we have a test case to prevent regression of this lowering?
There are no failures from removing this pattern.

2024-07-30 03:05 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +class ArithConstantOpLowering
I'd prefer using complete Flash Attention case to track the performance change after these productization PRs are merged.
These ops are too small, I'm concerned that the performance data will fluctuate too much to measure perf improvement.
I can add some lit tests for these custom Arith ops lowering to verify the functionality.

2024-07-30 03:06 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +class ArithConstantOpLowering
I agree functional testing is enough.

2024-07-30 06:30 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      for (auto i = 0; i < num; i++) {
Done.

2024-07-30 06:30 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        // vnni = false;
Done.

2024-07-30 06:30 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        transpose ? ptrOp.getStrides()[1] : ptrOp.getStrides()[0], true);
Done.

2024-07-30 06:31 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    if (!isa<VectorType, RankedTensorType>(srcType))
LGTM. Thanks for helping with these changes.

2024-07-30 06:41 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        transpose ? ptrOp.getStrides()[1] : ptrOp.getStrides()[0], true);
Actually I think we should be careful in `return failure()` unless we are sure those patterns will be well-handled in the following passes. Otherwise, we may get unexpected error message, it's not good for addressing root cause.
So, in developing stage, I would prefer using `assert` other than `return failure()` for unsupported cases.
What do you think?

2024-07-30 16:21 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      for (auto i = 0; i < num; i++) {
forget to push the change?

2024-07-30 19:52 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    rewriter.replaceOp(op, adaptor.getSrc());
They are not the same, e.g.,`%1 = tt.expand_dims %0 {axis = 1 : i32} : tensor<16xf32, #triton_gpu.slice<{dim = 1, parent = #warp}>> -> tensor<16x1xf32, #warp>`

2024-07-31 02:19 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      for (auto i = 0; i < num; i++) {
> forget to push the change?

This change looks missed in a rebase. Thanks for the update!

2024-07-31 02:39 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +class ArithDivFOpLowering
Measured up to 4% improvement. Created IGC ticket.

2024-07-31 10:42 UTC, victor-eds reviewed
LGTM but some comments

2024-07-31 10:42 UTC, victor-eds commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = builtin.unrealized_conversion_cast %[[VAL_0]] : vector<8xf32> to tensor<8x16xf32>
```suggestion
```
Not needed

2024-07-31 10:42 UTC, victor-eds commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = builtin.unrealized_conversion_cast %[[VAL_0]] : vector<8xf32> to tensor<8x16xf32>
```suggestion
```
Not needed

2024-07-31 10:42 UTC, victor-eds commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// COM: Checks the correct lowering of triton ops, includeing broadcast, splat, expand_dims, addptr.
```suggestion
// COM: Checks the correct lowering of triton ops, including broadcast, splat, expand_dims, addptr.
```

2024-07-31 10:42 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +      return failure();
```suggestion
    auto dstElementsAttr = dyn_cast<DenseElementsAttr>(op.getValue());
    if (!dstElementsAttr || !dstElementsAttr.isSplat())
      return failure();
```
This will only work if the constant is a splat, e.g., it won't work for:

```
%0 = arith.constant dense[0, 1, 2, 3, ...] : tensor<128xi32>
```

2024-07-31 10:42 UTC, victor-eds commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = builtin.unrealized_conversion_cast %[[VAL_0]] : !llvm.ptr<1> to !tt.ptr<f16>
```suggestion
```

2024-07-31 10:42 UTC, victor-eds commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = builtin.unrealized_conversion_cast %[[VAL_0]] : vector<8xf32> to tensor<8x16xf32>
```suggestion
```

2024-07-31 10:42 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +           "only support 2d load/store/prefetch for now");
Should we return `failure()` instead of asserting here?

2024-07-31 10:42 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +               "only support 16-bit element type for now");
Can we return `failure()` here instead?

2024-07-31 10:42 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +           "Reduce size should be split into subgroups");
Can we return failure?

2024-07-31 12:27 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    rewriter.replaceOp(op, adaptor.getSrc());
`adaptor.getSrc().getType()` is the input `value` type of `expand_dim` op after conversion to LLVM dialect, `op.getType()` is the type of `tt.expand_dim` op result. I don't think they should be same here.
Basically, `expand_dim` op do not have real data movement, so we use its `src` after conversion to replace itself for simplicity. 
@Dewei-Wang-sh Please correct me if I explain it incorrectly.

2024-07-31 12:51 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +           "only support 2d load/store/prefetch for now");
Same to comment https://github.com/intel/intel-xpu-backend-for-triton/pull/1574#discussion_r1696394437
Can you explain why return `failure()` is better than `assert` here? 

In my opinion, for the cases we do not supported temporarily, using assertion will give us error message exactly when the those cases. Otherwise, it's very easy to get unexpected error report when those unexpected patterns flow into the following passes. It's not good for trouble shooting.

2024-07-31 13:35 UTC, LiyangLingIntel commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = builtin.unrealized_conversion_cast %[[VAL_0]] : vector<8xf32> to tensor<8x16xf32>
Done.

2024-07-31 13:35 UTC, LiyangLingIntel commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// COM: Checks the correct lowering of triton ops, includeing broadcast, splat, expand_dims, addptr.
Updated.

2024-07-31 13:35 UTC, LiyangLingIntel commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = builtin.unrealized_conversion_cast %[[VAL_0]] : vector<8xf32> to tensor<8x16xf32>
Updated.

2024-07-31 13:35 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +      return failure();
Updated.

2024-07-31 13:36 UTC, LiyangLingIntel commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = builtin.unrealized_conversion_cast %[[VAL_0]] : !llvm.ptr<1> to !tt.ptr<f16>
Updated.

2024-07-31 13:36 UTC, LiyangLingIntel commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = builtin.unrealized_conversion_cast %[[VAL_0]] : vector<8xf32> to tensor<8x16xf32>
Updated.

2024-07-31 13:36 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +               "only support 16-bit element type for now");
Same to above.

2024-07-31 13:40 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +           "Reduce size should be split into subgroups");
I agree with that for the case not considered in the pass, we can return failure to exit the pass.

2024-07-31 13:47 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +           "Reduce size should be split into subgroups");
no, I would suggest keep assert as possible,  assertion is very helpful when debug.
this time, it's ok.  please leave the assertion I wrote as is.

2024-07-31 14:06 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    Value surfaceP = calculateSurface(ptrOp.getShape()[transpose], true);
is it intentional to change from getStrides to getShape?

2024-07-31 14:20 UTC, whitneywhtsang approved these changes

2024-07-31 16:05 UTC, FMarno commented on third_party/intel/backend/compiler.py
> +        metadata["shared"] = src.get_int_attr("triton_gpu.shared") if src.get_int_attr("triton_gpu.shared") else 0
```suggestion
        metadata["shared"] = src.get_int_attr("triton_gpu.shared") or 0
```
I'm not a python expert but I think this works. https://realpython.com/python-or-operator/#using-or-with-common-objects

2024-07-31 16:28 UTC, LiyangLingIntel commented on third_party/intel/backend/compiler.py
> +        metadata["shared"] = src.get_int_attr("triton_gpu.shared") if src.get_int_attr("triton_gpu.shared") else 0
Updated.
Thanks, I learned a new magical python expression!

2024-07-31 16:47 UTC, etiotto commented on third_party/intel/backend/compiler.py
> +        metadata["shared"] = src.get_int_attr("triton_gpu.shared") if src.get_int_attr("triton_gpu.shared") else 0
This change isn't required. I see that, with: 
``` 
  metadata["shared"] = src.get_int_attr("triton_gpu.shared")
```
The metadata for  `triton_gpu.shared`  is initialized to zero already:
```
metadata:  {'hash': '7e7ae8580ebc6641f54cc506dc79237102351e5c8f2f35b03de0c48b8e961c80', 'target': GPUTarget(backend='xpu', arch={'dev_type': 'gpu', 'device_arch': 23, 'driver_version': '1.3.29735', 'gpu_eu_count': 448, 'gpu_subslice_count': 56, 'has_fp64': True, 'max_compute_units': 448, 'max_num_sub_groups': 64, 'max_work_group_size': 1024, 'name': 'Intel(R) Data Center GPU Max 1100', 'platform_name': 'Intel(R) Level-Zero', 'sub_group_sizes': [16, 32], 'support_cl_bf16_conversion': True, 'support_cl_sg_2d_block_io': True, 'support_cl_sg_matmul_acc': True, 'support_cl_sg_matmul_acc_tf32': False, 'total_memory': 51539607552, 'vendor': 'Intel(R) Corporation', 'version': '1.3'}, warp_size=32), 'num_warps': 4, 'num_ctas': 1, 'num_stages': 2, 'cluster_dims': (1, 1, 1), 'threads_per_warp': 32, 'optimize_epilogue': False, 'enable_fp_fusion': True, 'default_dot_input_precision': 'tf32', 'allowed_dot_input_precisions': ('tf32', 'tf32x3', 'ieee'), 'allow_fp8e4nv': True, 'allow_fp8e4b15': True, 'grf_mode': ('small', 'large', 'auto', 'default'), 'max_num_imprecise_acc_default': 0, 'extern_libs': (('libdevice', '/home/jovyan/intel-xpu-backend-for-triton/python/triton/backends/intel/lib/libsycl-spir64-unknown-unknown.bc'),), 'debug': None, 'backend_name': 'intel', 'shared': 0}
tensor([1.3713, 1.3076, 0.4940,  ..., 0.6724, 1.2141, 0.9733])
tensor([1.3713, 1.3076, 0.4940,  ..., 0.6724, 1.2141, 0.9733])
The maximum difference between torch and triton is 0.0
...
```

2024-07-31 17:02 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +  patterns.add<AddPtrOpConversion>(typeConverter, benefit);
kudos for using alphabetical order here !

2024-07-31 17:02 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +           "Reduce size should be split into subgroups");
I am ok with the assert

2024-07-31 17:02 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +           "only support 2d load/store/prefetch for now");
I am ok with the assert

2024-07-31 17:13 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    auto vecType = cast<VectorType>(dstType);
The cast is unsafe, should modify the check at line 33 to check for this.,

2024-07-31 17:13 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    rewriter.replaceOp(op, newOp);
Can use `replaceOpWithNewOp` here.

2024-07-31 17:30 UTC, etiotto commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:   llvm.func spir_funccc @_Z32sub_group_non_uniform_reduce_maxf(f32) -> f32
[nit]: The indentation of the CHECKS is not consistent with the style used by the test cases already in this file.

2024-07-31 17:30 UTC, etiotto commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:   llvm.func spir_funccc @_Z32sub_group_non_uniform_reduce_addf(f32) -> f32
These should be CHECK-DAG

2024-07-31 17:30 UTC, etiotto commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = llvm.mlir.constant(0 : i32) : i32
Existing tests use a different style to match, example: 

```
// CHECK: [[VAL_1:%.*]] = llvm.mlir.constant(0 : i32) : i32
```
Let's be consistent.

2024-07-31 17:30 UTC, etiotto commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:   llvm.func spir_funccc @_Z32sub_group_non_uniform_reduce_addf(f32) -> f32
done

2024-07-31 17:30 UTC, etiotto commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:   llvm.func spir_funccc @_Z32sub_group_non_uniform_reduce_maxf(f32) -> f32
fixed

2024-07-31 17:30 UTC, etiotto commented on test/Conversion/intel/tritongpu_to_llvm_intel_advanced_path.mlir
> +// CHECK:           %[[VAL_1:.*]] = llvm.mlir.constant(0 : i32) : i32
done

2024-07-31 17:30 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    rewriter.replaceOp(op, newOp);
done

2024-07-31 17:31 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    auto vecType = cast<VectorType>(dstType);
fixed

2024-07-31 17:31 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    if (!isa<RankedTensorType>(srcType))
done

2024-07-31 17:38 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    if (!dstType || !dyn_cast_or_null<VectorType>(dstType))
```suggestion
    if (!dyn_cast_or_null<VectorType>(dstType))
```

2024-07-31 17:38 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    if (!dstType || !dyn_cast_or_null<VectorType>(dstType))
```suggestion
    if (!dyn_cast_or_null<VectorType>(dstType))
```

2024-07-31 17:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    if (!dstType || !dyn_cast_or_null<VectorType>(dstType))
ok will change

2024-07-31 17:51 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +namespace tt = mlir::triton;
done

2024-07-31 17:51 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    if (!dstType || !dyn_cast_or_null<VectorType>(dstType))
done

2024-07-31 17:51 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/ArithOpsToLLVM.cpp
> +    if (!dstType || !dyn_cast_or_null<VectorType>(dstType))
done

2024-07-31 18:24 UTC, merged

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    };
Drop the semicolon here.

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    };
done

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      result = rewriter.create<LLVM::ExtractElementOp>(loc, base, idxVal);
Use the `extract_element` macro

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        offsetX = rewriter.create<LLVM::LShrOp>(loc, offsetY, i32_val(1));
use the `lshr` macro

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        undef = rewriter.create<LLVM::InsertElementOp>(
use the `insert_element` macro

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        undef = rewriter.create<LLVM::InsertElementOp>(
done

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +        offsetX = rewriter.create<LLVM::LShrOp>(loc, offsetY, i32_val(1));
done

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      for (auto i = 0; i < num; ++i) {
auto -> int

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      for (auto i = 0; i < num; ++i) {
done

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    int subgroupSize =
Use:
```
 int subgroupSize = triton::gpu::TritonGPUDialect::getThreadsPerWarp(mod);

2024-07-31 18:40 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +    int subgroupSize =
done

2024-07-31 18:41 UTC, etiotto commented
The PR should not have been merged because it has oustanding comments and questions.

2024-08-01 01:42 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUToLLVM/TypeConverter.cpp
> +      return mlir::VectorType::get(num, elmTy);
maybe the later pass can better handle scalar type, but I'm not quite sure as this is added months ago.