Minor fix to GEMM benchmark kernel performance regression
intel/intel-xpu-backend-for-triton pull request #1634
Opened 2024-07-16 07:41 UTC by LiyangLingIntel

After comparing the source code and code generation between POC branch and default branch.
There is no big gap in assemble code generation. The main diff is the input data type and data distribution.

On POC branch, to align with XeTLA, we used bfloat16 as input dtype and uniform distribution on the interval [0,1) to generate random data (`torch.rand`). 
This pull request changes those back as POC branch.

With this change, the average TFlops for 4k Gemm increase from 234 to 279, tested on IDC Max 1550.

2024-07-16 07:49 UTC, LiyangLingIntel commented
There is no big problem with the regression. Please help decide whether we should use the inputs as XeTLA or the inputs as Triton tutorial cases.

2024-07-16 08:27 UTC, Dewei-Wang-sh approved these changes
lgtm

2024-07-16 08:40 UTC, ESI-SYD approved these changes

2024-07-16 08:40 UTC, ESI-SYD commented on benchmarks/xetla_benchmark/gemm_benchmark.py
>          d = torch.empty((M, N), device='xpu', dtype=torch.float16)
```suggestion
        c = torch.empty((M, N), device='xpu', dtype=torch.bfloat16)
        d = torch.empty((M, N), device='xpu', dtype=torch.bfloat16)
```

2024-07-16 08:51 UTC, Dewei-Wang-sh approved these changes
lgtm

2024-07-16 13:35 UTC, etiotto commented on third_party/intel/include/Dialect/TritonIntelGPU/IR/TritonIntelGPUOps.td
> +def TTIG_PrefetchOp : TTIG_Op<"prefetch", [MemoryEffects<[MemWrite, MemRead]>]> {
the prefetch operation only reads memory.

2024-07-16 14:29 UTC, etiotto reviewed
The Prefetch operation  reads from global memory but doesn't write to it. It should only have the MemRead memory effect applied to it.

2024-07-16 17:15 UTC, whitneywhtsang commented
> There is no big problem with the regression. Please help decide whether we should use the inputs as XeTLA or the inputs as Triton tutorial cases.

Let's use the inputs as XeTLA, as the good performance is reported before.

> [1192d9f](https://github.com/intel/intel-xpu-backend-for-triton/commit/1192d9fe59c89be00d1c141e21faba76d879458d) This change would be necessary if we want to go in GenISA, or prefetch instruction would be eliminated.

As we plan to remove GenISA usage, and we don't use GenISA by default, I think we can drop 1192d9fe59c89be00d1c141e21faba76d879458d.

2024-07-16 19:31 UTC, etiotto reviewed
Address outstanding review comments about memory semantics for prefetch operation (only Read needed).

2024-07-16 21:25 UTC, etiotto requested changes

2024-07-16 21:25 UTC, etiotto commented on third_party/intel/include/Dialect/TritonIntelGPU/IR/TritonIntelGPUOps.td
> +def TTIG_PrefetchOp : TTIG_Op<"prefetch", [MemoryEffects<[MemWrite, MemRead]>]> {
Or... remove this change from this PR completely. The benchamrk change is the one that is required to fix the performance difference right ?

2024-07-17 01:07 UTC, Dewei-Wang-sh commented on third_party/intel/include/Dialect/TritonIntelGPU/IR/TritonIntelGPUOps.td
> +def TTIG_PrefetchOp : TTIG_Op<"prefetch", [MemoryEffects<[MemWrite, MemRead]>]> {
[etiotto](https://github.com/etiotto) [on Mar 26](https://github.com/intel/intel-xpu-backend-for-triton/pull/678#discussion_r1538106889)
I do not think the operation has any write memory effects.

Member
Author
@[Dewei-Wang-sh](https://github.com/Dewei-Wang-sh) Dewei-Wang-sh [on Mar 26](https://github.com/intel/intel-xpu-backend-for-triton/pull/678#discussion_r1538491873) • 
the prefetch write L1/L3 cache.
if we make it only memread, meantime this operation has no result
later canonicalization would delete this operation as it has no side-effect.

2024-07-17 01:11 UTC, Dewei-Wang-sh commented
> > [1192d9f](https://github.com/intel/intel-xpu-backend-for-triton/commit/1192d9fe59c89be00d1c141e21faba76d879458d) This change would be necessary if we want to go in GenISA, or prefetch instruction would be eliminated.
> 
> As we plan to remove GenISA usage, and we don't use GenISA by default, I think we can drop [1192d9f](https://github.com/intel/intel-xpu-backend-for-triton/commit/1192d9fe59c89be00d1c141e21faba76d879458d).

no matter we use ocl or genisa, the prefetch operation's attribute should be the same.
stated above, this change. is nessary.

2024-07-17 06:00 UTC, LiyangLingIntel commented
As we discussed above, I have reverted the change to prefech Op. It looks need more discussion and I'll look deeper into it,  I can submit another pull request for this issue then.
For this PR, we can make it simple just for adjusting the gemm kernel inputs.

2024-07-17 13:17 UTC, whitneywhtsang approved these changes

2024-07-17 13:29 UTC, etiotto commented
> As we discussed above, I have reverted the change to prefech Op. It looks need more discussion and I'll look deeper into it, I can submit another PR for this issue then if needed.
> For this PR, we can make it simple just for adjusting the gemm kernel inputs.

Good. Like I suspected the change involving the attributes is not strictly necessary for fixing the performance issue.

2024-07-17 13:33 UTC, merged