Support to build the Triton XPU backend as a third-party plug-in to Triton
intel/intel-xpu-backend-for-triton pull request #180
Opened 2024-01-02 06:53 UTC by chengjunlu

Support to build the Triton XPU backend as a third-party plug-in to Triton.

We are looking forward the public Triton supporting dispatch the compilation stages to the third-party plug-in.

Right now the build scripts supports the building XPU backend as a third-party plug-in. But the public Triton could not dispatch the complier stage to XPU.

The forked Triton supports that: https://github.com/chengjunlu/triton/tree/chengjun/enhance_front_end.

We are talking to Phil about it.

2024-01-03 15:53 UTC, etiotto commented
Hi @chengjunlu I do not think I fully understand what you wrote in the description of the PR. This is my interpretation:
  - public Triton has a mechanism to build plugins backends from different vendors
  - plugins aren't fully functional (not exactly clear to me the reason)

So the question is what this PR allows ? What is the functionality that this PR adds ? Can you please clarify in the description ?

2024-01-03 16:16 UTC, etiotto requested changes
Looks to me that this PR does more that the minimum necessary to make the project a Triton plugin. Can you post a minimal PR to make it a plugin and address everything else in separate self contained pull requests please ?

2024-01-03 16:16 UTC, etiotto commented on lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
> -      Value warpSize = i32_val(32);
I'd like to keep the code as close as possible to the upstream code to reduce merge conflicts. Can we do this change upstream ? 

If we want to do this change downstream then we should split it into a different PR to (a) keep unrelated changes separate and (b) we can mark the PR as something we need to upstream.

2024-01-03 16:16 UTC, etiotto commented on lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
> -    Value warpSize = i32_val(32);
Same comment as at line 588.

2024-01-03 16:16 UTC, etiotto commented on cmake/FindSPIRVToLLVMTranslator.cmake
> +    message(STATUS "SPIR-LLVM location is not specified. Will try to download
nit: SPIR-LLVM  -> SPIRV-LLVM

2024-01-03 16:16 UTC, etiotto commented on cmake/FindSPIRVToLLVMTranslator.cmake
> +#    set(SPIRV_HEADERS_SKIP_EXAMPLES ON)
Remove commented out code.

2024-01-03 16:16 UTC, etiotto commented on cmake/FindSPIRVToLLVMTranslator.cmake
> +# - Try to find SPIRV-LLVM-Translator
This change isn't necessary to create a plugin. Can you split it into a different PR?

2024-01-03 16:16 UTC, etiotto commented on lib/Target/SPIRV/CMakeLists.txt
> +# SPIRV-LLVM Translator is required.
Are any of these changes required to make the code a Triton plugin ? Let's have a minimal PR to do just that, and separate everything else into their own self contained pull requests please.

2024-01-04 01:01 UTC, chengjunlu commented on lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
> -      Value warpSize = i32_val(32);
The 32 warp size is preferred by the NV and it is in hardware. 
But for the Intel GPU, we have a software vectorization to convert the SIMT kernel to SIMD. We can support different warp size from 8/16/32. 
In the DPAS PoC, I do the experimental found only the SIMD 16 work properly for both the ATSM and PVC.

AMD keep an copy of the code.
https://github.com/ROCmSoftwarePlatform/triton/blob/d0ad70d55df3ebe11cc80bbb364a91551e6b6248/lib/Conversion/TritonGPUROCMToLLVM/TritonGPUToLLVMBase.h#L485

Maybe we can PR the changes to public Triton?

2024-01-04 01:04 UTC, chengjunlu commented on lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
> -      Value warpSize = i32_val(32);
In the Triton 3p python extensions, I have already use the warp size 16 as the default configurations.

``` Python
class XPUOptions:
    num_warps: int = 4
    num_ctas: int = 1
    num_stages: int = 3
    # cluster_dims: tuple = (1, 1, 1)
    spirv_version: int = None
    dev_type: str = 'GPU'
    dev_id: int = None
    threads_per_warp: int = 16
```

2024-01-04 01:21 UTC, chengjunlu commented
> Hi @chengjunlu I do not think I fully understand what you wrote in the description of the PR. This is my interpretation:
> 
> * public Triton has a mechanism to build plugins backends from different vendors
> * plugins aren't fully functional (not exactly clear to me the reason)
> 
> So the question is what this PR allows ? What is the functionality that this PR adds ? Can you please clarify in the description ?
> 
> Also, the PR is lacking a tests to exercise the new functionality. How do we test this PR ?

1. This PR enables the build the XPU llvm-target as a third party plug-in with the Triton mechanism.
2. The Triton public main branch has issue to run the code in third party plug-in. It is expected to be fixed soon.
3. I will add a CI test script to build the XPU backend as a 3p plug-in

2024-01-04 14:23 UTC, etiotto commented on lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
> -      Value warpSize = i32_val(32);
> The 32 warp size is preferred by the NV and it is in hardware. But for the Intel GPU, we have a software vectorization to convert the SIMT kernel to SIMD. We can support different warp size from 8/16/32. In the DPAS PoC, I found only the SIMD 16 work properly for both the ATSM and PVC.
> 
> AMD keeps an copy of the code. https://github.com/ROCmSoftwarePlatform/triton/blob/d0ad70d55df3ebe11cc80bbb364a91551e6b6248/lib/Conversion/TritonGPUROCMToLLVM/TritonGPUToLLVMBase.h#L485
> 
> Maybe we can PR the changes to public Triton?

Yes I am aware that different vendors have a different preferred warp size. So this change is good in my opinion. The point I was making here is that this change isn't really germane to this PR. We can do it in a separate pull requests, and it would be best to make the change upstream.

2024-01-05 01:57 UTC, chengjunlu commented on lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
> -      Value warpSize = i32_val(32);
I will create a new PR for the warp size.
To track the changes we want to upstream, I will add a [UPSTREAM] prefix to the commit message. Is that Ok?

2024-01-05 14:30 UTC, etiotto commented on lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
> -      Value warpSize = i32_val(32);
To track the changes we want to upstream, I will add a [UPSTREAM] prefix to the commit message. Is that Ok?

> Yes, good idea!

2024-01-08 13:55 UTC, whitneywhtsang commented on CMakeLists.txt
> +# Use the PYTHON_THIRD_PARTY_PATH var to detect whehter XPU backend is built as a plug-in
```suggestion
# Use the PYTHON_THIRD_PARTY_PATH var to detect whether XPU backend is built as a plug-in
```

2024-01-08 13:55 UTC, whitneywhtsang commented on CMakeLists.txt
> +MESSAGE(STATUS "johnlu cmake TRITON_BUILD_PYTHON_MODULE ${TRITON_BUILD_PYTHON_MODULE}")
```suggestion
```

2024-01-22 17:08 UTC, pengtu approved these changes
Looks good to me.  Let's expediate it to the branch and refine it later if needed.

2024-01-22 21:09 UTC, etiotto commented on third_party/intel_xpu_backend/CMakeLists.txt
> +add_triton_plugin(TritonXPU ${CMAKE_CURRENT_SOURCE_DIR}/triton_xpu.cc)
Upstream they names the third_party vendor directories simply nvidia/amd:
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/56368199/35d58dc2-8cf1-4688-8d20-fd2c7c97e72a)

We should name our directory simply 'intel'

2024-01-22 21:09 UTC, etiotto commented on third_party/intel_xpu_backend/triton_xpu.cc
> +#if 0
Remove dead code please

2024-01-22 21:09 UTC, etiotto commented on third_party/intel_xpu_backend/backend/compiler.py.in
> +        metadata["cluster_dims"] = (1, 1, 1)
why is this hardcoded ?

2024-01-22 21:09 UTC, etiotto commented on third_party/intel_xpu_backend/backend/compiler.py.in
> -        cluster_info = xpu.ClusterInfo()
Can you explain why we do not need this info ?

2024-01-23 05:30 UTC, chengjunlu commented on third_party/intel_xpu_backend/backend/compiler.py.in
> -        cluster_info = xpu.ClusterInfo()
The CTA cluster is only valid for NV H100 GPU for now. And the FS2 may support it in the future.
These compilation stages in the XPU backend are only used for the Intel GPU. So we can simply remove the ClusterInfo for simplicity.

2024-01-23 05:32 UTC, chengjunlu commented on third_party/intel_xpu_backend/backend/compiler.py.in
> +        metadata["cluster_dims"] = (1, 1, 1)
The launcher interface requires the `clustder_dims` information to launcher the kernel in jit.py.
We hard code it to 1, 1, 1, just simply bypass these unused dimensions of the hierarchized multi-threads.

2024-01-23 08:00 UTC, chengjunlu commented on CMakeLists.txt
> +# Use the PYTHON_THIRD_PARTY_PATH var to detect whehter XPU backend is built as a plug-in
Code changed.

2024-01-23 08:00 UTC, chengjunlu commented on CMakeLists.txt
> +MESSAGE(STATUS "johnlu cmake TRITON_BUILD_PYTHON_MODULE ${TRITON_BUILD_PYTHON_MODULE}")
Code changed.

2024-01-23 08:01 UTC, chengjunlu commented on python/src/translation.cc
> +  m.def("get_threads_per_warp", [](mlir::ModuleOp mod) {
This translation.cc is out of date.

2024-01-23 08:01 UTC, chengjunlu commented on python/setup.py
> +        ninja_dir = "/home/chengjun/clion-2023.1.3/bin/ninja/linux/x64/ninja"
Remove the personal platform related code.

2024-04-16 13:05 UTC, vlad-penkin commented
@chengjunlu there were no changes in this PR since January. Can we close it?

2024-04-17 00:54 UTC, chengjunlu commented
> @chengjunlu there were no changes in this PR since January. Can we close it?

This issue is originally for upstream the Triton XPU to the third_part submodule to OpenAI Triton.

The status has been changed during the discussion with OpenAI Triton.

So I think we can close this issue as it is not valid for now. We can open a new issue if something changed in future.

2024-04-17 00:54 UTC, closed without merging