Add script to compare CI performance runs
intel/intel-xpu-backend-for-triton pull request #1846
Opened 2024-08-12 08:24 UTC by sommerlukas

Add a script to easily compare two runs of the "E2E performance" CI workflow. 

The script compares the speedup over Pytorch eager yielded by the two different CI runs, prints an evaluation and is also able to visualize the data as a boxplot. 

For more details on the usage of the script, see the accompanying README. 

This script was written and used for #1370 and #1371.

2024-08-12 09:10 UTC, victor-eds approved these changes

2024-08-12 09:17 UTC, FMarno commented on scripts/compare-ci-runs/README.md
> +* `-p`/`--path`: Per default, the script would store all intermediate data and
```suggestion
* `-p`/`--path`: The output path, `DIR`. Per default, the script would store all intermediate data and
```
This description takes a while to get to the point.

2024-08-12 09:17 UTC, FMarno commented on scripts/compare-ci-runs/README.md
> +* `--no-plot`: Per default, the script will also visualize the output in a plot.
```suggestion
* `--no-plot`: Disable plotting. Per default, the script will also visualize the output in a plot.
```

2024-08-12 09:17 UTC, FMarno commented on scripts/compare-ci-runs/README.md
> +The local mode can be used by adding the `-e`/`--eval-only` option.
```suggestion
The evaluation mode can be used by adding the `-e`/`--eval-only` option.
```

2024-08-12 09:17 UTC, FMarno commented on scripts/compare-ci-runs/compare-runs.py
> +    if args.local:
what about eval?

2024-08-12 10:57 UTC, sommerlukas commented on scripts/compare-ci-runs/compare-runs.py
> +    if args.local:
In evaluation mode, this function is never called.

2024-08-12 11:49 UTC, FMarno approved these changes

2024-08-12 13:00 UTC, vlad-penkin commented
@sommerlukas please add requirements.txt for all dependencies which are needed to run the script.

2024-08-12 13:03 UTC, vlad-penkin requested changes
@sommerlukas few notes 
- please add requirements.txt for dependencies needed to run the script.
- there is no need to explicitly mention `numpy` , `pandas` depends on it

2024-08-12 14:21 UTC, sommerlukas commented
> @sommerlukas few notes
> 
>     * please add requirements.txt for dependencies needed to run the script.
> 
>     * there is no need to explicitly mention `numpy` , `pandas` depends on it

Thanks for the feedback @vlad-penkin!

I've added a `requirements.txt`. I've omitted the version information, as I don't believe that the script relies on version-specific features. Let me know if you prefer to include the version information in the `requirements.txt`.

2024-08-12 19:20 UTC, pbchekin reviewed
Please add docstrings to the functions and specify types for the arguments and results.

Also, instead of mixing `os.path` and `pathlib` use one (I recommend `pathlib` since it is newer).

2024-08-12 19:20 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +    ret = subprocess.run(
Nit: is it more reasonable to use `subprocess.check_call` (https://docs.python.org/3/library/subprocess.html#subprocess.check_call) in this context?. It throws an exception if process exit code is not 0 and prints process output to stdout/stderr.

2024-08-12 19:20 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +        ["gh", "run", "download", "-R", "intel/intel-xpu-backend-for-triton", "-D", f"{name}", f"{run}"],
```suggestion
        ["gh", "run", "download", "-R", "intel/intel-xpu-backend-for-triton", "-D", name, run],
```

2024-08-12 19:20 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +    path = Path(file)
Nit:
```suggestion
    path = Path(file).absolute
```

2024-08-12 19:20 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +                df = parse_data(config, df, file)
```suggestion
    for file in Path(directory).glob("**/*performance.csv"):
        df = parse_data(config, df, file)
```

2024-08-12 19:20 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +          f"relative difference < 0.0 means {denominator} performs better")
```suggestion
          f" relative difference > 0.0 means {numerator} performs better,"
          f" relative difference < 0.0 means {denominator} performs better")
```

2024-08-12 19:40 UTC, vlad-penkin commented on scripts/compare-ci-runs/compare-runs.py
> +    # Filter out NaN and zero values
I suggest to print the rows which are skipped.

2024-08-12 19:41 UTC, vlad-penkin commented on scripts/compare-ci-runs/compare-runs.py
> +        df = df.merge(previous, how="left", on=["suite", "datatype", "mode", "name", "dev"])
Do we want to show / print rows which are present in current results only?

2024-08-13 08:40 UTC, sommerlukas commented on scripts/compare-ci-runs/compare-runs.py
> +    # Filter out NaN and zero values
Added a print for the `NaN` rows.

2024-08-13 08:41 UTC, sommerlukas commented on scripts/compare-ci-runs/compare-runs.py
> +        df = df.merge(previous, how="left", on=["suite", "datatype", "mode", "name", "dev"])
I switched to `outer`, this way configurations only appearing in one of the dataframes will be preserved and a `NaN` value added, which will then be printed by the printout of `NaN` rows.

2024-08-13 08:42 UTC, sommerlukas commented on scripts/compare-ci-runs/compare-runs.py
> +    ret = subprocess.run(
IMHO, the current approach allows us to give the user a bit more information in which step the script failed and the `stdout` and `stderr` are also not polluted with the Python stracktrace.

2024-08-13 14:46 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +    """Retrieve configuration name"""
Nit:
```suggestion
    """Retrieve configuration name."""
```

2024-08-13 14:46 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +    """Download artifacts for given configuration and CI run ID from Github"""
Nit:
```suggestion
    """Download artifacts for given configuration and CI run ID from GitHub."""
```

2024-08-13 14:46 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +def get_raw_data(args: argparse.Namespace) -> tuple[Path, Path]:
```suggestion
def get_raw_data(args: argparse.Namespace) -> tuple[Optional[Path], Optional[Path]]:
```

This will also require
```
from typing import Optional
```

2024-08-13 14:46 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +def parse_directory(config: str, previous: pd.DataFrame, directory: str) -> pd.DataFrame:
```suggestion
def parse_directory(config: str, previous: pd.DataFrame, directory: Path) -> pd.DataFrame:
```

2024-08-13 14:46 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +    if previous is not None:
Is it expected to be in the previous loop? To merge all data frames for all csv files.

2024-08-13 14:46 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +    denomDir = Path(os.getcwd()).joinpath(get_config(args.denominator))
I think `Path()` creates a path relative to the current directory, `os.getcwd()` is not required.
```suggestion
    numDir = Path(get_config(args.numerator))
    denomDir = Path(get_config(args.denominator)).
```

2024-08-13 14:46 UTC, pbchekin commented on scripts/compare-ci-runs/compare-runs.py
> +    cwd = os.getcwd()
Not used

2024-08-14 07:32 UTC, sommerlukas commented on scripts/compare-ci-runs/compare-runs.py
> +    if previous is not None:
No, this is just merging the dataframe collected for one CI run (if we previously already processed one) with the frame from this CI run. 

Collecting the data from the different CSV files of one CI run into a single dataframe happens through `pd.concat(...)` in `parse_data`.

2024-08-14 14:54 UTC, pbchekin approved these changes

2024-08-14 15:52 UTC, whitneywhtsang commented
@vlad-penkin Please take another look.

2024-08-15 13:20 UTC, merged