Feature/intel sycl rt support
intel/intel-xpu-backend-for-triton pull request #1857
Opened 2024-08-12 18:43 UTC by ZzEeKkAa

Add support to https://pypi.org/project/intel-sycl-rt/ wheel package that is described #1717

2024-08-12 19:31 UTC, vlad-penkin requested changes

2024-08-12 19:31 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +else:
Please add sycl runtime version check `>= 2025.0.0`

2024-08-12 19:31 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +else:
Shall we raise the exception if sycl runtime libraries and headers file folder location can't be identified at all?

2024-08-12 19:46 UTC, pbchekin commented on python/triton/runtime/build.py
> +            cxx = icpx if icpx is not None else clangpp if clangpp else gxx
What about
```suggestion
            cxx = icpx or clangpp or gxx
```

2024-08-12 19:46 UTC, pbchekin commented on python/triton/runtime/build.py
> +    if os.getenv('VERBOSE') is not None:
What about `TRITON_XPU_VERBOSE` instead of `VERBOSE`?

Also
```suggestion
    if os.getenv('VERBOSE'):
```

2024-08-12 19:46 UTC, pbchekin commented on third_party/intel/backend/driver.py
> +import pkg_resources
`pkg_resources` requires `setuptools` in runtime and this package is currently not in Triton dependencies (it is listed only as a build dependency). From the context I think it is possible to use a built-in `importlib.util` instead of ``pkg_resources.

2024-08-12 19:59 UTC, etiotto commented on python/triton/runtime/build.py
> +            cc_cmd += ["--std=gnu++17"]
Do we really need `--std=gnu++17` or is `--std=c++17` sufficient ?

2024-08-12 20:18 UTC, ZzEeKkAa commented on python/triton/runtime/build.py
> +    if os.getenv('VERBOSE') is not None:
I'm glad with any name. Just `VERBOSE` is used in most build tools to display compile command line

2024-08-12 20:18 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +else:
Won't it be added in `2024.1.4` ?

2024-08-12 20:31 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +else:
I guess it is bad idea for the scenarios when `icpx` compiler is presented. We are adding `-fsycl` option that does all this magic for us.

2024-08-12 20:32 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +else:
However I've added `try-catch` for the case when there is no runtime package.

2024-08-12 20:36 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +import pkg_resources
Importlib won't work, because `intel-sycl-rt` is not a python package, but just a library
```
$ print(importlib.util.find_spec('intel-sycl-rt'))
None
```

2024-08-12 20:39 UTC, ZzEeKkAa commented on python/triton/runtime/build.py
> +            cc_cmd += ["--std=gnu++17"]
I've tested with g++ and clang++ - `c++17` is enough

2024-08-12 20:42 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +else:
Anyway, I guess it won't break compiler if we pass not existing path, but it will increase code complexity. I'm happy to add check if it is necessary.

2024-08-12 20:47 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +else:
> Won't it be added in `2024.1.4` ?

It won't.

2024-08-12 20:51 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +else:
> Anyway, I guess it won't break compiler if we pass not existing path, but it will increase code complexity. I'm happy to add check if it is necessary.

Without this constraint we will increase the likelihood that user will have broken environment without straightforward easy way to diagnose what's wrong.

2024-08-12 21:36 UTC, etiotto commented on python/triton/runtime/build.py
> +            cc_cmd += ["--std=gnu++17"]
Great.

2024-08-12 22:30 UTC, pbchekin commented on third_party/intel/backend/driver.py
> +import pkg_resources
> Importlib won't work, because `intel-sycl-rt` is not a python package, but just a library

I see. In that case please take a look to https://setuptools.pypa.io/en/latest/pkg_resources.html:

> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

2024-08-12 22:52 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +else:
As discuss, it will introduce logic duplication.

2024-08-13 21:16 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +import pkg_resources
I've managed ot make `importlib.metadata` work. Thank you!

2024-08-13 21:17 UTC, ZzEeKkAa commented on python/triton/runtime/build.py
> +    if os.getenv('VERBOSE') is not None:
My concern is that this branch can be used not only with XPU.

2024-08-20 22:24 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +else:
Implemented as discuses: raise exception if sycl library is not found.

2024-08-20 23:15 UTC, pbchekin reviewed
Looks good, small nits only

2024-08-20 23:15 UTC, pbchekin commented on third_party/intel/backend/driver.py
> +        sycl_rt = importlib.metadata.metadata('intel-sycl-rt')
Nit:
```suggestion
        sycl_rt = importlib.metadata.metadata("intel-sycl-rt")
```

2024-08-20 23:15 UTC, pbchekin commented on third_party/intel/backend/driver.py
> +            include_dir += [os.path.abspath(f.locate().parent.parent)]
Method `locate()` returns the absolute path, no need to call `abspath()`
```suggestion
            include_dir += [f.locate().parent.parent.as_posix()]
```

2024-08-20 23:15 UTC, pbchekin commented on third_party/intel/backend/driver.py
> +        if f.name == 'sycl.hpp':
Nit:
```suggestion
        if f.name == "sycl.hpp":
```

2024-08-20 23:15 UTC, pbchekin commented on third_party/intel/backend/driver.py
> +    if tuple(map(eval, sycl_rt.get('version').split('.'))) < (2025, 0, 0):
Nit:
```suggestion
    if tuple(map(eval, sycl_rt.get("version").split("."))) < (2025, 0, 0):
```

2024-08-20 23:15 UTC, pbchekin commented on third_party/intel/backend/driver.py
> +    for f in importlib.metadata.files('intel-sycl-rt'):
Nit:
```suggestion
    for f in importlib.metadata.files("intel-sycl-rt"):
```

2024-08-20 23:15 UTC, pbchekin commented on third_party/intel/backend/driver.py
> +            library_dir += [os.path.abspath(f.locate().parent)]
```suggestion
        if f.name == "libsycl.so":
            library_dir += [f.locate().parent.as_posix()]
```

2024-08-21 02:24 UTC, ZzEeKkAa commented on python/triton/runtime/build.py
> +    if os.getenv('VERBOSE'):
Good to know, thx. Should we add to linter?

2024-08-21 02:27 UTC, pbchekin commented on python/triton/runtime/build.py
> +    if os.getenv('VERBOSE'):
Yep, will do. For some reason there is no Python linter in the upstream project, we will add downstream instead.

2024-08-21 16:48 UTC, vlad-penkin requested changes

2024-08-21 16:48 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +    if tuple(map(eval, sycl_rt.get('version').split('.'))) < (2025, 0, 0):
Please use more reliable and correct  implementation `packaging.Version` class for version string parsing and versions comparisons.  We've used it before in this module.

2024-08-21 17:07 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +            include_dir += [os.path.abspath(f.locate().parent.parent)]
abspath was used to get rid of relative path navigation like this:

```
In [12]: f.locate().parent.parent.as_posix()
Out[12]: '/home/jovyan/Projects/poc-wheel/.venv/lib/python3.9/site-packages/../../../include/sycl'

In [13]: os.path.abspath(f.locate().parent.parent)
Out[13]: '/home/jovyan/Projects/poc-wheel/.venv/include/sycl'
```

2024-08-21 17:09 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +    if tuple(map(eval, sycl_rt.get('version').split('.'))) < (2025, 0, 0):
BTW, it is only being imported here, but actually never used:
https://github.com/triton-lang/triton/blob/b37716642d538da661f42510aa73a4e5395f78c5/third_party/intel/backend/compiler.py#L13

2024-08-21 17:09 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +    if tuple(map(eval, sycl_rt.get('version').split('.'))) < (2025, 0, 0):
@pbchekin could you also add linter for unused imports?

2024-08-21 17:11 UTC, pbchekin commented on third_party/intel/backend/driver.py
> +            include_dir += [os.path.abspath(f.locate().parent.parent)]
What about
```
f.locate().parent.parent.absolute().as_posix()
```

IMHO it's better than mixing `os.path` and `pathlib` in the same expression

2024-08-21 17:12 UTC, ZzEeKkAa commented on python/triton/runtime/build.py
> +    if os.getenv('VERBOSE'):
It may good practice to introduce it to the upstream as well.

2024-08-21 17:14 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +            include_dir += [os.path.abspath(f.locate().parent.parent)]
```
f.locate().parent.parent.absolute().as_posix()
Out[15]: '/home/jovyan/Projects/poc-wheel/.venv/lib/python3.9/site-packages/../../../include/sycl'
```

2024-08-21 17:16 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +            include_dir += [os.path.abspath(f.locate().parent.parent)]
I found. There is a `resolve()` method

2024-08-21 17:22 UTC, pbchekin approved these changes

2024-08-23 00:14 UTC, vlad-penkin requested changes

2024-08-23 00:14 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +    sycl_ver = Version(sycl_rt.get("version"))
```suggestion
    sycl_ver = Version(sycl_rt.get("version", "0.0.0"))
```

2024-08-23 00:14 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
```suggestion
from packaging.specifiers import SpecifierSet

```

2024-08-23 00:14 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +    if sycl_ver.major < 2025:
```suggestion
    if sycl_ver in SpecifierSet("<2025.0.0a1"):
```

2024-08-23 00:14 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +        "or install intel-sycl-rt>=2025.0.0 wheel")
```suggestion
        "or install intel-sycl-rt>=2025.0.0 wheel"
    ) # yapf: disable
```

2024-08-23 15:17 UTC, ZzEeKkAa commented on third_party/intel/backend/driver.py
> +        "or install intel-sycl-rt>=2025.0.0 wheel")
Personally, I would prefer it in a shorter way, so more context is on the single screen. We can set up a design meeting and add this type of things to the linter. Otherwise setting linter exception will be annoying and waist of time.

2024-08-23 15:49 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +        "or install intel-sycl-rt>=2025.0.0 wheel")
It will be a very opinionated discussion 😊

2024-08-23 18:39 UTC, anmyachev commented on third_party/intel/backend/driver.py
> +include_dir, library_dir = find_sycl(include_dir, [])
```suggestion
include_dir, library_dir = find_sycl(include_dir)
```

2024-08-23 18:39 UTC, anmyachev commented on third_party/intel/backend/driver.py
> +def find_sycl(include_dir: list[str], library_dir: list[str]) -> tuple[list[str], list[str]]:
```suggestion
def find_sycl(include_dir: list[str]) -> tuple[list[str], list[str]]:
```

2024-08-23 18:39 UTC, anmyachev commented on third_party/intel/backend/driver.py
> +    """
If you return values, you should not change the implicitly passed values, such side effect is not expected from such a function.

```suggestion
    """
    library_dir = []
    include_dir = include_dir.copy()
```

2024-08-23 18:39 UTC, anmyachev commented on third_party/intel/backend/driver.py
> +      library_dir: list of library directories to pass to compiler.
```suggestion
```

2024-08-23 18:42 UTC, anmyachev commented on third_party/intel/backend/driver.py
> +        return include_dir, library_dir
Why is this branch needed if the next step is to check `ONEAPI_ROOT` environment variable?

2024-08-23 18:48 UTC, anmyachev commented on third_party/intel/backend/driver.py
> +        "or install intel-sycl-rt>=2025.0.0 wheel")
The general practice is to save the long exception message in a variable and then use it when throwing exceptions:

```python
message = "long long message"
# case 1
raise AssertionError(message)
# case 2 similar to case 1
raise AssertionError(message)
```

2024-08-23 20:25 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +        return include_dir, library_dir
`icpx` magically knows where `sycl` runtime binaries and header files are, other compilers don't.

2024-08-23 20:39 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +        return include_dir, library_dir
@ZzEeKkAa let's this assumption explicit and a comment line with the underlying assumption.

2024-08-24 08:51 UTC, vlad-penkin commented on third_party/intel/backend/driver.py
> +    if tuple(map(eval, sycl_rt.get('version').split('.'))) < (2025, 0, 0):
Created
- #2001 

for `pylint` checks.

2024-08-26 15:08 UTC, anmyachev commented on python/triton/runtime/build.py
> +    if os.getenv('VERBOSE'):
https://github.com/intel/intel-xpu-backend-for-triton/issues/2001

2024-08-26 20:21 UTC, vlad-penkin approved these changes
LGTM

2024-08-27 13:27 UTC, merged