Update XeTLA's attn implementation of Triton benchmark
intel/intel-xpu-backend-for-triton pull request #1877
Opened 2024-08-14 09:13 UTC by ESI-SYD

2024-08-15 02:49 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> -          SYCL_PROGRAM_COMPILE_OPTIONS=" -vc-codegen -vc-disable-indvars-opt -doubleGRF -Xfinalizer ' -printregusage -enableBCR -DPASTokenReduction ' " \
I thought you said this is needed for XeTLA, why is it no longer needed?

2024-08-15 02:52 UTC, whitneywhtsang commented on scripts/test-triton.sh
> +  TRITON_INTEL_ADVANCED_PATH=1 \
Can we change the order for the two to match the order for GEMM?

2024-08-15 02:52 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> -          SYCL_PROGRAM_COMPILE_OPTIONS=" -vc-codegen -vc-disable-indvars-opt -doubleGRF -Xfinalizer ' -printregusage -enableBCR -DPASTokenReduction ' " \
oic, as you now set it in benchmarks/xetla_kernel/CMakeLists.txt.

2024-08-15 02:53 UTC, whitneywhtsang commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +        line_vals=['xetla'],
Why are we not running Triton?

2024-08-15 03:09 UTC, ESI-SYD commented on .github/workflows/triton-benchmarks.yml
> -          SYCL_PROGRAM_COMPILE_OPTIONS=" -vc-codegen -vc-disable-indvars-opt -doubleGRF -Xfinalizer ' -printregusage -enableBCR -DPASTokenReduction ' " \
yes

2024-08-15 03:12 UTC, ESI-SYD commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +        line_vals=['xetla'],
For advanced path, I see `LLVM ERROR: TritonGPU module should contain a triton_gpu.num-warps attribute` for `Triton` attn. I think we can add back after attn features productization finished.

2024-08-15 03:13 UTC, ESI-SYD commented on scripts/test-triton.sh
> +  TRITON_INTEL_ADVANCED_PATH=1 \
Sure

2024-08-16 15:36 UTC, etiotto requested changes

2024-08-16 15:36 UTC, etiotto commented on .github/workflows/triton-benchmarks.yml
> +      - name: Run Triton FA kernel benchmark
We need to wait to make FlashAttention run on the llvm-target branch. First we need to complete the POC "productization". Only at that point we should remove this coverage.

2024-08-19 01:41 UTC, ESI-SYD commented on .github/workflows/triton-benchmarks.yml
> +      - name: Run Triton FA kernel benchmark
OK

2024-08-20 19:38 UTC, whitneywhtsang commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +        x_vals=[[4, 48, 1024, 64], [32, 32, 512, 64], [16, 32, 1024, 64], [8, 32, 2048, 64], [4, 32, 4096, 64],
done.

2024-08-20 21:41 UTC, whitneywhtsang approved these changes

2024-08-20 21:43 UTC, whitneywhtsang commented
Added a change to run flash attention with default path first, then we can add advanced path in a separate PR when it is ready.

2024-08-20 21:44 UTC, whitneywhtsang commented
@ESI-SYD Please check if you are ok with https://github.com/intel/intel-xpu-backend-for-triton/pull/1877/commits/984905a97dc537ac7988f5a0c7fbdf83ea85922b.

2024-08-20 22:56 UTC, whitneywhtsang commented
Verified that tolerance needs to be increased for advanced path in PoC branch too. https://github.com/intel/intel-xpu-backend-for-triton/pull/1877/commits/466cb15a3a24f3558db5802eb7b1fe6010ac00e0

2024-08-21 00:46 UTC, chengjunlu approved these changes

2024-08-21 16:16 UTC, etiotto commented on .github/workflows/triton-benchmarks.yml
> +          IGC_VISAOptions=" -TotalGRFNum 256 -enableBCR -nolocalra -printregusage -DPASTokenReduction -enableHalfLSC -abiver 2" \
We have a feature to chose the large GRF mode automatically so can you please remove the -TotalGRFNum option here ?  

We can also have 2 tests (one with extra IGC options and one without any extra options). That way we can track performance out-of-box vs with special IGC flags.

2024-08-21 16:16 UTC, etiotto commented on .github/workflows/triton-benchmarks.yml
> +          IGC_DisableLoopUnroll=1 \
Does this option matters in the advanced path ?  Can we remove it ?
I think is important to clean up any IGC options that aren't absolutely needed to get performance.

2024-08-21 16:16 UTC, etiotto commented on scripts/test-triton.sh
>    IGC_VISAOptions=" -TotalGRFNum 256 -enableBCR -nolocalra -printregusage -DPASTokenReduction -enableHalfLSC -abiver 2" \
`-TotalGRFNum 256`  is not required for Triton, remove. 
 
 Are any of the other flags required ?

2024-08-21 16:16 UTC, etiotto commented on scripts/test-triton.sh
>    IGC_VISAOptions=" -TotalGRFNum 256 -enableBCR -nolocalra -printregusage -DPASTokenReduction -enableHalfLSC -abiver 2" \
Remove `-TotalGRFNum 256`

2024-08-21 16:16 UTC, etiotto commented on scripts/test-triton.sh
> +  IGC_VISAOptions=" -TotalGRFNum 256 -enableBCR -nolocalra -printregusage -DPASTokenReduction -enableHalfLSC" \
Remove ` -TotalGRFNum 256`

2024-08-21 16:34 UTC, whitneywhtsang commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +        line_vals=['xetla'],
Addressed in https://github.com/intel/intel-xpu-backend-for-triton/pull/1877/commits/984905a97dc537ac7988f5a0c7fbdf83ea85922b.

2024-08-21 16:34 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> +      - name: Run Triton FA kernel benchmark
Addressed in https://github.com/intel/intel-xpu-backend-for-triton/pull/1877/commits/984905a97dc537ac7988f5a0c7fbdf83ea85922b.

2024-08-21 16:45 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> +          IGC_VISAOptions=" -TotalGRFNum 256 -enableBCR -nolocalra -printregusage -DPASTokenReduction -enableHalfLSC -abiver 2" \
Addressed in https://github.com/intel/intel-xpu-backend-for-triton/pull/1970 and https://github.com/intel/intel-xpu-backend-for-triton/pull/1971.

2024-08-21 16:54 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> +          IGC_DisableLoopUnroll=1 \
Created issue https://github.com/intel/intel-xpu-backend-for-triton/issues/1972.

2024-08-21 16:54 UTC, whitneywhtsang commented on scripts/test-triton.sh
>    IGC_VISAOptions=" -TotalGRFNum 256 -enableBCR -nolocalra -printregusage -DPASTokenReduction -enableHalfLSC -abiver 2" \
Addressed in https://github.com/intel/intel-xpu-backend-for-triton/pull/1970.
Created issue https://github.com/intel/intel-xpu-backend-for-triton/issues/1972.

2024-08-21 16:54 UTC, whitneywhtsang commented on scripts/test-triton.sh
>    IGC_VISAOptions=" -TotalGRFNum 256 -enableBCR -nolocalra -printregusage -DPASTokenReduction -enableHalfLSC -abiver 2" \
Addressed in https://github.com/intel/intel-xpu-backend-for-triton/pull/1970.

2024-08-21 16:54 UTC, whitneywhtsang commented on scripts/test-triton.sh
> +  IGC_VISAOptions=" -TotalGRFNum 256 -enableBCR -nolocalra -printregusage -DPASTokenReduction -enableHalfLSC" \
Addressed in https://github.com/intel/intel-xpu-backend-for-triton/pull/1970.

2024-08-21 23:16 UTC, merged