WIP: build benchmarks with upstream pytorch
intel/intel-xpu-backend-for-triton pull request #1905
Opened 2024-08-16 21:54 UTC by ZzEeKkAa

WIP

Reference: #1898

2024-08-20 20:17 UTC, ZzEeKkAa commented
@Wheest @ESI-SYD @chengjunlu could you please take a look at this DRAFT changes. I've converted it to work with upstream pytorch and made it work, so it compiles and produce number. But I don't have expertise in the product and how legit those changes are and if they negatively affects results. Could you review conceptually if this may take place. If so, I'll prepare it for the code review and make it production ready.

2024-08-21 09:13 UTC, chengjunlu commented on benchmarks/triton_kernels_benchmark/benchmark_testing.py
> +    with torch.profiler.profile() as prof:
Need to refer the Torch profiling step to capture the XPU kernel performance.

2024-08-21 19:07 UTC, ZzEeKkAa commented on benchmarks/triton_kernels_benchmark/benchmark_testing.py
> +    with torch.profiler.profile() as prof:
From the function description it should capture it whenever it is possible. I've set config explicitly hoping it will fail if XPU tracing is unavailable.

2024-08-21 19:07 UTC, ZzEeKkAa commented on benchmarks/triton_kernels_benchmark/benchmark_testing.py
> +    profiling_func_filter = filter(lambda x: x.name.startswith("__profile_kernel_of_func"), prof.events())
Could you provide some links what are you referring?

2024-08-21 19:12 UTC, ZzEeKkAa commented
> Basically looks good to me.
> 
> Need to confirm that the Torch profiler (Kineto) can capture the Triton kernel performance. Here is the steps to build the Torch with Kineto XPU supporting.
> 
> 1. Install the Intel PTI package: l_intel-pti-dev_p_0.9.0.38
> 2. Source the PTI env: source ${HOME}/intel/oneapi/pti/latest/env/vars.sh
> 3. Build the stock Pytorch.

I've build pytorch with PTI and was managed to get numbers out of gemm benchmark, but I don't have enough domain knowledge to confirm that they makes sense.

2024-08-22 02:18 UTC, chengjunlu commented on benchmarks/triton_kernels_benchmark/benchmark_testing.py
> +    profiling_func_filter = filter(lambda x: x.name.startswith("__profile_kernel_of_func"), prof.events())
I think you have already got the performance from the PTI. It is done.

2024-08-22 02:23 UTC, chengjunlu commented on benchmarks/triton_kernels_benchmark/benchmark_testing.py
> +    with torch.profiler.profile() as prof:
I thought we need to explicitly specified the XPU just as:
```
with torch.profiler.profile(activities=[torch.profiler.ProfilerActivity.XPU]) as prof:
```

I think it is ok if the XPU kernel performance is enabled by default.

2024-08-22 02:26 UTC, chengjunlu commented
> I've build pytorch with PTI and was managed to get numbers out of gemm benchmark, but I don't have enough domain knowledge to confirm that they makes sense.

We can compare the benchmark reports to the nightly performance reports.

2024-08-22 02:29 UTC, chengjunlu commented on benchmarks/triton_kernels_benchmark/benchmark_driver.py
> +# import intel_extension_for_pytorch
We can simply remove this file as long as Kineto works by removing the usage of this file at here:
https://github.com/intel/intel-xpu-backend-for-triton/blob/c7c60809cccfee24a650708712d9cc5aecf3db9f/benchmarks/triton_kernels_benchmark/__init__.py#L12

2024-08-22 17:51 UTC, ZzEeKkAa commented on benchmarks/triton_kernels_benchmark/benchmark_driver.py
> +# import intel_extension_for_pytorch
`benchmark_driver` is the file that you are saying to remove. If I remove both file and the highlighted line, I'm getting no numbers.

2024-08-22 17:56 UTC, ZzEeKkAa commented on benchmarks/xetla_kernel/python_main.cpp
> +  //   xpu::profiler_record("xetla kernel", evt);
I've also remove calls to `xpu::profiler_record("xetla kernel", evt);`. What it was doing? Why is it working without this usage?

2024-08-22 17:56 UTC, ZzEeKkAa commented on benchmarks/xetla_kernel/python_main.cpp
> +  //   xpu::profiler_record("xetla kernel", evt);
@chengjunlu

2024-08-23 00:46 UTC, chengjunlu commented on benchmarks/xetla_kernel/python_main.cpp
> +  //   xpu::profiler_record("xetla kernel", evt);
There are two profilers in the Torch. `torch.autograd.profiler_legacy.profile` and `torch.profiler.profile`.

The `xpu::profiler_record` is to add the SYCL event to the first profile and the legacy profile can get the Triton kernel performance statistics for using.

The second profiler is based on Kineto and PTI. If the Kineto can get the Triton kernel performance thru the PTI, then the function `xpu::profiler_record` is no longer required.

2024-08-28 04:27 UTC, chengjunlu commented
@ZzEeKkAa , The Kineto has issue in tracing the Triton kernel performance. The `triton.testing.do_bench` is used in the benchmarks for Pytorch 2.5.

We can use the benchmarks `do_bench` after the Kineto issue has been fixed.

2024-08-28 08:43 UTC, chengjunlu commented on benchmarks/triton_kernels_benchmark/benchmark_driver.py
> +# import intel_extension_for_pytorch
I met the same issue as yours. If we remove the `RECORD_FUNCTION` in the launcher, the Kineto cannot capture any Triton kernel performance.

I am not sure whether the time captured with the benchmark's launcher is correct. 

We use the Triton `do_bench` for now. Let's revisit the Kineto when the Kineto issue was solved.

2024-08-28 08:45 UTC, chengjunlu commented on benchmarks/xetla_kernel/CMakeLists.txt
> +target_compile_options(xetla_kernel PRIVATE "-fsycl" "-fpreview-breaking-changes")
@ZzEeKkAa The changes is required to run the XeTLA kernel in the benchmarks.

But do you have any idea why this flag is required?
https://github.com/intel/llvm/blob/283073a4f21aa44203fd49e25b4ff0379c91b29a/sycl/doc/UsersManual.md?plain=1#L429

2024-08-28 09:08 UTC, ESI-SYD commented
Can we update to setup upstream pytorch? Then we can run it in Actions.
https://github.com/intel/intel-xpu-backend-for-triton/blob/386ae76aebefa156d858f8cf6f58247764067340/.github/workflows/triton-benchmarks.yml#L52-L56

2024-08-30 00:14 UTC, chengjunlu approved these changes

2024-08-30 01:37 UTC, chengjunlu approved these changes

2024-08-30 01:49 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> +      - name: Setup no-op IPEX
Given that we are removing `import intel_extension_for_pytorch` in this PR, do we still need to setup no-op IPEX?

2024-08-30 01:49 UTC, whitneywhtsang commented on benchmarks/key_benchmarks/triton_kernels_benchmark/benchmark_testing.py
What's the performance impact, now that we change back to use elapsed time?

2024-08-30 02:24 UTC, ESI-SYD commented
[Upstream PT(9f1945a3bc1defa56c01cb1fbdfdd3a938e8c025)](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10609254853/job/29404643614)
vs [pt+ipex](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10605751168/job/29395177166)
: Has performance lost

[preprocessed-data-upstream-ipex.csv](https://github.com/user-attachments/files/16809422/preprocessed-data-upstream-ipex.csv)
[performance-plot-upstream-xetla-tflops-upstream-ipex-xetla-tflops-ipex.pdf](https://github.com/user-attachments/files/16809400/performance-plot-upstream-xetla-tflops-upstream-ipex-xetla-tflops-ipex.pdf)
[performance-plot-upstream-triton-tflops-upstream-ipex-triton-tflops-ipex.pdf](https://github.com/user-attachments/files/16809401/performance-plot-upstream-triton-tflops-upstream-ipex-triton-tflops-ipex.pdf)

2024-08-30 02:58 UTC, ESI-SYD commented on .github/workflows/triton-benchmarks.yml
> +      - name: Setup no-op IPEX
Yes, can removed

2024-08-30 03:19 UTC, whitneywhtsang commented
> [Upstream PT(9f1945a3bc1defa56c01cb1fbdfdd3a938e8c025)](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10609254853/job/29404643614) vs [pt+ipex](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10605751168/job/29395177166) : Has performance lost
> 
> [preprocessed-data-upstream-ipex.csv](https://github.com/user-attachments/files/16809422/preprocessed-data-upstream-ipex.csv) [performance-plot-upstream-xetla-tflops-upstream-ipex-xetla-tflops-ipex.pdf](https://github.com/user-attachments/files/16809400/performance-plot-upstream-xetla-tflops-upstream-ipex-xetla-tflops-ipex.pdf) [performance-plot-upstream-triton-tflops-upstream-ipex-triton-tflops-ipex.pdf](https://github.com/user-attachments/files/16809401/performance-plot-upstream-triton-tflops-upstream-ipex-triton-tflops-ipex.pdf)

Not sure how to read the result, looks like it failed to run? 
If there is performance lost, do you know why? Is the relative performance still the same between XeTLA and Triton?

2024-08-30 09:53 UTC, ESI-SYD commented
I updated this PR, skipped upstream torch sdpa failure to get successful [run](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10629513475/job/29466503753) to unblock Fa benchmark.

Take this one as [reference](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10623940969/job/29451334896) (with IPEX)

From reports generated by [script](https://github.com/intel/intel-xpu-backend-for-triton/pull/2060) and focus on cases whose relative difference value far from zero.

```bash
rm -rf performance* preprocess* ipex/ upstream/ && python compare_runs.py -d "ipex:10623940969" -n "upstream:10629513475" --triton-benchmark
```

**Difference summary:**
1. Ratio of `Triton`/ `XeTLA` keep same except for attention.
![image](https://github.com/user-attachments/assets/b008cc7e-e2d2-4b5e-81fd-934c7a41186d)
2. Attention `XeTLA` cases degraded (reproduced, needs fix)
![image](https://github.com/user-attachments/assets/ac3f17a3-bd20-4f4c-8462-12f0cf4b4bc9)
3. Both `Triton` and `XeTLA` softmax cases degraded, so ratio not changed.

2024-08-30 15:08 UTC, whitneywhtsang commented on benchmarks/key_benchmarks/triton_kernels_benchmark/benchmark_testing.py
Answered in https://github.com/intel/intel-xpu-backend-for-triton/pull/1905#issuecomment-2320701513.

2024-08-30 17:22 UTC, etiotto requested changes
I am under the impression the benchmark FA code cannot be run using PyTorch and can only be run correctly using IPEX. This suggests that we *cannot* remove the dependency on IPEX for the benchmark codes until pytorch fixes the functional problem affecting FA.  For this reason I am blocking the PR from merging.  We cannot remove verification code from the FA benchmark because doing so would prevent proper functional checking for PRs that might modify the FA codegen.

2024-09-03 13:17 UTC, kwasd commented
(required for #1933)

2024-09-05 18:37 UTC, whitneywhtsang commented
Blocked by https://github.com/intel/intel-xpu-backend-for-triton/issues/2042, converting to draft.

2024-09-08 13:52 UTC, anmyachev commented
> I updated this PR, skipped upstream torch sdpa failure to get successful [run](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10629513475/job/29466503753) to unblock Fa benchmark.
> 
> Take this one as [reference](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10623940969/job/29451334896) (with IPEX)
> 
> From reports generated by [script](https://github.com/intel/intel-xpu-backend-for-triton/pull/2060) and focus on cases whose relative difference value far from zero.
> 
> ```shell
> rm -rf performance* preprocess* ipex/ upstream/ && python compare_runs.py -d "ipex:10623940969" -n "upstream:10629513475" --triton-benchmark
> ```
> 
> **Difference summary:**
> 
> 1. Ratio of `Triton`/ `XeTLA` keep same except for attention.
> 2. Attention `XeTLA` cases degraded (reproduced, needs fix)
> 3. Both `Triton` and `XeTLA` softmax cases degraded, so ratio not changed.

I still see `RECORD_FUNCTION("xetla softmax", {input});` (and similar) function calls. Can this affect the performance?

2024-10-16 20:37 UTC, closed without merging