Refactor instruction schedule pass
intel/intel-xpu-backend-for-triton pull request #1919
Opened 2024-08-19 08:11 UTC by LiyangLingIntel

Refactor `ScheduleLoad` pass to make it work for both GEMM and FlashAttention cases.

2024-08-20 17:35 UTC, whitneywhtsang commented
Did you verify that flash attention can still get the good performance after this change?

2024-08-20 17:43 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUTransforms/ScheduleLoad.cpp
> +        unsigned groupId = dotsGroup.second;
```suggestion
        auto [dots, groupId] = dotsGroup;
```

2024-08-20 21:15 UTC, etiotto commented on test/TritonIntelGPU/schedule-load.mlir
> +module attributes {"triton_gpu.num-ctas" = 1 : i32, "triton_gpu.num-warps" = 32 : i32, "triton_gpu.threads-per-warp" = 16 : i32, triton_intel_gpu.min_sg_size = 16 : i32, triton_intel_gpu.support_dpas
I have another PR where I have simplified the first test. This new GEMM test can also be similarly simplified (remove attributes that aren't required, remove code that isn't required e.g. the stores at the end and any operation that can be made dead without altering the functionality of the test).

2024-08-21 01:57 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUTransforms/ScheduleLoad.cpp
> +        unsigned groupId = dotsGroup.second;
Updated.
Personally I would prefer using auto like this way. The old implementation was because I thought our using `auto` criteria is only when there is explicit type marking.

2024-08-21 02:02 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUTransforms/ScheduleLoad.cpp
> +        unsigned groupId = dotsGroup.second;
Complicated type is also allowed: https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable

2024-08-21 02:03 UTC, LiyangLingIntel commented
> Did you verify that flash attention can still get the good performance after this change?

Not yet. I don't think flash attention performance should be affected becaue the conversion results before and after this change are the same. 
The changes in this PR just do refactoring and make the logic working for GEMM.

2024-08-21 10:23 UTC, FMarno requested changes

2024-08-21 10:23 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUTransforms/ScheduleLoad.cpp
> +      SmallVector<std::pair<SmallVector<tt::DotOp>, int>> dotsGroup;
Why was this changed to a pair? the second value doesn't seem to be used

2024-08-22 06:14 UTC, LiyangLingIntel commented on third_party/intel/lib/TritonIntelGPUTransforms/ScheduleLoad.cpp
> +      SmallVector<std::pair<SmallVector<tt::DotOp>, int>> dotsGroup;
The second value was used for make decision for inst moving, it looks we can deprecated it for now.
Updated.

2024-08-22 08:31 UTC, FMarno approved these changes
That all looks tidier but you have changed the logic a bit, it may have just been more complicated than needed. I don't know if the existing lit test covered all the aspects of the previous logic, so I think it is worth checking the performance.

2024-08-22 08:31 UTC, FMarno commented on third_party/intel/lib/TritonIntelGPUTransforms/ScheduleLoad.cpp
> +        notVisited.append(getNotVisitedUses(dots, 1));
instead of calling `getNotVisitedUses` twice, consider removing the `opIdx` arg and just doing two loops in the `getNotVisitedUses` function call.

2024-08-22 18:21 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUTransforms/ScheduleLoad.cpp
> +        notVisited.append(getNotVisitedUses(dots, 1));
done.

2024-08-22 19:16 UTC, whitneywhtsang approved these changes
Verified no performance impact with this change on FA.

2024-08-22 19:17 UTC, merged