Show error installing upstream pytorch not source
intel/intel-xpu-backend-for-triton pull request #1950
Opened 2024-08-20 17:03 UTC by Retribution98

The core Triton is a small number of people, and we receive many PRs (thank
you!).  To help us review your code more quickly, **if you are a new
contributor (less than 3 PRs merged) we ask that you complete the following
tasks and include the filled-out checklist in your PR description.**

Complete the following tasks before sending your PR, and replace `[ ]` with
`[x]` to indicate you have done them.

- [x] I am not making a trivial change, such as fixing a typo in a comment.

- [x] I have written a PR description following these
  [rules](https://cbea.ms/git-commit/#why-not-how).

- [x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.

- Select one of the following.
  - [ ] I have added tests.
    - `/test` for `lit` tests
    - `/unittest` for C++ tests
    - `/python/test` for end-to-end tests
  - [x] This PR does not need a test because `FILL THIS IN`.

- Select one of the following.
  - [x] I have not added any `lit` tests.
  - [ ] The `lit` tests I have added follow these [best practices](https://mlir.llvm.org/getting_started/TestingGuide/#filecheck-best-practices),
    including the "tests should be minimal" section. (Usually running Python code
    and using the instructions it generates is not minimal.)

2024-08-21 09:43 UTC, anmyachev commented on scripts/compile-pytorch-ipex.sh
> +  fi
As far as I understand, it is implicitly assumed that the already assembled wheels are just for the pinned versions (just not for the upstream ones)

```suggestion
```

2024-08-21 10:55 UTC, Retribution98 commented on scripts/compile-pytorch-ipex.sh
> +  fi
Yes, but if your branch is no longer up to date, it will install a newer version than expected. Is this ok?

2024-08-21 11:01 UTC, anmyachev commented on scripts/compile-pytorch-ipex.sh
> +  fi
> Is this ok?

No, but apparently it happens rarely. You can add a check that the versions match (what was downloaded and what we are pinning)

2024-08-21 19:15 UTC, vlad-penkin requested changes

2024-08-21 19:15 UTC, vlad-penkin commented on scripts/compile-pytorch-ipex.sh
> +  fi
Nightly wheels will be available after
- #1913
is implemented during current iteration. There is no need to make temporary change

2024-08-22 14:13 UTC, Retribution98 commented
@vlad-penkin is it ok now?

2024-08-23 00:32 UTC, vlad-penkin commented
> @vlad-penkin is it ok now?

Why do we need this change after this PR merge:

- #1955

?

2024-08-23 14:17 UTC, anmyachev commented on scripts/compile-pytorch-ipex.sh
> +  fi
Is this the only difference between upstream and proxy pytorch wheels?

2024-08-23 14:17 UTC, anmyachev approved these changes
LGTM!

2024-08-23 14:33 UTC, Retribution98 commented on scripts/compile-pytorch-ipex.sh
> +  fi
yes, but only for torch. 
ipex doesn't exist, so we need to build noop locally

2024-08-23 14:35 UTC, Retribution98 commented
> Why do we need this change after this PR merge:
@vlad-penkin 
Yes, this issue is now complete, but the script is still not working correctly.
I replaced the error by installing the correct version from the wheels

2024-08-23 15:05 UTC, pbchekin commented on scripts/compile-pytorch-ipex.sh
> +      if [[ "noop" = "$IPEX_CURRENT_COMMIT"* ]]; then
This does not work:

```
# prints nothing
IPEX_CURRENT_COMMIT="2.4.0+noop"
[[ "noop" = "$IPEX_CURRENT_COMMIT"* ]] && echo noop
```

This should work:

```
IPEX_CURRENT_COMMIT="2.4.0+noop"
[[ $IPEX_CURRENT_COMMIT = *noop ]] && echo noop
```

2024-08-23 15:05 UTC, pbchekin commented on scripts/compile-pytorch-ipex.sh
> +      if [[ "$IPEX_PINNED_COMMIT" = "$IPEX_CURRENT_COMMIT"* ]]; then
If you use double square brackets, then quotes are not needed:
```suggestion
      if [[ $IPEX_PINNED_COMMIT = $IPEX_CURRENT_COMMIT* ]]; then
```

2024-08-23 15:05 UTC, pbchekin commented on scripts/compile-pytorch-ipex.sh
> +    --pattern $WHEEL_PATTERN \
Just to be on the safe side:
```suggestion
    --pattern "$WHEEL_PATTERN" \
```
We don't want bash to interpolate WHEEL_PATTERN if there is a file or directory with the name that matches .

2024-08-23 15:15 UTC, Retribution98 commented on scripts/compile-pytorch-ipex.sh
> +      if [[ "noop" = "$IPEX_CURRENT_COMMIT"* ]]; then
I checked and it should work because the current commit is split on the 148 line and only the part after + remains
I believe we don't need to hardcode the expected version there, because is set in the other script.
Should we pin it like as IPEX version or can we check only "noop" suffix?

2024-08-23 15:15 UTC, Retribution98 commented on scripts/compile-pytorch-ipex.sh
> +      if [[ "$IPEX_PINNED_COMMIT" = "$IPEX_CURRENT_COMMIT"* ]]; then
I see. Thank you!

2024-08-23 15:16 UTC, Retribution98 commented on scripts/compile-pytorch-ipex.sh
> +    --pattern $WHEEL_PATTERN \
Agree, thank you

2024-08-23 20:10 UTC, vlad-penkin commented
> > Why do we need this change after this PR merge:
> 
> @vlad-penkin Yes, this issue is now complete, but the script is still not working correctly. I replaced the error by installing the correct version from the wheels

Can we rename the PR and the linked issue? Current titles are misguiding.

2024-08-23 20:45 UTC, Retribution98 commented
> Can we rename the PR and the linked issue? Current titles are misguiding.

@vlad-penkin
All is updated

2024-08-23 22:51 UTC, vlad-penkin commented
Provided my feedback in https://github.com/intel/intel-xpu-backend-for-triton/issues/1949#issuecomment-2307899415.

2024-08-26 15:49 UTC, AshburnLee reviewed
I use your forked repo and branch, 
1. At least this use case fails on test:
~~~
./scritps/compile-triton.sh --clean
./scripts/compile-pytorch-ipex.sh --upstream-pytorch  --no-op-ipex --pinned
./scritps/test-triton.sh --no-deps --core
~~~

2. And in the following use case, the test script will build IPEX which is not expected:
~~~
./scritps/compile-triton.sh --clean
./scripts/compile-pytorch-ipex.sh --upstream-pytorch  --no-op-ipex --source
./scritps/test-triton.sh --no-deps --core  # will build IPEX
# log: **** Install IPEX from nightly builds. ****
~~~ 
`test-triton.sh` needs change accordingly.
Please give a further check.

I'll check other use cases.

2024-08-26 19:26 UTC, pbchekin commented on scripts/compile-pytorch-ipex.sh
> +      if [[ $IPEX_PINNED_COMMIT = $IPEX_CURRENT_COMMIT* ]]; then
`IPEX_PINNED_COMMIT` is a full commit id, `IPEX_CURRENT_COMMIT` is a short commit id?
If this is the case then `[[ $IPEX_PINNED_COMMIT = $IPEX_CURRENT_COMMIT* ]]` won't work.

2024-08-26 19:39 UTC, Retribution98 commented
@AshburnLee thank you for you comment,
 
> At least this use case fails on test:
Unfortunately, I can not reproduce your fails, could you share what kind of errors you're getting?

But I see that you are using the wrong `--no-deps` parameter in both cases. The correct option is `--skip-deps`.
If the `--skip-deps` parameter is not given, the IPEX version from wheels is installed by default.

2024-08-26 19:58 UTC, Retribution98 commented on scripts/compile-pytorch-ipex.sh
> +      if [[ $IPEX_PINNED_COMMIT = $IPEX_CURRENT_COMMIT* ]]; then
`IPEX_PINNED_COMMIT` - the value from `./github/pins/ipex.txt`
`IPEX_CURRENT_COMMIT` - the value from the installed version.

In this PR, I'm keeping the previous behavior:
1. We get the full version name and put it in `IPEX_CURRENT_COMMIT`.
2. We then split the current value. 
    - If this version was built by the specific commit, we can get its hash and put it back into `IPEX_CURRENT_COMMIT`.
    - If IPEX was built from our `create-noop-ipex.py` script, the version has `noop` instead of the commit hash and we also put it into `IPEX_CURRENT_COMMIT`.

I agree that the variable name doesn't show the full picture of what's going on, but I think it was done to reuse the variable and not increase the number of variables. Do you suggest using an additional variable?

2024-08-26 20:12 UTC, pbchekin approved these changes

2024-08-26 20:28 UTC, vlad-penkin commented
> @AshburnLee thank you for you comment,
> 
> > At least this use case fails on test:
> > Unfortunately, I can not reproduce your fails, could you share what kind of errors you're getting?
> 
> But I see that you are using the wrong `--no-deps` parameter in both cases. The correct option is `--skip-deps`. If the `--skip-deps` parameter is not given, the IPEX version from wheels is installed by default.

This behavior needs to be changed as part of this PR. Nightly PyTorch wheel should be installed by default.

2024-08-27 06:06 UTC, AshburnLee commented
There are 4 use cases for this script:

1. Build upstream pytorch with branch dev/triton-test-3.0 & fake IPEX:
`./scripts/compile-pytorch-ipex.sh --upstream-pytorch (--no-op-ipex --source)`
IPEX version & torch version:
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.1.0a0+git4de5871  # pytorch branch: dev/triton-test-3.0

`test-triton.sh --skip-deps` faild:
```
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_block_pointer.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_core.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
ERROR language/test_standard.py - AttributeError: module 'torch' has no attribute 'xpu'
```

2. Build upstream pytorch from pinned commit & fake IPEX
`./scripts/compile-pytorch-ipex.sh --upstream-pytorch --no-op-ipex --pinned`
IPEX version & torch version:
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.5.0a0+gitb7baa06   # pinned upstream-pytorch

`test-triton.sh --skip-deps` faild:
```
FAILED language/test_compile_errors.py::test_returns_branched_on_non_constexpr - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_global_var_access - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_binary_op - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_undefined_variable - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_builtin - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_not_const_annotate_no_err - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_static_assert - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_power_of_two_shapes_2 - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_power_of_two_shapes - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_constexpr_annotated_global_var_access - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_returns_branched_on_constexpr - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_binary_operator - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_captured_var_access - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_unary_op - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_two_returns_no_err - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_err_in_nested_call - ImportError: /home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/torch/lib/libc10_xpu.so: undefined symbol: _ZNK4sycl3_V16device32ext_oneapi_supports_cl_extensionENS0_6detail11string_viewEPNS0_3ext6oneapi12experimental10cl_versionE
FAILED language/test_compile_errors.py::test_constexpr_global_var_access - ImportError: /home/jovyan/conda/envs/junh [...]

2024-08-27 06:27 UTC, AshburnLee commented
I think we may need a doc on how to use this script for users.

To be honest, I'm confused reading this script :sweat_smile: , the `--help` dose not help at all "Example usage: ./compile-pytorch-ipex.sh [--pytorch | --upstream-pytorch | --ipex | --no-op-ipex | --pinned | --source | --clean | --venv]". This can't show me how to use the script.

Without the instruction I can only think of the 4 use cases as commented above. I'm not sure if they are REAL use cases.

Please correct me if I was wrong, thanks.

Since this script has been constantly changes over an extended period, I am considering to refactor it for friendly readability.

2024-08-27 08:53 UTC, AshburnLee commented
Append another use case:
Case  1 + `--clean`:
`./scripts/compile-pytorch-ipex.sh --upstream-pytorch --clean`
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.5.0a0+git3515090  # upstream pytorch commit (https://github.com/pytorch/pytorch/pull/134457)
`test-triton.sh --skip-deps` pass

2024-08-27 08:56 UTC, Retribution98 commented
@AshburnLee 
> Build upstream pytorch with branch dev/triton-test-3.0

What is this? I don't see this branch in the upstream.
As far as I can tell from this script, this branch is used with https://github.com/Stonepia/pytorch and is based on torch 2.1.0a0.
It looks like it should be used with IPEX. 

> ./scripts/compile-pytorch-ipex.sh --upstream-pytorch (--no-op-ipex --source)
Why do you use '(' and ')' ?

2024-08-27 18:30 UTC, anmyachev commented on scripts/test-triton.sh
> -$SKIP_DEPS || $SCRIPTS_DIR/compile-pytorch-ipex.sh --pinned $ARGS
@Retribution98 I believe we can remove `ARGS` from this script at all.

2024-08-27 18:43 UTC, Retribution98 commented on scripts/test-triton.sh
> -$SKIP_DEPS || $SCRIPTS_DIR/compile-pytorch-ipex.sh --pinned $ARGS
It is declared in all scripts, even if it is not used. I think we should have the same structure in different places. That seems like a separate issue, doesn't it?

2024-08-27 18:57 UTC, anmyachev commented on scripts/test-triton.sh
> -$SKIP_DEPS || $SCRIPTS_DIR/compile-pytorch-ipex.sh --pinned $ARGS
If we leave it as is, the parameters will get into this variable without any messages/warnings or processing. Avoiding such a situation seems more important to me personally than having the same interface everywhere.

2024-08-27 19:35 UTC, vlad-penkin approved these changes
LGTM

2024-08-27 19:38 UTC, merged

2024-08-28 02:41 UTC, AshburnLee commented
After swiching to newer PTDB(0.5.2->**0.5.3**) and Agama(914.32->**950.13**), `test-triton.sh` works fine for upstream-pytorch both from source & from pinned:

./scripts/compile-pytorch-ipex.sh --upstream-pytorch  # default is pinned
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.5.0a0+gitb7baa06   # pinned upstream pytorch

./scripts/compile-pytorch-ipex.sh --upstream-pytorch --source
- intel_extension_for_pytorch 2.4.0+noop
- torch                       2.5.0a0+gitf33bcbe   # source upstream pytorch

@Retribution98 @vlad-penkin