[MatchTargetSize] Extend for-loop canonicalization pattern
intel/intel-xpu-backend-for-triton pull request #2045
Opened 2024-08-29 14:03 UTC by jopperm

Support canonicalization of dependent `scf.for` loops by re-gluing individual results after the loop.

See https://github.com/intel/intel-xpu-backend-for-triton/pull/1947 for more context / the complete PoC.

2024-08-29 17:16 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +                       [](auto *user) { return isa<ttgi::ExtractOp>(user); })) {
auto* -> Operation*

2024-08-29 17:16 UTC, etiotto commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +      } else if (llvm::all_of(result.getUsers(), [](auto *user) {
auto * -> Operation *

2024-08-30 14:27 UTC, victor-eds approved these changes

2024-09-02 02:01 UTC, Dewei-Wang-sh requested changes

2024-09-02 02:01 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +    llvm::SmallDenseMap<OpResult, Value> reglueMap;
we can extend the new condition by handling the scf.yield operation.
no need to add a map.
if the scf.yield has a operand whose def is glue, then split it into two operands

2024-09-02 14:27 UTC, jopperm commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +    llvm::SmallDenseMap<OpResult, Value> reglueMap;
I've simplified the code to always insert glue ops after the loop, and replacing results immediately without storing them in a map.

2024-09-09 03:10 UTC, Dewei-Wang-sh approved these changes
LGTM

2024-09-09 03:12 UTC, merged