[Adv][MatchTargetSize] Use transposed reduction
intel/intel-xpu-backend-for-triton pull request #2109
Opened 2024-09-04 10:21 UTC by victor-eds

Sub-group reduction can be expensive compared to elementwise operations. Before reducing across the sub-group, perform a sub-group transpose, enabling across the work-item reductions via elementwise operations.

Set the `TRITON_INTEL_REDUCE_TRANSPOSE` environment variable to enable this optimization.

See https://github.com/intel/intel-xpu-backend-for-triton/issues/1637.

2024-09-05 08:16 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +  // Fixed for reduce transpose.
can you put this to a separate function?
the default way is not to use the transposed reduction.

2024-09-05 08:29 UTC, victor-eds commented
Updated speedups after local memory size optimization:

| Z | H | N_CTX | D_HEAD | avg_speedup | max_speedup | min_speedup | fastest kernel time speedup |
|--|--|--|--|--|--|--|--|
| 4 | 48 | 1024 | 64 | 1.10191010384 | 1.07082957743 | 1.09588523178 | 1.068683061|
| 32 | 32 | 512 | 64 | 1.01343202132 | 1.0217439084 | 0.99757119036 | 1.058990189|
| 16 | 32 | 1024 | 64 | 0.992116020819 | 1.02069447274 | 0.987583771168 | 1.052717338 |
| 8 | 32 | 2048 | 64 | 1.01413512218 | 1.05291521059 | 0.96438796374 | 1.044926112|
| 4 | 32 | 4096 | 64 | 0.99789214318 | 1.01624939711 | 0.97283415829 | 1.009807591|
| 2 | 32 | 8192 | 64 | 0.978309856454 | 0.985213529856 | 0.982828752225 | 1.006800757|
| 1 | 32 | 16384 | 64 | 0.994263113805 | 0.991351341065 | 1.01170229538 | 1.04698394|

2024-09-05 08:39 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +  // Fixed for reduce transpose.
I think the transposed reduction should be the default path, as it also opens possibility for further optimizations exploiting the new tensor layout. If we drop the layout conversion in L889 (introduced for simplicity), we'd end up with an optimal encoding that can reduce the number of followup elementwise tensor instructions by a factor of 16. Basically, we could go from the current:
| t0 | t1 | t2 | ... | t15 |
| -- | -- | -- | -- | -- |
| el0 | x | x | ... | x |
| el1 | x | x | ... | x |
| ... | x | x | ... | x |
| el15 | x | x | ... | x |

To:

| t0 | t1 | t2 | ... | t15 |
| -- | -- | -- | -- | -- |
| el0 | el1 | el2 | ... | el15 |


That way, operations like:

```
%200 = arith.addf %199, %196 fastmath<fast> : tensor<16xf32, #triton_gpu.slice<{dim = 1, parent = #warp}>> loc(#loc)
```

appearing in our codegen and currently represented as *16* additions (SIMD1) as per current encoding would require *1* addition (SIMD16).

2024-09-05 13:55 UTC, sommerlukas commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +  // Fixed for reduce transpose.
>  the default way is not to use the transposed reduction.

As Victor's measurements of kernel time indicate that the transposed reduction is beneficial in some cases and does not cause performance regressions in the remaining cases, we should consider making the transposed reduction the default.

2024-09-06 09:19 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +  // Fixed for reduce transpose.
1/7 is beneficial, and "16 32 1024 64" actually has the same kernel with "4 48 1024 64", but do not benefit at all.
1.  I doubt this speedup number, it does not make sense.
2.  with a more complicated code, we only got very little perf benefit.

2024-09-06 09:21 UTC, Dewei-Wang-sh commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +  // Fixed for reduce transpose.
> rted, I understand hiding this behavior behind

yes, after all features ported which  Quintin is working on, then we can decide according to the CI benchmark data.
but for now, it's better to put it in a separate function.

2024-09-06 09:23 UTC, Dewei-Wang-sh requested changes
ok if transposed reduction is not mixed with current impl.

2024-09-06 09:26 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +  // Fixed for reduce transpose.
Kernel time speedups might be more accurate as these won't include runtime overhead that may hide absolute execution time speedups.

2024-09-09 08:12 UTC, Dewei-Wang-sh commented on third_party/intel/include/Dialect/TritonIntelGPU/IR/Utils.h
> +  return std::getenv("TRITON_INTEL_REDUCE_TRANSPOSE");
triton has a default method to get bool env.

2024-09-09 08:16 UTC, Dewei-Wang-sh approved these changes
overall lgtm

2024-09-09 11:33 UTC, victor-eds commented on third_party/intel/include/Dialect/TritonIntelGPU/IR/Utils.h
> +  return std::getenv("TRITON_INTEL_REDUCE_TRANSPOSE");
Used. Thanks!

2024-09-09 16:32 UTC, sommerlukas approved these changes

2024-09-10 14:25 UTC, etiotto approved these changes

2024-09-11 00:43 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      Value element = rewriter.create<TritonGEN::SubGroupShuffleOp>(
`TritonGEN::SubGroupShuffleOp` is removed.

2024-09-11 01:08 UTC, whitneywhtsang commented
CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10803054713/job/29966267884
Doesn't appear to work.

2024-09-11 01:12 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      Value element = rewriter.create<TritonGEN::SubGroupShuffleOp>(
Fixed by https://github.com/intel/intel-xpu-backend-for-triton/pull/2109/commits/c3879b9c0853e28b5038e6fbcda8b3d8af5e430e.

2024-09-11 09:16 UTC, victor-eds commented
> CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10803054713/job/29966267884
> Doesn't appear to work.

Apparently there is a pass getting encoding advanced path is dropping and that's the crash. Pushing fix.

2024-09-11 10:43 UTC, victor-eds commented
Run and verification passing on my machine. Can you rerun on your branch after rebase?

2024-09-12 03:03 UTC, whitneywhtsang commented
Verified it works now, CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10823296402.
Please don't forget to revert your changes to `triton-benchmarks.yml`.

2024-09-12 03:13 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +  constexpr unsigned subGroupSize = 16;
is it more robust to get subgroup size from module?

2024-09-12 08:03 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUTransforms/MatchTargetSize.cpp
> +  constexpr unsigned subGroupSize = 16;
That's how it's done in the whole file. I don't think this pass works with other sub-group size

2024-09-12 16:00 UTC, whitneywhtsang approved these changes

2024-09-12 16:03 UTC, merged