Decompose large `simdblockread` to smaller `simdblockread`s
intel/intel-xpu-backend-for-triton pull request #2193
Opened 2024-09-11 05:01 UTC by whitneywhtsang

`<64xi16>` `simdblockread` is not supported by OpenCL C builtins, decompose it to `8 x <8xi8>`.

2024-09-11 05:26 UTC, whitneywhtsang commented
Before this PR: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10805431155
After this PR: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10805299931
Performance improves with this PR.

2024-09-11 06:16 UTC, quintinwang5 commented
> Before this PR: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10805431155 After this PR: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10805299931 Performance of SLM path improves with this PR. Performance of SLM path looks slower than my expectation, @quintinwang5 what's the expected performance of SLM path?

local data:
```
attn-performance:
      Z     H    N_CTX  D_HEAD  Triton-GB/s  XeTLA-GB/s  Triton-GB/s-min  XeTLA-GB/s-min  Triton-GB/s-max  XeTLA-GB/s-max  Triton-TFlops  XeTLA-TFlops  Triton-TFlops-min  XeTLA-TFlops-min  Triton-TFlops-max  XeTLA-TFlops-max  Triton-CV  XeTLA-CV
0   1.0  32.0  16384.0    64.0    10.382262   16.149019        10.382262       16.149019        10.382262       16.149019      85.051490    132.292763          85.051490        132.292763          85.051490        132.292763        NaN       NaN
1   2.0  32.0   8192.0    64.0    20.954494   32.180948        20.954494       32.180948        20.954494       32.180948      85.829609    131.813164          85.829609        131.813164          85.829609        131.813164        NaN       NaN
2   4.0  32.0   4096.0    64.0    42.069249   61.615244        42.069249       61.615244        42.069249       61.615244      86.157822    126.188019          86.157822        126.188019          86.157822        126.188019        NaN       NaN
3   4.0  48.0   1024.0    64.0   170.200363  212.119221       150.046645      212.119221       175.054429      212.119221      87.142586    108.605041          76.823882        108.605041          89.627868        108.605041   0.036618       NaN
4   8.0  32.0   2048.0    64.0    88.815334  121.433232        88.352289      121.433232        89.283250      121.433232      90.946902    124.347630          90.472744        124.347630          91.426048        124.347630   0.007412       NaN
5  16.0  32.0   1024.0    64.0   170.390493  228.915493       155.531799      228.915493       174.944903      228.915493      87.239932    117.204732          79.632281        117.204732          89.571790        117.204732   0.002092       NaN
6  32.0  32.0    512.0    64.0   260.522518  394.943885       247.597618      394.943885       268.908737      394.943885      66.693765    101.105635          63.384990        101.105635          68.840637        101.105635   0.011547   
```
SLM path should be about  <= 10 TFLOPS than advanced path.
At least, you need the following environment variables to get relative good performance in advanced(and SLM) path:
```
export TRITON_INTEL_ENABLE_INSTR_SCHED=1
export TRITON_INTEL_ENABLE_FAST_PREFETCH=1
```

2024-09-11 06:28 UTC, Dewei-Wang-sh requested changes
by default, we do not want enable first load to slm.

2024-09-11 06:30 UTC, Dewei-Wang-sh commented
please get me informed for what happened in advanced path!!!!

2024-09-11 09:24 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      auto simdRead = rewriter.create<GlueOp>(loc, v64i16Ty, values);
```suggestion
      VectorType v8i16Ty = VectorType::get(8, i16_ty);
      SmallVector<Value> values;
      Value offset = i32_val(128);
      for (int i = 0; i < 8; ++i) {
        auto simdRead =
            rewriter.create<TritonGEN::SIMDBlockReadOp>(loc, v8i16Ty, base);
        values.push_back(simdRead.getRes());
        base = gep(ptrToSharedMemTy, i16_ty, base, offset);
      }
      auto simdRead = rewriter.create<GlueOp>(loc, v64i16Ty, values);
```
```suggestion
      VectorType v8i16Ty = VectorType::get(8, i16_ty);
      SmallVector<Value> values;
      Value offset = i32_val(/*getSubGroupSize()*/);
      for (int i = 0; i < 8; ++i) {
        auto simdRead =
            rewriter.create<TritonGEN::SIMDBlockReadOp>(loc, v8i16Ty, base);
        values.push_back(simdRead.getRes());
        base = gep(ptrToSharedMemTy, v8i16Ty, base, offset);
      }
      auto simdRead = rewriter.create<GlueOp>(loc, v64i16Ty, values);
```

Equivalent and more intuitive. This is a sub-group operation in which each work-item reads a `v8i16Ty` value, so we can offset by sub-group size `v8i16Ty` elements.

2024-09-11 09:27 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      auto simdRead = rewriter.create<GlueOp>(loc, v64i16Ty, values);
Also, can we avoid magic number `8`?

2024-09-11 13:38 UTC, whitneywhtsang commented
> by default, we do not want enable first load to slm.

There is no plan to enable first load to slm by default, this a draft PR, two of the commits are used for testing, as I am changing the lowering for SLM path, so enabled it to ensure it works as expected in the meantime.

2024-09-11 13:39 UTC, whitneywhtsang commented
> please get me informed for what happened in advanced path!!!!

Of course, this is a draft PR, not ready for review.

2024-09-11 15:59 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      auto simdRead = rewriter.create<GlueOp>(loc, v64i16Ty, values);
Ups, that was weird.

2024-09-11 20:59 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      auto simdRead = rewriter.create<GlueOp>(loc, v64i16Ty, values);
done.

2024-09-12 01:22 UTC, Dewei-Wang-sh commented
> 01.744336

yet you requested others for review...

2024-09-12 01:23 UTC, Dewei-Wang-sh commented
> > please get me informed for what happened in advanced path!!!!
> 
> Of course, this is a draft PR, not ready for review.


but you requested others for review...

2024-09-12 01:34 UTC, whitneywhtsang commented
> > > please get me informed for what happened in advanced path!!!!
> > 
> > 
> > Of course, this is a draft PR, not ready for review.
> 
> but you requested others for review...

Mainly want to get early feedback from Victor, as the idea came from him. And Quintin, as the results of FA with SLM path didn't look right. Anyways, I will take extra caution to  include you on advanced path changes, or remember to not request any reviewers for draft PR.

2024-09-12 01:46 UTC, Dewei-Wang-sh commented
> > > > please get me informed for what happened in advanced path!!!!
> > > 
> > > 
> > > Of course, this is a draft PR, not ready for review.
> > 
> > 
> > but you requested others for review...
> 
> Mainly want to get early feedback from Victor, as the idea came from him. And Quintin, as the results of FA with SLM path didn't look right. Anyways, I will take extra caution to include you on advanced path changes, or remember to not request any reviewers for draft PR.

thanks.
FYI, I'm the one who proposed to used SLM first in FA.

> > > > please get me informed for what happened in advanced path!!!!
> > > 
> > > 
> > > Of course, this is a draft PR, not ready for review.
> > 
> > 
> > but you requested others for review...
> 
> Mainly want to get early feedback from Victor, as the idea came from him. And Quintin, as the results of FA with SLM path didn't look right. Anyways, I will take extra caution to include you on advanced path changes, or remember to not request any reviewers for draft PR.

Thanks.
FYI, I'm the one who proposed to use SLM and SIMDBLOCKload/store during the FA.

2024-09-12 01:46 UTC, Dewei-Wang-sh commented
> > > > please get me informed for what happened in advanced path!!!!
> > > 
> > > 
> > > Of course, this is a draft PR, not ready for review.
> > 
> > 
> > but you requested others for review...
> 
> Mainly want to get early feedback from Victor, as the idea came from him. And Quintin, as the results of FA with SLM path didn't look right. Anyways, I will take extra caution to include you on advanced path changes, or remember to not request any reviewers for draft PR.

Thanks.
FYI, I'm the one who proposed to use SLM and SIMDBLOCKload/store during the FA.

2024-09-12 01:47 UTC, whitneywhtsang commented
Baseline CI: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10821106789
This PR: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10820043424
Results within the margin of error.

2024-09-12 01:51 UTC, whitneywhtsang commented
> > > > > please get me informed for what happened in advanced path!!!!
> > > > 
> > > > 
> > > > Of course, this is a draft PR, not ready for review.
> > > 
> > > 
> > > but you requested others for review...
> > 
> > 
> > Mainly want to get early feedback from Victor, as the idea came from him. And Quintin, as the results of FA with SLM path didn't look right. Anyways, I will take extra caution to include you on advanced path changes, or remember to not request any reviewers for draft PR.
> 
> Thanks. FYI, I'm the one who proposed to use SLM and SIMDBLOCKload/store during the FA.

Sounds good. Just to clarify, I meant the idea of this PR, i.e., decompose `simdblockread` to OpenCL C builtin supporting sizes, came from Victor.

2024-09-12 02:23 UTC, whitneywhtsang commented
Will do a similar change to `simdblockwrite` if this change looks good to reviewers.

2024-09-12 08:01 UTC, victor-eds approved these changes

2024-09-12 08:01 UTC, victor-eds commented on third_party/intel/lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
> +}
For future: Change operation signature to use scalars instead of vectors of length 1.

2024-09-12 14:05 UTC, whitneywhtsang commented on third_party/intel/lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
> +}
Sounds good, will do that.

2024-09-12 14:53 UTC, etiotto commented
@Dewei-Wang-sh looks like you asked for changes for this PR. Does it now look OK to you as well ?

2024-09-12 15:44 UTC, victor-eds commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      const unsigned maxOCLVectorSize = 8;
Also, I think the name is a bit misleading as the maximum OCL vector size is 16. Can we rename it to `maxBlockLoadi16Width`?

2024-09-12 16:05 UTC, whitneywhtsang commented on third_party/intel/lib/TritonIntelGPUToLLVM/TritonOpsToLLVM.cpp
> +      const unsigned maxOCLVectorSize = 8;
done.

2024-09-13 04:11 UTC, whitneywhtsang commented
> Results within the margin of error on SLM path.

2024-09-13 04:12 UTC, whitneywhtsang commented
> Will do a similar change to `simdblockwrite` if this change looks good to reviewers.

Done in https://github.com/intel/intel-xpu-backend-for-triton/pull/2227.

2024-09-13 07:56 UTC, Dewei-Wang-sh approved these changes
lgtm

2024-09-13 15:47 UTC, merged