[CI] remove ipex for updating translator
intel/intel-xpu-backend-for-triton pull request #2230
Opened 2024-09-13 03:25 UTC by AshburnLee

Fix: https://github.com/intel/intel-xpu-backend-for-triton/issues/2214

`test-triton.sh` by default dose not execute softmax & gemm & attention benchmarks. I think those should be tested when updating translator. But there is a error in attention benchmark. Created a ticket to track it: https://github.com/intel/intel-xpu-backend-for-triton/issues/2228

2024-09-13 14:36 UTC, pbchekin commented
Please do a test run.

2024-09-13 15:38 UTC, leshikus reviewed
Is it included in any CI workflow? if not, I suggest adding the regular check

2024-09-18 09:08 UTC, AshburnLee commented
> Please do a test run.

Translator: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10917852785
Build and Test: see CI

2024-09-18 09:09 UTC, AshburnLee commented
> Is it included in any CI workflow? if not, I suggest adding the regular check

Add Benchmarks in Test and Run workflow

2024-09-18 15:27 UTC, leshikus approved these changes
Looks good

2024-09-18 15:29 UTC, pbchekin requested changes

2024-09-18 15:29 UTC, pbchekin commented on .github/workflows/build-test-reusable.yml
> +      - name: Run benchmarks
We do not need benchmarks in build-test, they are running daily in triton-benchmarks.

2024-09-19 05:57 UTC, AshburnLee commented on .github/workflows/build-test-reusable.yml
> +      - name: Run benchmarks
Done, run default test suits.

2024-09-19 14:53 UTC, pbchekin approved these changes

2024-09-20 01:16 UTC, merged