Increase `warmup` and `rep` for FA benchmark
intel/intel-xpu-backend-for-triton pull request #2256
Opened 2024-09-16 11:22 UTC by anmyachev

Closes #2255

2024-09-17 10:45 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +    warmup, rep = 150, 150
```suggestion
    warmup, rep = 200, 200
```

2024-09-17 20:28 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +    warmup, rep = 200, 200
```suggestion
    warmup, rep = 300, 300
```

2024-09-23 13:08 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +    warmup, rep = 300, 300
```suggestion
    warmup, rep = 10, 300
```

2024-09-23 15:08 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +    warmup, rep = 10, 300
```suggestion
    warmup, rep = 10, 200
```

2024-09-29 17:55 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +    warmup, rep = 10, 200
```suggestion
    warmup, rep = 10, 300
```

2024-09-30 10:15 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +    warmup, rep = 10, 200
```suggestion
    warmup, rep = 10, 300
```

2024-09-30 11:10 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py
> +    warmup, rep = 10, 300
```suggestion
    warmup, rep = 10, 400
```

2024-09-30 13:34 UTC, anmyachev commented
@ESI-SYD @chengjunlu geomean diff will most likely be less, I will write the exact figures here after https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11106696646/job/30855590713 is finished

2024-10-01 14:48 UTC, etiotto commented
> @ESI-SYD @chengjunlu geomean diff will most likely be less, I will write the exact figures here after https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11106696646/job/30855590713 is finished:
> 
> * Triton ADV: -5%
> * Triton DFT: -2%
> * Xetla: -8%
> 
> Are you aware of this effect where as the number of runs increases, the average time gets noticeably worse? I don't know what to do with this slowdown, but I still think the idea of ​​running multiple times (>3, only in this case "*-CV" column will not be `NaN`) is good (from the point of view of calculating the average).
> 
> cc @whitneywhtsang @etiotto

I think that when the warmup runs "too many times" the GPU may start heating up and then throttle the frequency down, so when the timed run start the performance is reduced. That means we are better off not increasing the rep/warmup to the point we see performance degradations in the benchmarks.

2024-10-01 15:02 UTC, etiotto requested changes
I do not think we should increase the number of repetition too much. Going from 10 too 600 repetitions is a huge increase. 

The kernel timing distribution should be a normal (gaussian) curve. We only need to run the benchmark enough times to approximate a gaussian "bell" curve. From https://www.scribbr.com/statistics/central-limit-theorem/#:~:text=By%20convention%2C%20we%20consider%20a,if%20the%20population%20is%20normal. looks like 30 is the number of reps we should use.

2024-10-01 15:07 UTC, whitneywhtsang commented
If we revert https://github.com/intel/intel-xpu-backend-for-triton/pull/2142, then rep is the number of iterations, then the problem of NaNs in CV is gone?

2024-10-01 18:24 UTC, anmyachev commented
> If we revert #2142, then rep is the number of iterations, then the problem of NaNs in CV is gone?

@whitneywhtsang Most likely yes. However, I made a change to make `do_bench` function more similar to the one used in upstream triton. If this is not necessary, I can revert some of the changes.

2024-10-01 18:32 UTC, whitneywhtsang commented
> > If we revert #2142, then rep is the number of iterations, then the problem of NaNs in CV is gone?
> 
> @whitneywhtsang Most likely yes. However, I made a change to make `do_bench` function more similar to the one used in upstream triton. If this is not necessary, I can revert some of the changes.

I also see the benefit of being more similar to upstream triton, but rep meaning the number of iterations is more intuitive IMO.

2024-10-07 14:38 UTC, etiotto commented
> > > If we revert #2142, then rep is the number of iterations, then the problem of NaNs in CV is gone?
> > 
> > 
> > @whitneywhtsang Most likely yes. However, I made a change to make `do_bench` function more similar to the one used in upstream triton. If this is not necessary, I can revert some of the changes.
> 
> I also see the benefit of being more similar to upstream triton, but rep meaning the number of iterations is more intuitive IMO.

I agree. To me "rep" should really mean the number of repetition of the kernel after warmup. I think we can diverge from upstream here, and then try to upstream our changes.

2024-10-14 16:43 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/benchmark_testing.py
> -    n_repeat = max(1, int(rep / estimate_ms))
There is no point in calculating the number of iterations through the expected time of one iteration, since the required number of iterations is requested by the user.

2024-10-14 16:44 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/benchmark_testing.py
> -    n_repeat = max(1, int(rep / estimate_ms))
There is no point in calculating the number of iterations through the expected time of one iteration, since the required number of iterations is requested by the user.

2024-10-14 16:47 UTC, anmyachev commented on benchmarks/triton_kernels_benchmark/benchmark_testing.py
> +    rep_time = n_repeat * estimate_ms
I translate the parameters into those that upstream (`triton_do_bench`) understands.

2024-10-14 18:13 UTC, anmyachev commented
> > > > If we revert #2142, then rep is the number of iterations, then the problem of NaNs in CV is gone?
> > > 
> > > 
> > > @whitneywhtsang Most likely yes. However, I made a change to make `do_bench` function more similar to the one used in upstream triton. If this is not necessary, I can revert some of the changes.
> > 
> > 
> > I also see the benefit of being more similar to upstream triton, but rep meaning the number of iterations is more intuitive IMO.
> 
> I agree. To me "rep" should really mean the number of repetition of the kernel after warmup. I think we can diverge from upstream here, and then try to upstream our changes.

@etiotto @whitneywhtsang ready for review

2024-10-14 21:12 UTC, whitneywhtsang approved these changes

2024-10-14 21:12 UTC, whitneywhtsang commented
Please update PR description.

2024-10-15 01:02 UTC, chengjunlu approved these changes

2024-10-15 14:35 UTC, etiotto approved these changes

2024-10-15 14:35 UTC, merged