1471: Generic SPIR-V Runner
intel/intel-xpu-backend-for-triton pull request #2258
Opened 2024-09-16 13:14 UTC by kballeda

This PR implements serialization/de-serialization of kernel arguments and meta data from Triton to SPIRVRunner. https://github.com/intel/intel-xpu-backend-for-triton/issues/1471

1. Kernel arguments and Torch Tensors are dumped from driver.py
2. Kernel launch configuration settings and tensor info is dumped in JSON format
3. SPIRVRunner is updated to utilize the JSON file/SPIR-V kernel binary and Tensors to reproduce the Triton results

2024-09-17 01:32 UTC, alexbaden requested changes
I made an initial pass and have a few comments. Please add a sample json file so the SPIRV Runner continues to build and run the tutorial kernel and tensor files that are checked into the repo.

2024-09-17 01:32 UTC, alexbaden commented on third_party/intel/backend/driver.py
> +            args_dict = kernel_meta_extractor(str(arg), args_dict)
Why do we need to serialize the args dictionary object as a string and then use regex to parse?

2024-09-17 01:32 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +#include "json.hpp"
Please work with @vlad-penkin to ensure this library has an acceptable license for us to use. Another option is simdjson, which is Apache 2 and can be automatically pulled in with cmake as opposed to vendoring: https://github.com/simdjson/simdjson/blob/master/doc/basics.md#using-simdjson-as-a-cmake-dependency

2024-09-17 01:32 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +          std::cerr << "Error: Loaded object is not a tensor " << std::endl;
I think we should just throw here, and we can catch all exceptions in `main`.

2024-09-17 01:32 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +struct argsDict {
suggest rename: `KernelArguments`

2024-09-17 01:32 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +argsDict parseArgsJson(const std::string& filename, const std::string& outtensorname) {
suggestion: move this to a static struct method, or we could make this the struct constructor

2024-09-17 01:32 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +        set_scalar_arg(cgh, i, sizeof(void *), params[i]);
I see that you cast params to `void*`  in the calling function - but I thought the type here needed to match the kernel function signature?

2024-09-17 05:39 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +#include "json.hpp"
Sure will follow up with @vlad-penkin offline

2024-09-18 15:06 UTC, kballeda commented
@alexbaden  Thanks for the review. I have made change, please take a look if you get a chance.

2024-09-20 12:11 UTC, kballeda commented on third_party/intel/backend/driver.py
> +            args_dict = kernel_meta_extractor(str(arg), args_dict)
Good suggestion 5th argument is pyObject which is accessed directly accessed.

2024-09-20 12:13 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +#include "json.hpp"
Thanks @vlad-penkin and @alexbaden  for suggestions. Yes now we download the library as part of build process.
https://github.com/intel/intel-xpu-backend-for-triton/blob/5805c71a91270d6ab9c0361d3be046894dbea92f/utils/SPIRVRunner/CMakeLists.txt#L10

2024-09-20 12:13 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +struct argsDict {
Done

2024-09-20 12:13 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +argsDict parseArgsJson(const std::string& filename, const std::string& outtensorname) {
Done

2024-09-20 13:11 UTC, alexbaden requested changes
Thanks for making the requested changes. I have done a more thorough review and made comments.

2024-09-20 13:11 UTC, alexbaden commented on third_party/intel/backend/driver.py
> +    dir_path = os.path.realpath('spirv_runner_data')
Let's make the path part of the environment variable that controls this. Something like `TRITON_XPU_DUMP_KERNEL_ARGS='/path/to/dump/directory`.

2024-09-20 13:11 UTC, alexbaden commented on third_party/intel/backend/driver.py
> +        debug_mode = os.getenv('TRITON_DEBUG')
See above - `TRITON_DEBUG` is for enabling asserts in Kernel code. Let's create a new environment variable controlling this specific behavior.

2024-09-20 13:11 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +        if (value.get<int>() == 1)
Can you explain what is happening here? I don't think I understand the code - with this kind of complex branching and magic numbers a comment is helpful.

2024-09-20 13:11 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +      auto value = it.value();
Looking at driver.py in the Intel backend there are quite a few more types we need to handle: 
https://github.com/intel/intel-xpu-backend-for-triton/blob/main/third_party/intel/backend/driver.py#L161

I don't think we can key this off the JSON type - we will likely have to examine the function signature and then map the arguments read from JSON to the appropriate type.

2024-09-20 17:35 UTC, kballeda commented on third_party/intel/backend/driver.py
> +    args_dict.update({'spv_name': f"{getattr(arg, 'name')}.spv"})
I played around with few tutorials/tests [add kernel, matmul, sort_kernel, flip, kernel.spv for dot flows etc] to find that .spv filename is based on kernel name.

2024-09-20 17:37 UTC, alexbaden commented on third_party/intel/backend/driver.py
> +    args_dict.update({'spv_name': f"{getattr(arg, 'name')}.spv"})
We need to prove it using the current Triton source for this approach to be acceptable.

2024-09-20 17:50 UTC, kballeda commented on third_party/intel/backend/driver.py
> +        if type(arg).__name__ == "KernelMetadata":
In this case KernelMetaData/Tensors are objects residing in arg not declared within function, so it results in syntactical error. We opted for string comparison between them by picking type(arg).__name__ and == operator.

2024-09-24 11:56 UTC, victor-eds reviewed
Can we avoid adding a dependency on an external project? Can we use LLVM project JSON/YAML whatever built-in library instead?

2024-09-25 12:57 UTC, kballeda commented on third_party/intel/backend/driver.py
> +    args_dict.update({'spv_name': f"{getattr(arg, 'name')}.spv"})
Please find the triton source for this approach,

1. https://github.com/intel/intel-xpu-backend-for-triton/blob/6955edf097b076e2154cd7a4d85c68686d76a1e2/python/triton/compiler/compiler.py#L302
2. https://github.com/intel/intel-xpu-backend-for-triton/blob/6955edf097b076e2154cd7a4d85c68686d76a1e2/python/triton/compiler/compiler.py#L306

Prints:
```file_name: compile() -  sort_kernel```
ir_filename:  sort_kernel.ttir sort_kernel ttir
ir_filename:  sort_kernel.ttgir sort_kernel ttgir
ir_filename:  sort_kernel.llir sort_kernel llir
```ir_filename:  sort_kernel.spv sort_kernel spv```
```binary_ext:  spv```

2024-09-25 15:30 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +        if (value.get<int>() == 1)
Line256: -> Iterate over json data related to kernel arguments 
Line257-263: Skip constant values (example: 1) if not set the scalar kernel argument 
Line265: Corresponds to setting kernel arguments of tensors

Original sycl_kernel_launch from driver.py checks for constant values and skips them while setting SYCL kernel arguments
https://github.com/intel/intel-xpu-backend-for-triton/blob/5805c71a91270d6ab9c0361d3be046894dbea92f/third_party/intel/backend/driver.py#L333


Following is the dump of constants from python, it basically indicates that the constant value such as "1" at a particular argument index.
```make_launcher constants:  {1: 1, 4: 1, 8: 1, 11: 1, 12: 64, 13: 64, 14: 32, 15: False, 16: False, 17: False, 18: 'tf32', 19: False, 20: False, 21: True, 22: True, 23: triton.language.int8}```

Following is the corresponding signature of the kernel from python (Identical to Json dump), here based on constant value list above 1,4, 8,11 entries are skipped.
```make_launcher signature:  {0: '*i8', 1: 'i32', 2: 'i32', 3: '*i8', 4: 'i32', 5: 'i32', 6: '*i8', 7: 'i32', 8: 'i32', 9: '*i32', 10: 'i32', 11: 'i32'}```

2024-09-26 14:07 UTC, FMarno commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +#if _DEBUG
That example is 4 years old now. I think the default exception hander is probably very suitable for the task https://github.com/intel/llvm/blob/2c0a2587a5fdda30d12238625b8577bcbb90e642/sycl/include/sycl/exception_list.hpp#L58.
Either way I'm fine ignoring it for now.

2024-09-26 14:28 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    assert(narg == expected_num_params);
The assert needs to be evaluated before the arguments are set. Basically we want to check that the number of params passed in via the JSON object matches the SPV function signature. One of the design goals here is to match the launcher code in `driver.py` as close as possible with the goal of eventually unifying as much code as possible between both files: https://github.com/intel/intel-xpu-backend-for-triton/blob/main/third_party/intel/backend/driver.py#L328

2024-09-27 09:52 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  auto spirv = read_spirv(tritonArgDict.spv_name);
we would like to keep it for readability as the original version follows this.

2024-09-27 09:52 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    std::cout << "Help: " << std::endl;
Done

2024-09-27 09:52 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    spv_name = jsonData.value("spv_name", " ");
Done

2024-09-27 09:54 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +static inline void set_scalar_arg(sycl::handler &cgh, int index,
This is used for scalar arguments in latest version. As Alex mentioned we would like to maintain identical flow with sycl_kernel_launch. Thanks for the review !

2024-09-27 10:04 UTC, kballeda commented
> Can we avoid adding a dependency on an external project? Can we use LLVM project JSON/YAML whatever built-in library instead?

Thanks for the review and suggestion! We will look into it post this PR.

2024-09-27 10:19 UTC, FMarno commented
> > Can we avoid adding a dependency on an external project? Can we use LLVM project JSON/YAML whatever built-in library instead?
> 
> Thanks for the review and suggestion! We will look into it post this PR.

Adding a dependency is a bit of a burden for other users of the repo. I think it would be best to reconsider this before merging.

2024-09-27 10:40 UTC, FMarno commented
I think the layout of the json data is complicating the code, leading to awkward parts like looking for regex patterns. Instead of arguments as extra keys in a flat object, why not an array of arguments? e.g.
```
{
  "gridX": 97,
  "gridY": 1,
  "gridZ": 1,
  "num_warps": 4,
  "threads_per_warp": 32,
  "shared_memory": 0,
  "kernel_name": "add_kernel",
  "spv_name": "add_kernel.spv",
  "kernel_args" : [["tensor", "tensor_9.pt", "torch.float32"], ["tensor", "tensor_10.pt", "torch.float32"], ["tensor", "tensor_11.pt", "torch.float32"], ["int", "intArg_12", 98432]]
}
```
In this example I've gone with representing an argument as an array of [type_str, args...], but feel free to change that about to make the parsing easiest.

2024-09-27 11:43 UTC, victor-eds commented
Sorry, I thought we were already linking against LLVM. As that isn't the case, this header-only library dependency doesn't hurt for now IMO.

2024-09-27 12:54 UTC, kballeda commented
> I think the layout of the json data is complicating the code, leading to awkward parts like looking for regex patterns. Instead of arguments as extra keys in a flat object, why not an array of arguments? e.g.
> 
> ```
> {
>   "gridX": 97,
>   "gridY": 1,
>   "gridZ": 1,
>   "num_warps": 4,
>   "threads_per_warp": 32,
>   "shared_memory": 0,
>   "kernel_name": "add_kernel",
>   "spv_name": "add_kernel.spv",
>   "kernel_args" : [["tensor", "tensor_9.pt", "torch.float32"], ["tensor", "tensor_10.pt", "torch.float32"], ["tensor", "tensor_11.pt", "torch.float32"], ["int", "intArg_12", 98432]]
> }
> ```
> 
> In this example I've gone with representing an argument as an array of [type_str, args...], but feel free to change that about to make the parsing easiest.

Thanks for the review, will consider this as a cleanup activity post this PR.

2024-09-27 14:02 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +      auto value = it.value();
As part of the sycl_kernel_launch, we were mapping the tensors as void* and kernel arguments to respective types. 
https://github.com/intel/intel-xpu-backend-for-triton/blob/659470b340e50376d977b4b241bb6b4d1da0c861/third_party/intel/backend/driver.py#L331

Following is the typical dump at set_scalar_args() for test_dot [Tensors are of Pv type and scalar args are i]:

```
Argument-0 = Pv Size: 8
Argument-1 = i Size: 4
Argument-2 = Pv Size: 8
Argument-3 = i Size: 4
Argument-4 = Pv Size: 8
Argument-5 = i Size: 4
Argument-6 = Pv Size: 8
Argument-7 = i Size: 4
```
Based on my search and @whitneywhtsang also confirmed that none of the tests/tutorials pass scalar_arg type other than int32_t at the moment. In order to get the SPIRVRunner closer to sycl_kernel_launch, implemented an approach to map the kernel scalar signature types to respective data types similar to ty_to_cpp.

Logic that processes SYCL argument setup for tensor/sclar arguments,

https://github.com/kballeda/intel-xpu-backend-for-triton/blob/0e957302c53d1976f6019b936cfe318f29c147f8/utils/SPIRVRunner/SPIRVRunner.cpp#L297

Map Json scalar type to kernel scalar signature,

https://github.com/kballeda/intel-xpu-backend-for-triton/blob/0e957302c53d1976f6019b936cfe318f29c147f8/utils/SPIRVRunner/SPIRVRunner.cpp#L222

2024-09-27 14:03 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    return reinterpret_cast<void *>(t.data_ptr());
@alexbaden : This change is part of original code not done as part of this PR.

2024-09-30 18:40 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    return reinterpret_cast<void *>(t.data_ptr());
I am fine with it - converting a typed ptr to a typeless ptr should be well defined and supported.

2024-09-30 19:09 UTC, alexbaden requested changes
The change to process the signature in the C++ code is an improvement, but it is a step back in the Python side. We need to unify into a single file. Here's a suggested JSON syntax to start from (note the arguments array with nested dicts): 
```
{
    "gridX": 97,
    "gridY": 1,
    "gridZ": 1,
    "num_warps": 4,
    "threads_per_warp": 32,
    "shared_memory": 0,
    "kernel_name": "add_kernel",
    "spv_name": "add_kernel.spv",
    "arguments": [
        {
            "name": "tensor_9",
            "type": "tensor",
            "dtype": "torch.float32",
            "ctype": "*fp32"
        },
        {
            "name": "scalarArg_12",
            "type": "scalar",
            "value": 98432
        }
    ]
}
```
We should be able to encode all the information we need without regular expressions or even string processing.

2024-09-30 19:09 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    for (auto it = jsonData.begin(); it != jsonData.end(); ++it) {
Why not store the tensors in their own array in the JSON, so this regex is not necessary?

2024-09-30 19:09 UTC, alexbaden commented on third_party/intel/backend/driver.py
> +def serialize_signature(constants, signature):
The signature and the args data need to be part of the same file. I think that would also simplify the type checking in the args code above.

2024-10-01 01:31 UTC, kballeda commented
> The change to process the signature in the C++ code is an improvement, but it is a step back in the Python side. We need to unify into a single file. Here's a suggested JSON syntax to start from (note the arguments array with nested dicts):
> 
> ```
> {
>     "gridX": 97,
>     "gridY": 1,
>     "gridZ": 1,
>     "num_warps": 4,
>     "threads_per_warp": 32,
>     "shared_memory": 0,
>     "kernel_name": "add_kernel",
>     "spv_name": "add_kernel.spv",
>     "arguments": [
>         {
>             "name": "tensor_9",
>             "type": "tensor",
>             "dtype": "torch.float32",
>             "ctype": "*fp32"
>         },
>         {
>             "name": "scalarArg_12",
>             "type": "scalar",
>             "value": 98432
>         }
>     ]
> }
> ```
> 
> We should be able to encode all the information we need without regular expressions or even string processing.

@alexbaden  : Thanks for the suggestion, we will explore this as part of this issue https://github.com/intel/intel-xpu-backend-for-triton/issues/2389

2024-10-01 01:38 UTC, kballeda commented on third_party/intel/backend/driver.py
> +    dir_path = os.getenv('TRITON_XPU_DUMP_KERNEL_ARGS')
Please refer : 
TRITON_XPU_DUMP_KERNEL_ARGS: https://github.com/intel/intel-xpu-backend-for-triton/pull/2258#discussion_r1768584272  -> This covers path of dumps one of the review comments

SPIRV_RUNNER_ARGS: https://github.com/intel/intel-xpu-backend-for-triton/pull/2258#discussion_r1768585648
This was created as per the earlier review comment it was recommended not to use TRITON_DEBUG and introduce a new variable.

2024-10-01 01:38 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    for (auto it = jsonData.begin(); it != jsonData.end(); ++it) {
This issue covers this, https://github.com/intel/intel-xpu-backend-for-triton/issues/2389

2024-10-01 01:40 UTC, alexbaden commented on third_party/intel/backend/driver.py
> +    dir_path = os.getenv('TRITON_XPU_DUMP_KERNEL_ARGS')
They can be the same flag. 

`os.getenv("TRITON_XPU_DUMP_SPIRV_KERNEL_ARGS", NONE)`

2024-10-01 01:43 UTC, kballeda commented on third_party/intel/backend/driver.py
> +def serialize_signature(constants, signature):
Please elaborate more on this

2024-10-01 05:53 UTC, kballeda commented on third_party/intel/backend/driver.py
> +            args_dict.update({tensor_name: str(tensor_type)})
Good catch, looks like it's missed out.

2024-10-01 14:16 UTC, etiotto approved these changes
This is a good improvement as it allows to create a reproducer pretty cleanly. Thanks!

2024-10-04 19:53 UTC, kballeda commented
@alexbaden Thanks for the review.   https://github.com/intel/intel-xpu-backend-for-triton/issues/2389 updated as requested, also more improvements added. Please take a look. 

**JSON:**

1. We have restructured the JSON arguments format, transitioning from a flat to a nested one.
2. We have eliminated the need for the kernel signature JSON dump (signature.json) as an input, streamlining the process by reducing the number of required JSON input files to one.

**SPIRV Runner:**

To enhance the user experience of SPIRV-Runner, we have streamlined the data management process. All SPIRV-related files—including .pt, .spv, and .json—are now automatically exported from Triton to a designated directory specified by the TRITON_XPU_DUMP_SPIRV_KERNEL_ARGS environment variable. SPIRV-Runner then retrieves its input data directly from this specified location. If the environment variable is not set, SPIRV-Runner will default to using the current directory for its input data, maintaining the existing workflow.

1. Previously, users had to manually select the .spv file from the Triton cache directory. Now, as part of the enhanced Triton functionality, the .spv file is automatically saved to a user-defined path set in an environment variable, along with tensors and JSON files.
2. Users can now execute Triton kernels and use the SPIRV Runner without interruption. The output file cpp_outs.pt is also conveniently saved to the path specified by the environment variable.
3. The SPIRV Runner has been updated to eliminate the need for regular expression operations. It now accesses nested argument data directly from JSON files.
4. To optimize memory usage, the SPIRV Runner no longer uses vectors to temporarily store JSON data during processing. This change reduces redundant memory consumption.
5. Important: Users are advised to clear the Triton cache before running kernels at the Triton level. This precaution ensures that the .spv file is correctly dumped to the path designated by the environment variable.

**Testing and Known Issues:**

The file test_core.py, specifically the test_dot function, serves to evaluate the stability of the SPIRVRunner. It systematically executes 432 distinct test combinations, each designed to assess a variety of data types and configuration permutations. Upon completion of each test, a log file is generated. This log file determines the success or failure of the test by automatically comparing the output tensor from Triton with the output from SPIRVRunner, denoted as cpp_outs.pt. The test outcomes are recorded as Boolean values, with True indicating a successful result and False indicating a failure.

Total Tests:

```
intel-xpu-backend-for-triton$ tail -n +2 spirvrunner_tests.sh | wc -l
432
```

Test Results:
Each test result is either True/False, Output tensors of Triton/SPIRV-Runner compared. 

| Total Tests | Pass   | Fail  | Crash/Unknown
|------------|------------|------------|----------|
| 432 | 370| 60| 2 |


```
intel-xpu-backend-for-triton$ python3 find_trufalse.py 
True: 370
False: 60
```

The log records two tests that concluded with the error message "Argument type doesn't match." It appears that the discrepancy is related to the data types, specifically float8e5 and float8e4nv.
```

python/test/unit/language/test_core.py::test_dot[1-128-128-64-4-False-False-chain-dot-ieee-float8e5-float32-1] PASSED       [100%]

======================================================= 1 passed in 24.35s ========================================================
Running on device: Intel(R) Data Center GPU Max 1100
Read 401872 byte kernel.
Loaded kernel with 0 registers and 51840 register spills.
Error: Argument type doesnt match

========================================================

python/test/unit/language/test_core.py::test_dot[1-128-128-64-4-False-False-chain-dot-ieee-float8e4nv-float32-1] PASSED     [100%]

======================================================= 1 passed in 59.73s ========================================================
Running on device: Intel(R) Data Center GPU Max 1100
Read 640568 byte kernel.
Loaded kernel with 0 registers and 77440 register spills.
Error: Argument type doesnt match

```

The table below provides a summary of the 60 tests that failed.

| Count | Reason   |  Remarks
|------------|------------|------------|
| 45 | add-matrix, add-row, add-cols| Add performed on torch ref, compare with torch |
| 15  | Transpose operation | Results are identical but one of them transposed |

Output dump below highlights the failure of 15 cases that does transpose operation.
Here SPIRVRunner output (cpp_outs.pt) is transpose of tensor_3.pt (Triton dump)

```
intel-xpu-backend-for-triton$ python3 ~/read.py ./tt_spirv_dumps/cpp_outs.pt 
  data = torch.load(file_path)
tensor([[-0.0262, -0.1303, -0.0215,  ..., -0.1701,  0.0044,  0.0392],
        [ 0.1002,  0.1521, -0.0814,  ...,  0.0726, -0.0453,  0.0364],
        [-0.1304, -0.1141,  0.0249,  ..., -0.0550,  0.0398,  0.0138],
        ...,
        [ 0.0904,  0.0657,  0.0302,  ..., -0.0479, -0.1151, -0.0072],
        [-0.2494, -0.1439, -0.0598,  ..., -0.0324,  0.0458, -0.0781],
        [ 0.1651,  0.0746,  0.0435,  ..., -0.1000, -0.0229,  0.0777]])
intel-xpu-backend-for-triton$ python3 ~/read.py ./tt_spirv_dumps/tensor_3.pt 
  data = torch.load(file_path)
tensor([[-0.0262,  0.1002, -0.1304,  ...,  0.0904, -0.2494,  0.1651],
        [-0.1303,  0.1521, -0.1141,  ...,  0.0657, -0.1439,  0.0746],
        [-0.0215, -0.0814,  0.0249,  ...,  0.0302, -0.0598,  0.0435],
        ...,
        [-0.1701,  0.0726, -0.0550,  ..., -0.0479, -0.0324, -0.1000],
        [ 0.0044, -0.0453,  0.0398,  ..., -0.1151,  0.0458, -0.0229],
        [ 0.0392,  0.0364,  0.0138,  ..., -0.0072, -0.0781,  0.0777]])
```

Raw test script,

<details>
<summary>spirvrunner_tests.sh</summary>

```

#!/bin/bash
rm -rf ./tt_spirv_dumps ~/.triton/cache && python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_dot[1-64-64-64-4-False-False-none-tf32-float32-float32-1]  && ./utils/SPIRVRunner/build/SPIRVRunner tensor_3 &&  python3 tensor_compare.py &> log_0
rm -rf ./tt_spirv_dumps ~/.triton/cache && python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_dot[1-64-64-64-4-False-False-none-tf32x3-float32-float32-1]  && ./utils/SPIRVRunner/build/SPIRVRunner tensor_3 &&  python3 tensor_compare.py &> log_1
rm -rf ./tt_spirv_dumps ~/.triton/cache && python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_dot[1-64-64-64-4-False-False-none-ieee-float16-float16-1]  && ./utils/SPIRVRunner/build/SPIRVRunner tensor_3 &&  python3 tensor_compare.py &> log_2
rm -rf ./tt_spirv_dumps ~/.triton/cache && python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_dot[1-64-64-64-4-False-False-none-ieee-float16-float32-1]  && ./utils/SPIRVRunner/build/SPIRVRunner tensor_3 &&  python3 tensor_compare.py &> log_3
rm -rf ./tt_spirv_dumps ~/.triton/cache && python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_dot[1-64-64-64-4-False-False-none-ieee-float32-float32-1_0]  && ./utils/SPIRVRunner/build/SPIRVRunner tensor_3 &&  python3 tensor_compare.py &> log_4
rm -rf ./tt_spirv_dumps ~/.triton/cache && python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_dot[1-64-64-64-4-False-False-trans-tf32-float32-float32-1]  && ./utils/SPIRVRunner/build/SPIRVRunner tensor_3 &&  python3 tensor_compare.py &> log_5
rm -rf ./tt_spirv_dumps ~/.triton/cache && python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_dot[1-64-64-64-4-False-False-trans-tf32x3-float32-float32-1]  && ./utils/SPIRVRunner/build/SPIRVRunner tensor_3 &&  python3 tensor_compare.py &> log_6
rm -rf ./tt_spirv_dumps ~/.triton/cache && python3 -m pytest --verbose --device xpu python/test/unit/language/test_core.py::test_dot[1-64-64-64-4-False-False-trans-ieee-float16-float16-1]  && ./utils/SPIRVRunn [...]

2024-10-04 19:56 UTC, kballeda commented
> This is a good improvement as it allows to create a reproducer pretty cleanly. Thanks!

@etiotto  Thank you very much for the review and approving!

2024-10-07 08:54 UTC, victor-eds reviewed
LGTM after NITs

2024-10-07 08:54 UTC, victor-eds commented on python/triton/compiler/compiler.py
> +        os.makedirs(spv_path)
```suggestion
    os.makedirs(spv_path, exist_ok=True)
```
Equivalent, right?

2024-10-07 08:54 UTC, victor-eds commented on python/triton/compiler/compiler.py
> +    spv_name = f"{spv_path}/{file_name}.{ext}"
```suggestion
    spv_name = os.path.join(spv_path, f"{file_name}.{ext}")
```

`os.path.join` is better

2024-10-07 08:54 UTC, victor-eds commented on python/triton/compiler/compiler.py
> +def triton_spirv_dump(data, file_name, ext):
```suggestion
def triton_spirv_dump(data, file_name):
    ext = "spv"
```
Isn't it always `"spv"`?

2024-10-07 08:54 UTC, victor-eds commented on third_party/intel/backend/driver.py
> +        if type(arg).__name__ == "Tensor":
Why not using `isinstance` in these two `if` statements too?

2024-10-07 13:53 UTC, etiotto commented
@kballeda please address the nits from @victor-eds

2024-10-08 12:12 UTC, kballeda commented on third_party/intel/backend/driver.py
> +        if type(arg).__name__ == "Tensor":
@victor-eds  - Thanks for the review, I have updated tensor check, as far as KernelMetadata is concerned it is constructed from a json and its type is unknown, let me know if you have any ideas how we can use isinstance in this case.

2024-10-08 14:06 UTC, victor-eds approved these changes

2024-10-09 05:21 UTC, kballeda commented
@victor-eds Thank you very much for review and approving!

2024-10-09 12:44 UTC, alexbaden requested changes
I have completed a review of all the new changes. Let's break out any additional features into subsequent PRs (including splitting the feature to copy the spv binary) so we can resolve the outstanding issues with this PR and get it merged. Thanks!

2024-10-09 12:44 UTC, alexbaden commented on third_party/intel/backend/driver.py
> +def find_latest_spv_file(cache_dir):
This assumes that the user wants to run a SPIR-V file that is not already present in the cache when the kernel is executed. I don't think this will always be the case. 

Please remove this code and the copy_spv_binary code to a second PR, I want to discuss the design of this functionality and we should not hold up this initial PR for additional features.

2024-10-09 12:44 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +      throw std::runtime_error("Triton Spirv dump path doesnt exist");
I think it looks weird to not have `{}` around the else, even if it is just one line.

2024-10-09 12:44 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  KernelArguments(const std::string &outtensorname) {
Why is it necessary to take the output tensor name here? How do we handle multiple outputs?

2024-10-09 12:44 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    auto env_path = std::getenv("TRITON_XPU_DUMP_SPIRV_KERNEL_ARGS");
I think it is preferable to specify the `args_data.json` file path explicitly rather than read it from the env variable. Remember, users of this program may not have a local Triton installation and would have no need to set the env variable (e.g. IGC team debugging an issue).

2024-10-10 05:44 UTC, kballeda commented on third_party/intel/backend/driver.py
> +def find_latest_spv_file(cache_dir):
Removed

2024-10-10 06:02 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +      throw std::runtime_error("Triton Spirv dump path doesnt exist");
added {}

2024-10-10 06:10 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    auto env_path = std::getenv("TRITON_XPU_DUMP_SPIRV_KERNEL_ARGS");
Just to clear the things, following code would do two things

1. As we are dumping all the data into path set in TRITON_XPU_DUMP_SPIRV_KERNEL_ARGS it checks for its existence - Our setup if it is present it goes with that otherwise
2. It picks current directory as the path - maintaining existing SPIRVRunner flow which is also applicable to IGC Team where we just place all files in flat in a directory and share with them. 

```
auto env_path = std::getenv("TRITON_XPU_DUMP_SPIRV_KERNEL_ARGS");
 spirv_dump_dir = (env_path != nullptr)
                         ? env_path
                         : std::filesystem::current_path().string();
    if (std::filesystem::exists(spirv_dump_dir)) {
       std::ifstream file(spirv_dump_dir + "/args_data.json");
```

2024-10-10 06:22 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  KernelArguments(const std::string &outtensorname) {
In the existing SPIRVRunner workflow, only a single output is supported. This pull request maintains that functionality but introduces the ability to generically determine the type of the output tensor based on user input. 
 
 How do we handle multiple outputs?
 [Kali]: We need to plan this in future based on use-case, please share if you know any test that produces two or more outputs. 

Reference: 
https://github.com/intel/intel-xpu-backend-for-triton/blob/a2a31008a1f28500bdc16468ffaac66d2913c5a5/utils/SPIRVRunner/SPIRVRunner.cpp#L228

https://github.com/intel/intel-xpu-backend-for-triton/blob/a2a31008a1f28500bdc16468ffaac66d2913c5a5/utils/SPIRVRunner/SPIRVRunner.cpp#L248

https://github.com/intel/intel-xpu-backend-for-triton/blob/a2a31008a1f28500bdc16468ffaac66d2913c5a5/utils/SPIRVRunner/SPIRVRunner.cpp#L258

2024-10-11 13:27 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  KernelArguments(const std::string &outtensorname) {
> This pull request maintains that functionality but introduces the ability to generically determine the type of the output tensor based on user input.

I don't understand, isn't the type of the output set by the function signature and encoded in the json arguments file?

Before, multiple outputs could be supported by modifying the file. I am not asking you to explicitly support multiple outputs here, but the approach of taking the output tensor name as an argument does not easily generalize (vs say taking the arguments json file as the argument here).

2024-10-14 07:52 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  KernelArguments(const std::string &outtensorname) {
Thanks for the review, I believe there is some confusion here. I have illustrated this in a diagram

2024-10-14 15:34 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  KernelArguments(const std::string &outtensorname) {
> Consider this example (from Tutorial 5 - Layer Norm):

> with the current code on main, I can manually (with some effort) create a `SPIRVRunner` that runs this code. I don't see how I can do that after we merge this PR. So, I think we need to handle that (at least allow a way for the user to manually support such a thing).


I attempted this example and made the following observations: I generated the JSON file and expanded my previous diagram to illustrate the behavior of the SPIR-V runner

### Running the Triton tutorial to generate JSON and .pt data : 

![softmax_layer_ttrun](https://github.com/user-attachments/assets/64eb53cf-138d-441f-ba58-bf2f2f0b874a)

Kernel explored here is - `_layer_norm_fwd_fused` same as the dump that you shared above

![softmax_layer_alex](https://github.com/user-attachments/assets/cc5d4e04-a25d-4c9e-a028-bdc702dc5514)

### Illustration of execution flow:

![softmax_layer_full](https://github.com/user-attachments/assets/422c53a1-7e6c-4860-b1ad-efb60330f321)

### Results:

I found that this tutorial runs smoothly without manual intervention. You can find the output logs here, which compare the Triton output with the SPIR-V runner output.


![softmax_layer_output_toshare](https://github.com/user-attachments/assets/b377daf1-d75d-4c8e-baee-ec3c47285bb6)

> If I understand you correctly the problem you have is that there is no way to identify whether a tensor is an output vs an input from the args list, so you don't know what to copy back and write out to disk. It is an interesting problem.

Perfect! You understood correctly. I'm glad the diagram was helpful

2024-10-14 16:01 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  KernelArguments(const std::string &outtensorname) {
I see - the parameter `outtensorname` is the selected tensor to copy back to the host and write to disk. 

Can you explain how you generated `tensor_1.pt` from Triton? Did that come from the arg dumps or did you manually pull that file from Triton's runtime?

2024-10-14 16:07 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  KernelArguments(const std::string &outtensorname) {
To get triton final output (tensor_1.pt) we need to call the serialize_args() part after launch(). 
Note: In recent reviews we moved it before launch().

2024-10-14 16:28 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  KernelArguments(const std::string &outtensorname) {
Thanks, that is what I was wondering. 

Please update the readme to clarify that `< Output Tensor Title >` is actually a selected tensor to copy back to CPU and write to disk, and that the name needs to match the `tensor_` name and number from the JSON file.

2024-10-15 00:54 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  KernelArguments(const std::string &outtensorname) {
Done

2024-10-15 12:48 UTC, alexbaden approved these changes

2024-10-15 12:48 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +      file.close();
Note: this should not be necessary, `ifstream` supports `RAII`.

2024-10-15 12:48 UTC, alexbaden commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    for (auto &item : triton_args.jsonData["argument_list"]) {
I think the first followup should be to put this logic into the `KernelArguments` struct, so the launcher can iterate through arguments generically (either using an API that moves all this logic into `KernelArguments`, or preferably by parsing the JSON into structured objects in `KernelArguments`). There should only be one place where we parse the JSON datastructure and serialize it into objects that structure the data for the operation(s) we want to do.

2024-10-15 12:49 UTC, merged

2024-10-15 13:47 UTC, kballeda commented
@alexbaden  Thank you very much for the review and approval !