Add Stream K and Split K to regular CI
intel/intel-xpu-backend-for-triton pull request #2313
Opened 2024-09-23 10:47 UTC by LiyangLingIntel

This PR will be ready when https://github.com/intel/intel-xpu-backend-for-triton/pull/2312 is landed.

2024-09-27 11:20 UTC, anmyachev commented on .github/workflows/triton-benchmarks.yml
> +
Maybe it would be better to put this in a separate step?

2024-09-27 14:30 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> +          # Simply run the split-k benchmark to check correctness
As it is only for functional, let's only run splitk at the out of box step, the previous step.

2024-09-27 14:30 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> +          python gemm_streamk_benchmark.py --reports $REPORTS
Can you please check if any of the environment variables make a difference in performance?
If no difference, please move it to the previous step.
If there is a difference, please add it also to the previous step.

2024-09-27 17:26 UTC, etiotto requested changes

2024-09-27 17:26 UTC, etiotto commented on .github/workflows/triton-benchmarks.yml
> +          # Simply run the split-k benchmark to check correctness
why do we need this step at all ? The bmk should self verify whether we use it for reporting performance numbers or not.

2024-09-27 17:26 UTC, etiotto commented on .github/workflows/triton-benchmarks.yml
> +          python gemm_streamk_benchmark.py --reports $REPORTS
We should report performance out-of-box. Remove all environment variables and IGC flags.

2024-09-27 17:27 UTC, etiotto submitted a review, later dismissed

2024-09-27 17:27 UTC, etiotto commented on benchmarks/triton_kernels_benchmark/gemm_streamk_benchmark.py
> +        # benchmark_suit.assert_close(xetla_fn(), torch_fn(), atol=1e-4, rtol=1.0, err_msg='xetla to torch')
I do not see much value in adding a benchmark that does not verify correctly.

2024-09-30 16:48 UTC, etiotto commented on .github/workflows/triton-benchmarks.yml
> +          python gemm_streamk_benchmark.py --reports $REPORTS
After offline discussion with @whitneywhtsang I think we can:
  - add the split-k and stream-k bmks to out-of-box section (with no env. variables at all)
  - add stream-k with env. variables in this section iff it has better performance than the default one

2024-09-30 16:48 UTC, etiotto commented on benchmarks/triton_kernels_benchmark/gemm_streamk_benchmark.py
> +        # benchmark_suit.assert_close(xetla_fn(), torch_fn(), atol=1e-4, rtol=1.0, err_msg='xetla to torch')
After revisiting this issue I think is reasonable to do this: 
  1. ensure the Triton result matches the PyTorch result (done already at line 280)
  2. open a ticket to track the xeTLA precision issue and temporarily comment out this verification step (once the ticket is fixed we can then uncomment this line)

2024-10-01 00:23 UTC, whitneywhtsang commented on benchmarks/triton_kernels_benchmark/gemm_streamk_benchmark.py
> +        xetla_fn = lambda: func(a, b, c, acc, cnt)
We should call the streamk implementation, instead of regular GEMM. FYI @ESI-SYD

2024-10-01 00:50 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> +
moved splitk to a separate step

2024-10-01 01:26 UTC, whitneywhtsang commented on benchmarks/triton_kernels_benchmark/gemm_benchmark.py
> -            [1, 3072, 4096, 3072],  # FIXME: Remove this case when gemm_streamk_benchmark works
streamk performance is currently 100TFlops, which is smaller than generic gemm performance of 216TFlops, should not yet remove this shape here.

2024-10-01 01:40 UTC, whitneywhtsang commented on benchmarks/triton_kernels_benchmark/gemm_streamk_benchmark.py
> +        # benchmark_suit.assert_close(xetla_fn(), torch_fn(), atol=1e-4, rtol=1.0, err_msg='xetla to torch')
moved them to separate steps with out of box

2024-10-01 01:41 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> +          # Simply run the split-k benchmark to check correctness
only out of box now.

2024-10-01 01:41 UTC, whitneywhtsang commented on .github/workflows/triton-benchmarks.yml
> +          python gemm_streamk_benchmark.py --reports $REPORTS
only out of box now, until streamk performance is improved.

2024-10-01 01:42 UTC, whitneywhtsang commented on benchmarks/triton_kernels_benchmark/gemm_benchmark.py
> -            [1, 3072, 4096, 3072],  # FIXME: Remove this case when gemm_streamk_benchmark works
added back.

2024-10-01 01:43 UTC, whitneywhtsang commented on benchmarks/triton_kernels_benchmark/gemm_streamk_benchmark.py
> +        xetla_fn = lambda: func(a, b, c, acc, cnt)
Created https://github.com/intel/intel-xpu-backend-for-triton/issues/2390 to track

2024-10-01 02:00 UTC, whitneywhtsang approved these changes

2024-10-01 14:42 UTC, etiotto approved these changes

2024-10-01 16:40 UTC, merged