[BACKEND] Added sycl backend support
intel/intel-xpu-backend-for-triton pull request #234
Opened 2024-01-11 04:48 UTC by Sarbojit2019

1. Change brings SYCL backend used in troch. This will help triton workloads get sync with torch. 
2. Change is addressing open issue #150

2024-01-12 07:43 UTC, Sarbojit2019 commented
Current error/failures look to me as environmental issues. @vlad-penkin @whitneywhtsang Can any of maintainer please confirm?

![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/52556743/47f3629d-77e9-4a43-a6dd-06e784cccab0)

2024-01-12 16:20 UTC, whitneywhtsang commented
> Current error/failures look to me as environmental issues. @vlad-penkin @whitneywhtsang Can any of maintainer please confirm?
> 
> ![image](https://private-user-images.githubusercontent.com/52556743/296163895-47f3629d-77e9-4a43-a6dd-06e784cccab0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMzNTEsIm5iZiI6MTcwNTA3MzA1MSwicGF0aCI6Ii81MjU1Njc0My8yOTYxNjM4OTUtNDdmMzYyOWQtNzdlOS00YTQzLWE2ZGQtMDZlNzg0Y2NjYWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MjQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwM2M0MDE1NDViZWIzNTQ4NzdkNzhlOGNlNjNjYjJmNjNlOTlkY2ZlYmFmYmJiYjQ0NTAwY2RiZDM5N2EzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uqUICfBT90bOohoVz9RFAyF59U-ol40NMoLVM96-C0g)

It is no longer failing with `libmkl_sycl_blas.so.4`, the new failure looks like
```
>       self.context = mod.init_context(torch.xpu.current_stream().sycl_queue)
E       ValueError: PyCapsule_GetPointer called with invalid PyCapsule object

/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/triton/runtime/driver.py:792: ValueError
```

2024-01-12 16:38 UTC, Sarbojit2019 commented
Test failures are due to change in function signature between ipex1.13 vs ipex2.0. We should at least move to ipex2.0 soon.

**ipex 2.0** https://github.com/intel/intel-extension-for-pytorch/blob/release/xpu/2.0.110/intel_extension_for_pytorch/xpu/streams.py#L17C43-L17C43

**ipex1.13 :**  https://github.com/intel/intel-extension-for-pytorch/blob/release/xpu/1.13.120/intel_extension_for_pytorch/xpu/streams.py#L12

2024-01-17 22:06 UTC, whitneywhtsang commented
@Sarbojit2019 Now that https://github.com/intel/intel-xpu-backend-for-triton/pull/239 is merged, please rebase your PR. 
A general comment, don't think we need to keep the old code IMO, as we can get a copy from git log if needed.

2024-01-18 14:05 UTC, kurapov-peter requested changes
The PR needs some general cleanup, but I'd like us to explicitly articulate how we solve the problem and what are the next steps.

We bring in the sycl runtime, get the necessary handles from pytorch to queues, device, etc, and generate the same kernel/module via L0. Finally, we bundle the kernel into a "sycl program", create a sycl kernel and transfer the ownership to the sycl runtime. We then submit a _sycl kernel_ to a _sycl queue_ so that any consumer of the queue would be able to wait on the event in that queue (by querying outstanding events).

Could you please extend this with the phase 2 as you named it?

2024-01-18 15:55 UTC, kurapov-peter commented
Also, a general question. Have we considered simply wrapping a level zero event handle into a sycl object and putting it into the queue? What is the downside of such an approach? In other words, why do we want to redo the launcher all everything instead?

2024-01-19 15:31 UTC, Sarbojit2019 commented on third_party/xpu/backend/driver.c
> +            }
Agree, as of now I did not find any existing logging method in this file. We can think of adding it in phase-2.

2024-01-19 15:31 UTC, Sarbojit2019 commented on third_party/xpu/backend/driver.py
> +      sycl::kernel kernel = *(static_cast<sycl::kernel*>(pKrnl));
Done

2024-01-19 15:31 UTC, Sarbojit2019 commented on third_party/xpu/backend/driver.py
> +  static void sycl_kernel_launch(int gridX, int gridY, int gridZ, int num_warps, int threads_per_warp, int shared_memory, sycl::queue& stream, sycl::kernel& kernel_ptr {', ' + arg_decls if len(arg_de
Done

2024-01-19 15:31 UTC, Sarbojit2019 commented on third_party/xpu/backend/driver.c
> +            if(pdevID == nullptr) return NULL;
Addressed

2024-01-19 15:31 UTC, Sarbojit2019 commented on third_party/xpu/backend/driver.c
> +        std::vector<std::unique_ptr<sycl::kernel>> compiled_kernel;
'compiled_kernel' is a global variable any loadSyclBinary call will push kernels into the vector.

2024-01-19 15:32 UTC, Sarbojit2019 commented on third_party/xpu/backend/driver.c
> +        #define EXPECT_EQ(value1, value2)                                              \
I have one macro as suggested. I have not added zeDriverGetLastErrorDescription as it needs L0 driver handle which at present we don't create.

2024-01-19 15:32 UTC, Sarbojit2019 commented on python/triton/compiler/compiler.py
> +                stream = torch.xpu.current_stream().sycl_queue
Not sure what do you mean by "This introduces a circular dependency". SYCL submission is via queue hence I am extracting it from torch runtime. In case you feel 'stream' name is confusing I can change it.

2024-01-19 15:49 UTC, kurapov-peter commented on python/triton/compiler/compiler.py
> +                stream = torch.xpu.current_stream().sycl_queue
Torch includes the triton package. You include torch here. This is a circular dependency.

2024-01-19 16:56 UTC, whitneywhtsang reviewed
In general, please have XPU specific changes in `third_party/xpu/backend/driver.py` when possible, and keep changes to `compiler.py` and `jit.py` minimal.

2024-01-19 16:56 UTC, whitneywhtsang commented on python/triton/compiler/compiler.py
> +
```suggestion
```

2024-01-19 16:56 UTC, whitneywhtsang commented on python/triton/compiler/compiler.py
> +            torch.xpu.device(device).sycl_device)
Please change `driver.get_current_device` for XPU instead.

2024-01-19 16:56 UTC, whitneywhtsang commented on python/triton/compiler/compiler.py
> -            if stream is None:
Please keep this, and update `driver.get_current_stream` for XPU.

2024-01-19 16:56 UTC, whitneywhtsang commented on python/triton/compiler/compiler.py
> -                dev_obj, ctxt_obj, q_obj = driver.utils.get_dev_ctxt_queue_objs()
Please update `driver.utils.get_dev_ctxt_queue_objs` for XPU.

2024-01-23 06:16 UTC, Sarbojit2019 commented on python/triton/compiler/compiler.py
> +                stream = torch.xpu.current_stream().sycl_queue
Here we are using Torch component to find, initialize and allocate device objects in Triton where as Torch uses Triton syntax for kernels hence there should not be any problem of circular dependency.

2024-01-23 11:21 UTC, kurapov-peter commented on python/triton/compiler/compiler.py
> +                stream = torch.xpu.current_stream().sycl_queue
Torch package imports Inductor which imports `triton` which in turn imports the `compile` function from `compiler`. It returns a `CompiledKernel` that imports torch again. Not a good idea.

2024-01-23 17:28 UTC, Sarbojit2019 commented on python/triton/compiler/compiler.py
> +                stream = torch.xpu.current_stream().sycl_queue
When a Torch inductor written in Triton is called at runtime, Triton has to generate a kernel function that is executable on the Torch device.  Triton cannot randomly find a GPU on the system and return a kernel that is not executable on the device that Torch is run.  Hence, Triton needs to get the device from the Torch side. 

If you still disagree, let's have a meeting offline.

2024-01-25 14:03 UTC, whitneywhtsang commented on third_party/intel/backend/driver.py
> +        self.device_count = mod.init_devices(torch.xpu.current_stream().sycl_queue)
Since 
```
    def get_current_stream(self, device):
        import torch
        return torch.xpu.current_stream().sycl_queue
```
```suggestion
        self.context = mod.init_context(self.get_sycl_queue())
        self.device_count = mod.init_devices(self.get_sycl_queue())
```

2024-01-25 14:03 UTC, whitneywhtsang commented on third_party/intel/backend/driver.c
Can you please run clang-format on this file?

2024-01-25 14:37 UTC, Sarbojit2019 commented on third_party/xpu/backend/driver.c
> +            sycl::kernel *k = new sycl::kernel(*ptr);
After the launch I am deleting it in launch function.

2024-01-25 16:27 UTC, kurapov-peter commented on python/triton/compiler/compiler.py
> +                stream = torch.xpu.current_stream().sycl_queue
Discussed offline. Decision is to proceed with the current approach as our options are limited by current Inductor design.

2024-01-25 16:52 UTC, whitneywhtsang commented on third_party/intel/backend/driver.c
> +  // std::cout<<"Inside create_module 1"<<std::endl;
Can we please also remove the commented out print lines?

2024-01-26 08:44 UTC, kurapov-peter requested changes

2024-01-26 08:44 UTC, kurapov-peter commented on third_party/intel/backend/driver.c
> +  }
Does this rely on some order in the unordered map?

2024-01-26 08:44 UTC, kurapov-peter commented on third_party/intel/backend/driver.py
> +        return 0, 0, 0
If this doesn't do anything, can we remove the method?

2024-01-26 08:44 UTC, kurapov-peter commented on third_party/intel/backend/driver.py
> +*/
Could you please clean up all the commented out code?

2024-01-26 15:07 UTC, kurapov-peter approved these changes

2024-01-26 15:28 UTC, whitneywhtsang commented on python/triton/compiler/compiler.py
> +            self.name, self.kernel, self.metadata.shared, driver.active.utils.get_sycl_device(device))
Please guide this change under `if driver.active.get_current_target()[0] == "xpu":`.

2024-01-26 15:39 UTC, whitneywhtsang approved these changes

2024-01-26 16:22 UTC, merged