[UT] Port and run operator tests
intel/intel-xpu-backend-for-triton pull request #246
Opened 2024-01-12 04:56 UTC by ESI-SYD

2024-01-12 14:47 UTC, whitneywhtsang commented
Please create issues for the skipped tests.

2024-01-12 15:05 UTC, whitneywhtsang approved these changes

2024-01-12 15:05 UTC, whitneywhtsang commented on .github/workflows/build_and_test.yml
> +        if: ${{ env.BACKEND == 'XPU'}}
`integration-tests.yml` doesn't check for BACKEND here.
```suggestion
```

2024-01-12 15:25 UTC, whitneywhtsang requested changes
```
...
FAILED operators/test_blocksparse.py::test_matmul[DTYPE0-16-False-True-sdd] - RuntimeError: Triton Error [ZE]: 2013265944
FAILED operators/test_blocksparse.py::test_matmul[DTYPE0-16-True-True-sdd] - RuntimeError: Triton Error [ZE]: 2013265944
FAILED operators/test_blocksparse.py::test_matmul[DTYPE0-64-False-True-dsd] - RuntimeError: Triton Error [ZE]: 2013265944
FAILED operators/test_blocksparse.py::test_softmax[64-1871-True] - RuntimeError: Triton Error [ZE]: 2013265944
=========== 55 failed, 2 passed, 884 skipped, 244 warnings in 26.69s ===========
```

2024-01-15 02:00 UTC, ESI-SYD commented
> Please create issues for the skipped tests.

OK

2024-01-15 15:07 UTC, whitneywhtsang approved these changes

2024-01-15 15:07 UTC, whitneywhtsang commented on scripts/test-triton.sh
> +  cd $CORE_TEST_DIR/operators
nit: follow the same order as ci testing, run runtime testing before operators.

2024-01-15 15:49 UTC, etiotto commented on scripts/test-triton.sh
> +  TRITON_DISABLE_LINE_INFO=1 python3 -m pytest -n 8 --verbose
[nit]: Either remove `-n 8` here or also add it to the runtime tests ?

2024-01-15 15:49 UTC, etiotto commented on python/test/unit/operators/test_matmul.py
> +    pytest.skip("FIXME: Port get_device_capability to XPU")
Have you opened an issue to track this problem ?

2024-01-15 15:49 UTC, etiotto commented on python/test/unit/operators/test_flash_attention.py
> +    pytest.skip("FIXME: Port get_device_capability to XPU")
Have you opened an issue to track this problem ?

2024-01-15 15:49 UTC, etiotto commented on python/test/unit/operators/test_cross_entropy.py
> +    pytest.skip("FIXME: Port get_device_capability to XPU")
Have you opened an issue to track this problem ?

2024-01-15 15:49 UTC, etiotto commented on python/test/unit/operators/test_blocksparse.py
> +    pytest.skip("FIXME: Port get_device_capability to XPU")
Have you opened an issue to track this problem ?

2024-01-15 15:58 UTC, whitneywhtsang commented on scripts/test-triton.sh
> +  TRITON_DISABLE_LINE_INFO=1 python3 -m pytest -n 8 --verbose
runtime tests intentionally run serially to avoid race condition with cache handling.

2024-01-15 17:04 UTC, etiotto commented on scripts/test-triton.sh
> +  TRITON_DISABLE_LINE_INFO=1 python3 -m pytest -n 8 --verbose
Fine. Let's add a comment to document that:
```
 # run runtime tests serially to avoid race condition with cache handling.
 ```

2024-01-16 03:37 UTC, ESI-SYD commented on python/test/unit/operators/test_matmul.py
> +    pytest.skip("FIXME: Port get_device_capability to XPU")
done

2024-01-16 03:37 UTC, ESI-SYD commented on python/test/unit/operators/test_flash_attention.py
> +    pytest.skip("FIXME: Port get_device_capability to XPU")
done

2024-01-16 03:37 UTC, ESI-SYD commented on python/test/unit/operators/test_blocksparse.py
> +    pytest.skip("FIXME: Port get_device_capability to XPU")
done

2024-01-16 03:37 UTC, ESI-SYD commented on python/test/unit/operators/test_cross_entropy.py
> +    pytest.skip("FIXME: Port get_device_capability to XPU")
done

2024-01-16 05:25 UTC, merged