Windows native port
intel/intel-xpu-backend-for-triton pull request #2478
Opened 2024-10-11 23:53 UTC by gshimansky

The core Triton is a small number of people, and we receive many PRs (thank
you!).  To help us review your code more quickly, **if you are a new
contributor (less than 3 PRs merged) we ask that you complete the following
tasks and include the filled-out checklist in your PR description.**

Complete the following tasks before sending your PR, and replace `[ ]` with
`[x]` to indicate you have done them.

- [x] I am not making a trivial change, such as fixing a typo in a comment.

- [x] I have written a PR description following these
  [rules](https://cbea.ms/git-commit/#why-not-how).

- [x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.

- Select one of the following.
  - [ ] I have added tests.
    - `/test` for `lit` tests
    - `/unittest` for C++ tests
    - `/python/test` for end-to-end tests
  - [x] This PR does not need a test because `it does not implement any new features`.

- Select one of the following.
  - [x] I have not added any `lit` tests.
  - [ ] The `lit` tests I have added follow these [best practices](https://mlir.llvm.org/getting_started/TestingGuide/#filecheck-best-practices),
    including the "tests should be minimal" section. (Usually running Python code
    and using the instructions it generates is not minimal.)

Fixes #2407. Current state is that code builds on windows and is able to pass many unit tests. More fixes will be done when this patch is integrated into main branch.

2024-10-12 00:02 UTC, whitneywhtsang commented
Please fix the CI failures. And can we add testing to prevent regression?

2024-10-12 00:35 UTC, gshimansky commented
> Please fix the CI failures. And can we add testing to prevent regression?

Sure, we will add windows CI too but at the moment we don't have almost any windows infrastructure, and we need to figure out how to do automation. All of the bash scripts are not going to run on windows.

2024-10-16 02:23 UTC, gshimansky commented
CI is green on Linux so PR is ready for review now.

2024-10-16 08:29 UTC, victor-eds reviewed
Is this intended to be upstreamed?

2024-10-16 08:29 UTC, victor-eds commented on CMakeLists.txt
> +  set(CMAKE_STATIC_LINKER_FLAGS_TRITONRELBUILDWITHASSERTS "/debug:fastlink /INCREMENTAL")
Why different options?

2024-10-16 08:29 UTC, victor-eds commented on CMakeLists.txt
> +  endif()
Wouldn't the `-std=*` be set by the `CMAKE_CXX_STANDARD`?

2024-10-16 08:29 UTC, victor-eds commented on bin/RegisterTritonDialects.h
> -// Below headers will allow registration to ROCm passes
Keep comment. Also, why do we need to drop AMD support?

2024-10-16 15:32 UTC, gshimansky commented on bin/RegisterTritonDialects.h
> -// Below headers will allow registration to ROCm passes
We're just not implementing AMD support on WIN32. Not dropping it on Linux. I've restored the comment. It was deleted in the original windows PR https://github.com/triton-lang/triton/pull/4045 for unknown reason.

2024-10-17 15:26 UTC, anmyachev commented on python/test/unit/language/test_core.py
> +        f.close()
Why is it necessary only in this case?

2024-10-17 15:26 UTC, anmyachev commented on python/test/unit/language/test_core.py
> +    with tempfile.NamedTemporaryFile(mode='w', suffix='.ttgir', delete=False) as f:
Why is `delete=False` option used?

2024-10-17 15:26 UTC, anmyachev commented on python/test/unit/language/print_helper.py
> +        torch.cuda.synchronize()
I don't think it's necessary since there is synchronization on 148 line.
```suggestion
```

2024-10-17 15:26 UTC, anmyachev commented on python/test/unit/language/test_reproducer.py
> +    tmpdir = os.path.abspath(".tmp")
Why?

2024-10-17 15:26 UTC, anmyachev commented on python/test/unit/language/test_compile_errors.py
> +        assert target in '\n'.join(traceback.format_tb(inner.__traceback__)), "error should point inside core.py"
Maybe use `os.path.sep`? It will be easier to upstream.

2024-10-17 16:04 UTC, anmyachev commented on python/triton/compiler/compiler.py
> +    libtriton_hash = hashlib.sha1()
Why did you change the algorithm?

2024-10-17 16:04 UTC, anmyachev commented on python/triton/compiler/compiler.py
> +    ext = "so" if os.name != "nt" else "pyd"
?
```suggestion
    ext = sysconfig.get_config_var('EXT_SUFFIX')
```

2024-10-17 16:09 UTC, anmyachev commented on third_party/intel/backend/driver.py
> +    file_name = name + (".pyd" if os.name == "nt" else ".so")
?
```suggestion
    file_name = f"{name}{sysconfig.get_config_var('EXT_SUFFIX')}"
```

2024-10-17 16:24 UTC, anmyachev commented on python/test/unit/language/test_subprocess.py
> +    outs = [line for line in proc.stdout.decode("UTF-8").replace('\r', '').split("\n") if line]
?
```suggestion
    outs = [line for line in proc.stdout.decode("UTF-8").splitlines() if line]
```

2024-10-17 18:01 UTC, anmyachev commented on python/triton/backends/compiler.py
> +        binary += ".exe" if os.name == "nt" else ""
?
```suggestion
        binary += sysconfig.get_config_var("EXE") or ""
```

2024-10-17 18:14 UTC, gshimansky commented on python/test/unit/language/print_helper.py
> +        torch.cuda.synchronize()
This code came from the original windows port PR https://github.com/triton-lang/triton/pull/4045. I removed it.

2024-10-17 18:14 UTC, gshimansky commented on python/test/unit/language/test_core.py
> +        f.close()
This code came from the original windows port PR https://github.com/triton-lang/triton/pull/4045. I removed it.

2024-10-17 18:16 UTC, gshimansky commented on python/test/unit/language/test_reproducer.py
> +    tmpdir = os.path.abspath(".tmp")
This code came from the original windows port PR https://github.com/triton-lang/triton/pull/4045. I removed it.

2024-10-17 18:28 UTC, anmyachev commented on third_party/intel/backend/driver.c
> +#endif
Looks like a development-friendly code. Will it stay that way?

2024-10-17 18:38 UTC, anmyachev commented on python/test/unit/language/test_core.py
> +    with tempfile.NamedTemporaryFile(mode='w', suffix='.ttgir', delete=False) as f:
Ah, windows file descriptors, totally forgot. Thanks for trying.

2024-10-17 18:40 UTC, anmyachev commented on python/triton/compiler/compiler.py
> +    ext = "so" if os.name != "nt" else "pyd"
It looks like the behavior in python has changed: https://bugs.python.org/issue39825 :)

> Do we want to switch to this kind of library names?

No, but we can do like that: `sysconfig.get_config_var('EXT_SUFFIX').split(".")[-1]`

2024-10-17 21:45 UTC, anmyachev commented on include/triton/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.h
> +#include <string>
In the upstream: https://github.com/triton-lang/triton/commit/d1958329c9c531d33b4933e9bfcdbc4b15ab4ed0

2024-10-17 21:45 UTC, anmyachev commented on python/test/unit/language/test_compile_errors.py
> +        assert target in '\n'.join(traceback.format_tb(inner.__traceback__)), "error should point inside core.py"
In the upstream https://github.com/triton-lang/triton/commit/188370325395c79a4ba3de0bc47e39a19fc83224

2024-10-17 21:45 UTC, anmyachev commented on python/test/unit/language/test_subprocess.py
> +    outs = [line for line in proc.stdout.decode("UTF-8").replace('\r', '').split("\n") if line]
In the upstream https://github.com/triton-lang/triton/commit/188370325395c79a4ba3de0bc47e39a19fc83224

2024-10-18 01:08 UTC, gshimansky commented on python/triton/backends/compiler.py
> +        binary += ".exe" if os.name == "nt" else ""
Ok

2024-10-18 01:16 UTC, gshimansky commented on third_party/intel/backend/driver.c
> +#endif
I am not sure I understand your question. In the original code we don't catch an exception that comes from `ext_oneapi_get_default_context`. On Windows it is always thrown but we can safely ignore it (at least it looks so since everything works just fine). We don't have `_DEBUG` defined even in current *WithAsserts configurations so there is no message coming from this code by default.

2024-10-18 01:19 UTC, gshimansky commented on python/triton/compiler/compiler.py
> +    ext = "so" if os.name != "nt" else "pyd"
`sysconfig.get_config_var('EXT_SUFFIX').split(".")[-1]` produces `so` and `pyd`, not `.so` or `.pyd`. We need to also add a dot to the expression which already looks pretty ugly. Are you sure it is better than `"so" if os.name != "nt" else "pyd"`?

2024-10-18 02:10 UTC, gshimansky commented on python/test/unit/language/test_compile_errors.py
> +        assert target in '\n'.join(traceback.format_tb(inner.__traceback__)), "error should point inside core.py"
Ok.

2024-10-18 08:38 UTC, anmyachev commented on include/triton/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.h
> +#include <string>
yes, do you mind or should I stop?

In any case, for now I have only taken changes that are in any case useful to Triton itself.

2024-10-18 08:42 UTC, anmyachev commented on python/triton/compiler/compiler.py
> +    ext = "so" if os.name != "nt" else "pyd"
> Are you sure it is better than "so" if os.name != "nt" else "pyd"?

Not completely, but there is one argument in favor of such a decision.

> It looks overly complicated and less readable to me.

yes, you are right, it looks more complicated. However, in this case in triton (if we upstream these changes) there will be no code branches that are not executed.

2024-10-18 08:47 UTC, anmyachev commented on third_party/intel/backend/driver.c
> +#endif
> On Windows it is always thrown but we can safely ignore it (at least it looks so since everything works just fine).

Yes, that's what caught my eye. Without exception handling, it looks like the code was used when writing the code and then debugging (and subsequent cleanup that might have been forgotten).

Maybe at least add a comment, because ignoring the exception doesn't seem obvious?

2024-10-18 13:53 UTC, gshimansky commented on python/test/unit/language/test_subprocess.py
> +    outs = [line for line in proc.stdout.decode("UTF-8").replace('\r', '').split("\n") if line]
Ok.

2024-10-18 13:58 UTC, gshimansky commented on third_party/intel/backend/driver.c
> +#endif
Ok I added a comment that exception is ignored.

2024-10-18 14:10 UTC, gshimansky commented on python/triton/compiler/compiler.py
> +    ext = "so" if os.name != "nt" else "pyd"
Ok.

2024-10-18 14:11 UTC, gshimansky commented on third_party/intel/backend/driver.py
> +    file_name = name + (".pyd" if os.name == "nt" else ".so")
Ok.

2024-10-18 19:26 UTC, anmyachev commented on python/setup.py
> +    supported = {"Linux": "linux", "Windows": "win"}
In the upstream: https://github.com/triton-lang/triton/commit/bce48c82f3a8586e2f35b51d1afbcfe72a3fbbcd

2024-10-18 20:27 UTC, pbchekin commented on python/test/unit/language/test_core.py
> +    with tempfile.NamedTemporaryFile(mode='w', suffix='.ttgir', delete=False) as f:
We still need to delete the temporary file somehow. On Linux, we should use `delete=True` because it is simpler.

2024-10-20 22:13 UTC, anmyachev commented on bin/CMakeLists.txt
> +  PARTIAL_SOURCES_INTENDED
On line 85 it is already used, is that enough?
```suggestion
```

2024-10-21 10:19 UTC, anmyachev commented on lib/Tools/LinearLayout.cpp
> +  _BitScanForward(&index, x);
In the upstream: https://github.com/triton-lang/triton/commit/9d424e02ed4db695cc58baf939ec75ed0f0bc5b1

2024-10-21 11:38 UTC, anmyachev commented on python/src/main.cc
> +#define EXPAND(x) x
Have you tried using `/Zc:preprocessor` or `/experimental:preprocessor` options to avoid using this workaround for MSVC compiler? Ref: https://stackoverflow.com/a/5134656/21672583

2024-10-21 21:18 UTC, gshimansky commented on bin/CMakeLists.txt
> +  PARTIAL_SOURCES_INTENDED
This is probably a result of some automatic merge. Removed.

2024-10-21 21:27 UTC, gshimansky commented on python/test/unit/language/test_core.py
> +    with tempfile.NamedTemporaryFile(mode='w', suffix='.ttgir', delete=False) as f:
I found that we can use `delete_on_close=False` instead of `delete=False`. The resulting file is deleted after `with` block ends and doesn't produce exceptions on Windows. Testing...

2024-10-21 21:40 UTC, gshimansky commented on python/test/unit/language/test_core.py
> +    with tempfile.NamedTemporaryFile(mode='w', suffix='.ttgir', delete=False) as f:
Unfortunately `delete_on_close` was added only in python 3.12.

2024-10-22 20:03 UTC, gshimansky commented on python/src/main.cc
> +#define EXPAND(x) x
Yes /Zc:preprocessor seems to have helped with this problem

2024-10-22 20:26 UTC, gshimansky commented on python/setup.py
> +    command = f'call "{vcvarsall_path}" {arch} && set'
Ok.

2024-10-24 15:05 UTC, anmyachev approved these changes
LGTM! 

Although there is still something to fix in terms of reducing the diff from the main triton, I think we should merge it and give the opportunity to add the following parts related to this pull request. I in turn will continue to upstream changes to reduce the diff as much as possible.

@gshimansky thank you for addressing all my comments, there were a lot of them :)

2024-10-25 13:38 UTC, anmyachev commented on third_party/f2reduce/f2reduce.cpp
> +#define __builtin_prefetch(addr) _mm_prefetch(reinterpret_cast<const char *>(addr), _MM_HINT_T0)
There is no longer a need to have it because all built-in use is under this `#if defined(__GNUC__)` guard. Fixed in https://github.com/triton-lang/triton/pull/4416.

2024-10-25 15:06 UTC, whitneywhtsang commented on CMakeLists.txt
> +    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__STDC_FORMAT_MACROS -fPIC")
can we make this change upstream?

2024-10-25 15:11 UTC, etiotto requested changes
The current implementation diverges too much from the upstream one. Please reduce the divergence to the absolute minimum. After that we will go back to review the code once more.

2024-10-25 18:45 UTC, gshimansky commented on third_party/f2reduce/f2reduce.cpp
> +#define __builtin_prefetch(addr) _mm_prefetch(reinterpret_cast<const char *>(addr), _MM_HINT_T0)
Ok.

2024-10-25 22:30 UTC, gshimansky commented on python/setup.py
> +        arch = {"x86_64": "x64", "AMD64": "64", "arm64": "arm64", "aarch64": "arm64"}[platform.machine()]
`platform.machine()` function on windows returns `AMD64` so this change may be needed in the future when we provide our binaries of llvm. Right now it is not needed because we don't build llvm and there is no LLVM binaries (at least I couldn't find any) on the original server oaitriton.blob.core.windows.net.

2024-10-25 22:31 UTC, gshimansky commented on bin/RegisterTritonDialects.h
> +#ifndef WIN32
Yes apparently they build just fine. This ifdef came from the original windows PR https://github.com/triton-lang/triton/pull/4045

2024-10-25 23:22 UTC, gshimansky commented on python/setup.py
> -            if sys.maxsize > 2**32:
Yes it looks that Triton inherited some obsolete windows support from deprecated project called ISAAC. Prior git history has been erased so I can only guess that this option was probably be used with MSVC project files but it is not compatible with Ninja build that we use now.

2024-10-25 23:36 UTC, gshimansky commented on python/src/interpreter.cc
> +    {MemSemantic::ACQUIRE_RELEASE, static_cast<int>(std::memory_order_acq_rel)},
Constants `__ATOMIC_*` are not defined on Windows. They are non-standard gcc extension I suppose.

2024-10-28 19:47 UTC, anmyachev commented on python/src/interpreter.cc
> +    {MemSemantic::ACQUIRE_RELEASE, static_cast<int>(std::memory_order_acq_rel)},
In the upstream: https://github.com/triton-lang/triton/commit/7c03aac0e52aa223d8bd2be7b3115d5a3b9ac69f

2024-10-29 15:36 UTC, etiotto commented on bin/RegisterTritonDialects.h
> +#ifndef WIN32
Perfect

2024-10-29 15:37 UTC, etiotto commented on python/setup.py
> +        arch = {"x86_64": "x64", "AMD64": "64", "arm64": "arm64", "aarch64": "arm64"}[platform.machine()]
Ok, thanks for the explanation. Given this is not currently required I'd remove it.

2024-10-29 15:38 UTC, etiotto commented on python/setup.py
> -            if sys.maxsize > 2**32:
@anmyachev can this change then be upstreamed too ?

2024-10-29 18:02 UTC, gshimansky commented on python/setup.py
> +        arch = {"x86_64": "x64", "AMD64": "64", "arm64": "arm64", "aarch64": "arm64"}[platform.machine()]
Ok removed it.

2024-10-29 18:02 UTC, gshimansky commented on bin/RegisterTritonDialects.h
> +#ifndef WIN32
I tried now and apparently they compile just fine. I removed ifdefs.

2024-10-30 09:09 UTC, victor-eds commented on CMakeLists.txt
> +  set(CMAKE_CXX_STANDARD 20)
Why did we need C++ 20 in Windows?

2024-10-30 09:09 UTC, victor-eds commented on python/setup.py
> +    return None
So we do not support VS installed in a different path?

2024-10-30 09:09 UTC, victor-eds commented on python/setup.py
> +            print(vs_path)
Do we wanna keep this print?

2024-10-30 09:09 UTC, victor-eds commented on python/src/interpreter.cc
> +    {MemSemantic::ACQUIRE_RELEASE, static_cast<int>(std::memory_order_acq_rel)},
Can we update this PR with that code? Thanks!

2024-10-30 13:59 UTC, gshimansky commented on CMakeLists.txt
> +  set(CMAKE_CXX_STANDARD 20)
This question has been answered before. MSVC is unable to compile some templates in C++ 17 mode but compiles them successfully in C++ 20 mode.
https://github.com/intel/intel-xpu-backend-for-triton/pull/2478#discussion_r1803310959

2024-10-30 13:59 UTC, anmyachev commented on python/setup.py
> -            if sys.maxsize > 2**32:
In the upstream: https://github.com/triton-lang/triton/commit/0591b3756bd4143b7163235c0eca4d718948e982

2024-10-30 14:01 UTC, gshimansky commented on python/setup.py
> +    return None
This is the default subfolders structures how MSVS installs itself. `ProgramFiles(x86)` is an environment variable, it may point to a different location but subfolders should be the same.

2024-10-30 14:05 UTC, gshimansky commented on python/setup.py
> +            print(vs_path)
No it is not needed. I removed it.

2024-10-30 14:07 UTC, anmyachev commented on .gitignore
> +
This is not needed since `dst_path` as not having the file extension when we call `download_and_copy`.
```suggestion
```

2024-10-30 14:10 UTC, gshimansky commented on .gitignore
> +
Ok.

2024-11-01 08:50 UTC, anmyachev commented on python/triton/compiler/compiler.py
> +    with open(os.path.join(TRITON_PATH, "_C", f"libtriton.{ext}"), "rb") as f:
```suggestion
    with open(os.path.join(TRITON_PATH, f"_C/libtriton.{ext}"), "rb") as f:
```

2024-11-01 15:17 UTC, pbchekin commented on python/triton/compiler/compiler.py
> +    with open(os.path.join(TRITON_PATH, "_C", f"libtriton.{ext}"), "rb") as f:
The original line is more portable.

2024-11-01 17:51 UTC, gshimansky commented on python/triton/compiler/compiler.py
> +    with open(os.path.join(TRITON_PATH, "_C", f"libtriton.{ext}"), "rb") as f:
Why do you think that using hardcoded forward slash in path is better than using os.path.join that is specifically made to use platform dependent path separators? Especially since we are already using os.path.join in this line why not concatenate path parts in a platform independent way?

2024-11-01 17:54 UTC, anmyachev commented on python/triton/compiler/compiler.py
> +    with open(os.path.join(TRITON_PATH, "_C", f"libtriton.{ext}"), "rb") as f:
you are right, sorry

2024-11-02 21:30 UTC, anmyachev commented on python/test/unit/language/test_core.py
> +    with tempfile.NamedTemporaryFile(mode='w', suffix='.ttgir', delete=False) as f:
Another way in the upstream: https://github.com/triton-lang/triton/commit/a27398664b44c70ef67e1813cdbcffd1d0991629

2024-11-02 22:48 UTC, anmyachev commented on third_party/nvidia/backend/compiler.py
> +            os.remove(flog.name)
This has been moved to `352` line, can be deleted.

2024-11-04 09:29 UTC, victor-eds commented on python/setup.py
> +    return None
Oh, I see. `vswhere` is a constant location. LGTM.

2024-11-04 09:30 UTC, victor-eds approved these changes

2024-11-04 15:15 UTC, anmyachev commented on python/setup.py
> +def find_visual_studio(version_ranges):
Could we reuse code from `CLFinder.py`?

2024-11-04 15:43 UTC, gshimansky commented on third_party/nvidia/backend/compiler.py
> +            os.remove(flog.name)
Do you mean that it has been moved in the upstream?

2024-11-04 15:49 UTC, anmyachev commented on third_party/nvidia/backend/compiler.py
> +            os.remove(flog.name)
This is only my guess, because I see similar code right in this pull request, in this file on line 352. Or am I missing something?

2024-11-05 12:00 UTC, anmyachev commented on CMakeLists.txt
> +    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__STDC_FORMAT_MACROS -fPIC")
Doesn't `set(CMAKE_CXX_STANDARD 17)` correspond to `-std=c++17`, not `-std=gnu++17`?

2024-11-06 02:15 UTC, gshimansky commented on third_party/nvidia/backend/compiler.py
> +            os.remove(flog.name)
Ok.

2024-11-06 09:47 UTC, anmyachev commented on python/setup.py
> +            cmake_args += ["-DCMAKE_BUILD_TYPE=" + cfg]
Already in `484` line.
```suggestion
```

2024-11-06 15:53 UTC, anmyachev commented on python/setup.py
> +        command = [
For me it works only if I specify `-products`:
`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -version "[17.0,18.0)" -products Microsoft.VisualStudio.Product.BuildTools -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -prerelease`

@gshimansky do you know why?

2024-11-06 16:29 UTC, gshimansky commented on python/setup.py
> +        command = [
For me it works just fine if I don't specify `-products` or if I specify `-products "*"`. Specifying `-products Microsoft.VisualStudio.Product.BuildTools` doesn't find anything for me but specifying `-products Microsoft.VisualStudio.Product.Professional` does.

2024-11-06 16:42 UTC, anmyachev commented on python/setup.py
> +        command = [
`-products "*"` works for me too. It seems that this is because I did not install the entire studio, but only the build tools. Should we add `-products "*"` to allow this case?

2024-11-06 16:49 UTC, gshimansky commented on python/setup.py
> +        command = [
I don't know whether it may result in multiple different products found as the result, but we can add it for now.

2024-11-07 01:58 UTC, gshimansky commented on python/setup.py
> +            cmake_args += ["-DCMAKE_BUILD_TYPE=" + cfg]
Ok.

2024-11-07 02:05 UTC, gshimansky commented on python/setup.py
> +def find_visual_studio(version_ranges):
We can and it should work in theory, but it doesn't. For some reason when I import these functions from CLFinder I am getting an error `LINK : fatal error LNK1168: cannot open C:\b\tr\python\triton\_C\libtriton.pyd for writing`. I have no idea how they are related but this link error is stably reproducible for me. I tried to debug the problem and found that environment after calling `set_env_vars` is identical when functions are reused from CLFinder.py or setup.py has its own copies, so now I am out of ideas how libtryton.pyd may end up locked.

2024-11-07 19:53 UTC, anmyachev commented on third_party/nvidia/backend/driver.c
> +    symbolName##_t funcHandle =                                                \
Should we explicitly clear any existing error on Windows as well?
```suggestion
    }                                                                          \
    /* Clear any existing error */                                             \
    SetLastError(NO_ERROR);                                                    \
    symbolName##_t funcHandle =                                                \
```

2024-11-07 19:56 UTC, anmyachev commented on python/setup.py
> +        command = [
> I don't know whether it may result in multiple different products found as the result, but we can add it for now.

I thought about that too. But couldn't it be the same default behavior when `-products` parameter is not specified at all?

2024-11-07 19:59 UTC, gshimansky commented on third_party/nvidia/backend/driver.c
> +    symbolName##_t funcHandle =                                                \
I don't think that is needed. GetLastError is used for information purposes only (think of it as of `errno` in POSIX), any next call of Win32 API should set its own error status, clear it if it is successful.

2024-11-08 08:48 UTC, anmyachev commented on python/triton/backends/compiler.py
> +        binary += sysconfig.get_config_var("EXE")
Done in https://github.com/intel/intel-xpu-backend-for-triton/commit/94684d326723b67b146f23f342623ea058a32098

2024-11-08 09:53 UTC, anmyachev commented on third_party/nvidia/backend/driver.c
> +#endif
This is no longer necessary.
```suggestion
```

2024-11-08 15:12 UTC, gshimansky commented on third_party/nvidia/backend/driver.c
> +#endif
Ok.

2024-11-08 15:46 UTC, anmyachev commented on third_party/nvidia/backend/compiler.py
> +
```suggestion
```

2024-11-08 17:28 UTC, gshimansky commented on third_party/nvidia/backend/compiler.py
> +
Ok.

2024-11-11 10:01 UTC, anmyachev commented on third_party/intel/backend/driver.c
> -        sycl_device.get_platform().ext_oneapi_get_default_context();
Could we make this available on Windows using `set SYCL_ENABLE_DEFAULT_CONTEXTS=1`: https://github.com/intel/llvm/blob/7dd09d9effd6a56d2c0c7abca38b21baa4d77fc8/sycl/doc/EnvironmentVariables.md?plain=1#L22?

2024-11-12 22:17 UTC, gshimansky commented on CMakeLists.txt
> +    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__STDC_FORMAT_MACROS -fPIC")
Then it might be some legacy like Windows build support that Triton inherited from previous projects and by now nobody knows why it was added.

2024-11-13 22:12 UTC, gshimansky commented on third_party/intel/backend/driver.c
> -        sycl_device.get_platform().ext_oneapi_get_default_context();
I checked this and it does work. But I am not sure it is a good way because triton on Windows will work only with this variable set to 1. Even on Linux if someone has environment `SYCL_ENABLE_DEFAULT_CONTEXTS=0` we're going to throw an uncaught exception, are you sure it is ok?

2024-11-15 15:16 UTC, etiotto commented on third_party/intel/backend/driver.c
> +      // This exception is thrown on Windows because
This is iffy. If the exception is thrown `ctx` will be uninitialized when used at line 212. Is there another API to use on Windows to get the context ?

2024-11-15 16:18 UTC, gshimansky commented on third_party/intel/backend/driver.c
> +      // This exception is thrown on Windows because
Not exactly unintialized. A default constructor is called which is allowed by sycl spec. And this is exactly what happens on Windows because this exception is thrown. It seems to work just fine with `ctx` initialized like this.

2024-11-19 11:50 UTC, anmyachev commented on python/setup.py
> +                raise EnvironmentError("Visual Studio 2019 or 2022 not found.")
It's probably a good idea to define `initialize_visual_studio_env` as in `CLFinder.py` file here as well.
```suggestion
            if not vs_path:
                raise EnvironmentError("Visual Studio 2019 or 2022 not found.")
            env = set_env_vars(vs_path)
```

2024-11-19 11:53 UTC, anmyachev commented on python/triton/runtime/CLFinder.py
> +    if os.environ.get('VSCMD_ARG_TGT_ARCH') != arch:
At this point `vcvarsall.bat` has not yet been called? This will only happen when calling `set_env_vars` function IIUC.

2024-11-19 14:23 UTC, anmyachev commented on CMakeLists.txt
> +  set(CMAKE_CXX_FLAGS_TRITONRELBUILDWITHASSERTS "/Zi /Ob0 /Od /RTC1 /bigobj /Zc:preprocessor")
@gshimansky these flags are for debug build, aren't?
```suggestion
  set(CMAKE_C_FLAGS_TRITONRELBUILDWITHASSERTS "/Zi /RTC1 /bigobj /Zc:preprocessor")
  set(CMAKE_CXX_FLAGS_TRITONRELBUILDWITHASSERTS "/Zi /RTC1 /bigobj /Zc:preprocessor")
```

2024-11-19 20:40 UTC, merged

2024-11-19 22:47 UTC, gshimansky commented on CMakeLists.txt
> +  set(CMAKE_CXX_FLAGS_TRITONRELBUILDWITHASSERTS "/Zi /Ob0 /Od /RTC1 /bigobj /Zc:preprocessor")
Yes. At the moment there is just one windows build and it is debug build mostly. We can split it into optimized and debug build like we have on Linux.

2024-11-19 22:51 UTC, gshimansky commented on python/triton/runtime/CLFinder.py
> +    if os.environ.get('VSCMD_ARG_TGT_ARCH') != arch:
This check is to verify that we're not already running in a `Developer Command Prompt` environment set outside of setup.py, and if we're running, we're running in environment for the same architecture (32 or 64 bits) that we're going to build here.

2024-11-20 12:17 UTC, anmyachev commented on CMakeLists.txt
> +    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__STDC_FORMAT_MACROS -fPIC")
I double checked. Explicitly usage of `-std=c++17` brokes build: https://github.com/intel/intel-xpu-backend-for-triton/pull/2771. Looks like at least on GCC `set(CMAKE_CXX_STANDARD 17)` add `-std=gnu++17` implicitly.