Introduce optional profiling option for SPIRVRunner
intel/intel-xpu-backend-for-triton pull request #2566
Opened 2024-10-24 17:03 UTC by anmyachev

Closes #2565 

Usage: `./build/SPIRVRunner tensor_2 --enable-profiling`

Output example:
```bash
...
Tensor output: [8192, 8192], Float (268435456 bytes)
Kernel execution time: 4.81872 ms
...
```

Profiling ref: https://github.com/intel/pti-gpu/blob/master/chapters/device_activity_tracing/DPCXX.md#how-to-use
Profiling ref with Kineto: https://github.com/pytorch/pytorch/issues/52936#issuecomment-2047893643

<details>

<summary>Example with Kineto</summary>

```c++
  #include <torch/csrc/autograd/profiler_kineto.h>
  using namespace torch::autograd::profiler;
  ProfilerConfig cfg{
    ProfilerState::KINETO,
      false,
      false,
      false,
      false,
      false
  };
  std::set<torch::autograd::profiler::ActivityType> activities{torch::autograd::profiler::ActivityType::CPU, torch::autograd::profiler::ActivityType::XPU};
  prepareProfiler(cfg, activities);
  enableProfiler(cfg, activities);

  sycl_kernel_launch(stream, kernel, triton_args);

  auto result = disableProfiler();
  result->save("./some_local_file2.json");
```

</details>

2024-10-24 17:08 UTC, anmyachev commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +  if (!triton_args.host_outbuffer.defined()) {
To avoid getting an incomprehensible error.

2024-10-25 15:37 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +bool check_option_amoung_argv(int argc, char **argv, std::string option) {
Can you explain this logic, I am not clear, why do we need this ?

2024-10-25 16:05 UTC, kballeda requested changes

2024-10-25 16:05 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    std::string message = "Output tensor isn't configurated; \
message typo (NITS)

2024-10-28 13:23 UTC, anmyachev commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +    if (get_kernel_time) {
Do you mean to make it part of  `KernelArguments` structure? If so, then it seems to me that `get_kernel_time` option has a different meaning and is not suitable for storage in this structure.

2024-10-28 13:50 UTC, kballeda commented on utils/SPIRVRunner/SPIRVRunner.cpp
> +bool check_option_amoung_argv(int argc, char **argv, std::string option) {
Sure will update this part as part of #2568

2024-10-28 15:07 UTC, kballeda approved these changes

2024-10-28 15:41 UTC, merged