Add BFloat16 and Float32 conversion.
intel/intel-xpu-backend-for-triton pull request #26
Opened 2023-06-20 08:27 UTC by Stonepia

This PR helps for the conversion between BF16 and FP32 type

Related Test cases:

test_core.py::test_cast[float32-bfloat16-False]
test_core.py::test_cast[bfloat16-float32-False]

2023-06-21 00:45 UTC, chengjunlu commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +      val = rewriter.create<arith::TruncIOp>(loc, i16_ty, val);
Make a trunc macro as others.

2023-06-21 00:46 UTC, chengjunlu commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +  static std::map<std::string, int> computeCapability;
Not to copy capability to this class.

2023-06-21 00:47 UTC, chengjunlu commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +std::map<std::string, int> FpToFpOpSPIRVConversion::computeCapability;
Why another copy of the compute capability?

2023-06-21 00:48 UTC, chengjunlu commented
Please add the BF16 conversion capability check logic in front end and pass it to the lowering pass.

2023-06-21 01:12 UTC, Stonepia commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +      val = rewriter.create<arith::TruncIOp>(loc, i16_ty, val);
Thanks for the reply! I didn't put this into the macro is because in `Utility.h`, we all have spirv Ops, but this truncIOp is arith dialect.

2023-06-21 01:19 UTC, EikanWang requested changes
Overall LGTM. Pls add test cases.

2023-06-21 01:19 UTC, EikanWang commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +      return val;
Have you also tried intel math library?

2023-06-21 01:19 UTC, EikanWang commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +      val = rewriter.create<arith::TruncIOp>(loc, i16_ty, val);
Ditto

2023-06-21 03:37 UTC, Stonepia commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +  static std::map<std::string, int> computeCapability;
Resolved in https://github.com/intel/intel-xpu-backend-for-triton/pull/26/commits/31ff3f76f74d8481b85a8c0e1a463df5a43e1f03

2023-06-21 03:37 UTC, Stonepia commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +      val = rewriter.create<arith::TruncIOp>(loc, i16_ty, val);
Resolved in https://github.com/intel/intel-xpu-backend-for-triton/pull/26/commits/a5726d5343c05b64c094e6edbc859f04d2d6fbc9

2023-06-21 03:50 UTC, chengjunlu commented on lib/Conversion/TritonGPUToSPIRV/TritonGPUToSPIRVBase.h
> +  // explicit ConvertTritonGPUOpToSPIRVPattern(TritonGPUToSPIRVTypeConverter &typeConverter,
Remove used code

2023-06-21 03:51 UTC, chengjunlu commented on lib/Conversion/TritonGPUToSPIRV/Utility.h
> +// Value createConstantBF16(Location loc, PatternRewriter &rewriter, float v);
Remove unused code

2023-06-21 03:52 UTC, chengjunlu commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +                                 bool special_op_supported=false) {
special op is confusing. Just name it by its purpose. "intelConvertBF16Op"

2023-06-21 04:09 UTC, Stonepia commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.cpp
> +                                 bool special_op_supported=false) {
Thanks for the review, resolved in https://github.com/intel/intel-xpu-backend-for-triton/pull/26/commits/af06d2a2371d4a4aac895e5e34dee23605aff611

2023-06-21 04:09 UTC, Stonepia commented on lib/Conversion/TritonGPUToSPIRV/Utility.h
> +// Value createConstantBF16(Location loc, PatternRewriter &rewriter, float v);
Thanks, I cleaned up the code

2023-06-21 05:10 UTC, chengjunlu commented on lib/Conversion/TritonGPUToSPIRV/ElementwiseOpToSPIRV.h
> +                                          Value smem, PatternBenefit benefit, std::map<std::string, int> computeCapability);
Pass the reference instead of value.

2023-06-21 05:53 UTC, chengjunlu approved these changes

2023-06-22 09:10 UTC, EikanWang approved these changes

2023-06-22 09:11 UTC, merged