SPIR-V Runner: Integrate argument parsing library
intel/intel-xpu-backend-for-triton pull request #2759
Opened 2024-11-19 16:21 UTC by kballeda

This PR integrates LLVM based argument parsing library into SPIR-V Runner and closes https://github.com/intel/intel-xpu-backend-for-triton/issues/2568

```
/intel-xpu-backend-for-triton/utils/SPIRVRunner$ ./build/SPIRVRunner -o tensor_2
Running on device: Intel(R) Data Center GPU Max 1100
Read 3772 byte kernel.
Loaded kernel with 0 registers and 0 register spills.
Tensor output: [98432], Float (393728 bytes)
Output Tensor Path: intel-xpu-backend-for-triton/utils/SPIRVRunner/cpp_outs.pt

intel-xpu-backend-for-triton/utils/SPIRVRunner$ ./build/SPIRVRunner -o tensor_2 -p
Running on device: Intel(R) Data Center GPU Max 1100
Read 3772 byte kernel.
Loaded kernel with 0 registers and 0 register spills.
Tensor output: [98432], Float (393728 bytes)
Kernel execution time: 0.0096 ms
Output Tensor Path: intel-xpu-backend-for-triton/utils/SPIRVRunner/cpp_outs.pt

intel-xpu-backend-for-triton/utils/SPIRVRunner$ ./build/SPIRVRunner --help
USAGE: SPIRVRunner [options]

OPTIONS:

Color Options:

  --color       - Use colors in output (default=autodetect)

General options:

  -o <filename> - Specify Output Tensor Name
  -p            - Enable Profiling

```

2024-11-20 14:21 UTC, kballeda commented on utils/SPIRVRunner/CMakeLists.txt
> +target_link_libraries(${TARGET_NAME} PRIVATE "${TORCH_LIBRARIES}" "${LLVM_LIBS}")
Thank you for the review. As discussed offline, https://github.com/intel/intel-xpu-backend-for-triton/issues/2568 necessitates the use of the argument parsing library that is already part of the current codebase. We have determined that LLVM is suitable for integration and is also available as a static library (LLVMSupport)

2024-11-20 14:27 UTC, anmyachev approved these changes
LGTM!

2024-11-21 07:23 UTC, kballeda commented on scripts/compile-triton.sh
> +    -DLLVM_ENABLE_RTTI=ON \
I get following error:

<details>
  <summary>Click to expand</summary>
[100%] Linking CXX executable SPIRVRunner
/usr/bin/ld: /tmp/icpx-fb3330f94f/SPIRVRunner-445ef4.o:(.rodata._ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
/usr/bin/ld: /tmp/icpx-fb3330f94f/SPIRVRunner-445ef4.o:(.rodata._ZTIN4llvm2cl15OptionValueCopyIbEE[_ZTIN4llvm2cl15OptionValueCopyIbEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/SPIRVRunner.dir/build.make:110: SPIRVRunner] Error 1


</details>

2024-11-21 13:11 UTC, alexbaden commented on scripts/compile-triton.sh
> +    -DLLVM_ENABLE_RTTI=ON \
Can you try building the SPIRV Runner w/out RTTI?

2024-11-21 17:04 UTC, kballeda commented on scripts/compile-triton.sh
> +    -DLLVM_ENABLE_RTTI=ON \
I have used LLVM (no RTTI default/similar to log above) + disabled RTTI in SPIRVRunner cmake file with following,

`target_compile_option(${TARGET_NAME} PRIVATE -fno-rtti)`

Error Log:

<details>
<summary>Click to show log</summary>

/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:208:61: error: use of typeid requires -frtti
  208 |         CodeLoc, (void *)impl.get(), nullptr, (const void *)typeid(T).name(),
      |                                                             ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:221:61: error: use of typeid requires -frtti
  221 |         CodeLoc, (void *)impl.get(), nullptr, (const void *)typeid(T).name(),
      |                                                             ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:234:62: error: use of typeid requires -frtti
  234 |         CodeLoc, (void *)impl.get(), hostData, (const void *)typeid(T).name(),
      |                                                              ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:247:62: error: use of typeid requires -frtti
  247 |         CodeLoc, (void *)impl.get(), hostData, (const void *)typeid(T).name(),
      |                                                              ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:262:62: error: use of typeid requires -frtti
  262 |         CodeLoc, (void *)impl.get(), hostData, (const void *)typeid(T).name(),
      |                                                              ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:277:62: error: use of typeid requires -frtti
  277 |         CodeLoc, (void *)impl.get(), hostData, (const void *)typeid(T).name(),
      |                                                              ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:293:23: error: use of typeid requires -frtti
  293 |         (const void *)typeid(T).name(), dimensions, sizeof(T),
      |                       ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:309:23: error: use of typeid requires -frtti
  309 |         (const void *)typeid(T).name(), dimensions, sizeof(T),
      |                       ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:325:23: error: use of typeid requires -frtti
  325 |         (const void *)typeid(T).name(), dimensions, sizeof(T),
      |                       ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:341:23: error: use of typeid requires -frtti
  341 |         (const void *)typeid(T).name(), dimensions, sizeof(T),
      |                       ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:373:57: error: use of typeid requires -frtti
  373 |                                           (const void *)typeid(T).name(),
      |                                                         ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:405:57: error: use of typeid requires -frtti
  405 |                                           (const void *)typeid(T).name(),
      |                                                         ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:425:23: error: use of typeid requires -frtti
  425 |         (const void *)typeid(T).name(), dimensions, sizeof(T), r);
      |                       ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:443:64: error: use of typeid requires -frtti
  443 |         CodeLoc, (void *)impl.get(), impl.get(), (const void *)typeid(T).name(),
      |                                                                ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:462:64: error: use of typeid requires -frtti
  462 |         CodeLoc, (void *)impl.get(), impl.get(), (const void *)typeid(T).name(),
      |                                                                ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:471:64: error: use of typeid requires -frtti
  471 |         CodeLoc, (void *)impl.get(), impl.get(), (const void *)typeid(T).name(),
      |                                                                ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:761:64: error: use of typeid requires -frtti
  761 |         CodeLoc, (void *)impl.get(), &MemObject, (const void *)typeid(T).name(),
      |                                                                ^
/opt/intel/oneapi/compiler/2025.0/include/sycl/buffer.hpp:781:64: error: use of typeid requires -frtti
  781 |         CodeLoc, (void *)impl.get(), Impl.get(), (const void *)typeid(T).name(),
      |                                                                ^
In file included from /home/jovyan/Kali/1119_args_new/intel-xpu-backend-for-triton/utils/SPIRVRunner/SPIRVRunner.cpp:2:
In file included from /opt/intel/oneapi/compiler/2025.0/include/sycl/sycl.hpp:27:
/opt/intel/oneapi/compiler/2025.0/include/sycl/accessor_image.hpp:980:35: error: use of typeid requires -frtti
  980 |         AccessMode, (const void *)typeid(DataT).name(), sizeof(DataT), CodeLoc);
      |                                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

</details>

2024-11-21 17:12 UTC, alexbaden commented on scripts/compile-triton.sh
> +    -DLLVM_ENABLE_RTTI=ON \
Ah, ok. I think it's worth trying an experiment to see if -fno-rtti will work here. Split the command line options parsing out to a separate file (without sycl) and see if that compiles, links, and runs with `-fno-rtti`. If it does, we might be able to build the command line parsing as a separate object file and then link that object file with our main `SPIRVRunner` object file to get around this problem.

2024-12-03 14:34 UTC, etiotto commented
@alexbaden are you ok with these changes ?

2024-12-03 14:36 UTC, alexbaden requested changes
No - see comment: https://github.com/intel/intel-xpu-backend-for-triton/pull/2759#discussion_r1852550872

2024-12-04 04:52 UTC, kballeda commented on scripts/compile-triton.sh
> +    -DLLVM_ENABLE_RTTI=ON \
I was out for some time. yes, this change was experimented, and it works. Updated the PR, please review the same. Thanks

2024-12-04 18:26 UTC, alexbaden approved these changes
Looks good, happy to see the `-fno-rtti` trick worked!

2024-12-05 04:20 UTC, kballeda commented on utils/SPIRVRunner/llvm_parser.h
> +    std::string output_tensor;
Sure, will check this!

2024-12-05 15:34 UTC, merged

2024-12-05 15:41 UTC, alexbaden commented on utils/SPIRVRunner/llvm_parser.h
> +    std::string output_tensor;
Looks good, thanks!