Initialize Docs
intel/intel-xpu-backend-for-triton pull request #36
Opened 2023-07-05 05:25 UTC by Stonepia

2023-07-19 08:13 UTC, chengjunlu commented on README.md
> +Intel® XPU Backend for Triton\* requires [PyTorch](https://pytorch.org/get-started/locally/) and [intel-extension-for-pytorch](https://github.com/intel/intel-extension-for-pytorch/) for build.
no IPEX for building.

2023-07-19 08:16 UTC, chengjunlu commented on README.md
> +Please refer to the [test guide](docs/tests.md) for more information.
The name `tests.md` is not good.  `HowToRun` better?

2023-07-19 08:59 UTC, chuanqi129 commented on docs/test_docs/E2E_tests.md
> +SHAPE=${8:-static}          # static / dynamic
For this stage, we focus on static shape, I think we can remove SHAPE param

2023-07-19 08:59 UTC, chuanqi129 commented on docs/test_docs/E2E_tests.md
> +fi
Also remove this `Shape_extra` part

2023-07-19 08:59 UTC, chuanqi129 commented on docs/test_docs/E2E_tests.md
> +```Python
Change `Python` to `Bash`

2023-07-19 08:59 UTC, chuanqi129 commented on docs/test_docs/E2E_tests.md
> +```Python
Same here

2023-07-19 08:59 UTC, chuanqi129 commented on docs/test_docs/E2E_tests.md
> +To profile the result, one should use the `performance` mode instead of `accuracy`. i.e, One should use
For this part, it will be better to add the profiling method in generally. And take Toyrchdynamo benchmark scripts as an example, how to do the profiling correspondingly . How do you think?

2023-07-20 01:16 UTC, Stonepia commented on docs/test_docs/E2E_tests.md
> +SHAPE=${8:-static}          # static / dynamic
Thanks for the comment! Fixed in https://github.com/intel/intel-xpu-backend-for-triton/pull/36/commits/52843f6d6f2cb96c84eef066d603c3a4b53fe8b3

2023-07-20 01:16 UTC, Stonepia commented on docs/test_docs/E2E_tests.md
> +fi
Thanks for the comment. Fixed.

2023-07-20 01:18 UTC, Stonepia commented on docs/test_docs/E2E_tests.md
> +To profile the result, one should use the `performance` mode instead of `accuracy`. i.e, One should use
I agree. For IPEX there is an ongoing profiling tool for the latest API. I am planning to add that guide after the PR is merged. but I will add a legacy profiling guide as well.

2023-07-20 01:19 UTC, Stonepia commented on README.md
> +Please refer to the [test guide](docs/tests.md) for more information.
Thanks for the comment. I made this change in https://github.com/intel/intel-xpu-backend-for-triton/pull/36/commits/f34331524fbf730ae6c06a9e056419910b806d75

2023-07-20 01:19 UTC, Stonepia commented on README.md
> +Intel® XPU Backend for Triton\* requires [PyTorch](https://pytorch.org/get-started/locally/) and [intel-extension-for-pytorch](https://github.com/intel/intel-extension-for-pytorch/) for build.
Thanks for the comment. Fixed in https://github.com/intel/intel-xpu-backend-for-triton/pull/36/commits/f34331524fbf730ae6c06a9e056419910b806d75

2023-07-20 02:24 UTC, chuanqi129 approved these changes

2023-07-20 02:26 UTC, EikanWang requested changes

2023-07-20 02:26 UTC, EikanWang commented on README.md
> +This is the development repository of Intel® XPU Backend for Triton\*, a new [OpenAI Triton](https://github.com/openai/triton) backend for Intel® GPUs. Triton is a language and compiler for writing h
Remove `third-party`

2023-07-20 02:26 UTC, EikanWang commented on README.md
> +Intel® XPU Backend for Triton\* serves as a third-party backend for [OpenAI Triton](https://github.com/openai/triton). One should build from the triton repo, instead of building from intel-xpu-backen
ditto

2023-07-20 02:27 UTC, chengjunlu approved these changes

2023-07-20 03:34 UTC, Stonepia commented on README.md
> +This is the development repository of Intel® XPU Backend for Triton\*, a new [OpenAI Triton](https://github.com/openai/triton) backend for Intel® GPUs. Triton is a language and compiler for writing h
Thanks! Removed in 
https://github.com/intel/intel-xpu-backend-for-triton/pull/36/commits/1441e1d973acb9a3093533848f49d8259c5ce6cf

2023-07-20 03:34 UTC, Stonepia commented on README.md
> +Intel® XPU Backend for Triton\* serves as a third-party backend for [OpenAI Triton](https://github.com/openai/triton). One should build from the triton repo, instead of building from intel-xpu-backen
Removed in https://github.com/intel/intel-xpu-backend-for-triton/pull/36/commits/1441e1d973acb9a3093533848f49d8259c5ce6cf

2023-07-25 07:41 UTC, EikanWang approved these changes

2023-07-25 07:46 UTC, merged