Add --help and clean up compile-triton.sh
intel/intel-xpu-backend-for-triton pull request #480
Opened 2024-02-12 15:17 UTC by etiotto

2024-02-12 15:21 UTC, whitneywhtsang commented on scripts/compile-triton.sh
> +      echo "Example usage: ./compile-triton.sh [--llvm | --triton | --clean| --venv]"
[nit]
```suggestion
      echo "Example usage: ./compile-triton.sh [--llvm | --triton | --clean | --venv]"
```

2024-02-12 15:37 UTC, etiotto commented on scripts/compile-triton.sh
> -    --skip-triton)
done

2024-02-12 15:37 UTC, etiotto commented on scripts/compile-triton.sh
> +      echo "Example usage: ./compile-triton.sh [--llvm | --triton | --clean| --venv]"
done

2024-02-12 15:38 UTC, whitneywhtsang approved these changes

2024-02-12 15:44 UTC, pbchekin commented on scripts/compile-triton.sh
> +fi
I know it was in the previous version, but `deactivate` generates an error if we are not in venv. The error is ignored, because the script does not have `set -e` but anyways it is an error.
```suggestion
elif [ -n "$VIRTUAL_ENV" ]; then
  echo "**** Cleaning up Python virtualenv ****"
  deactivate
fi
```

2024-02-13 03:06 UTC, whitneywhtsang requested changes

2024-02-13 03:06 UTC, whitneywhtsang commented on scripts/compile-triton.sh
>  # Install libGenISAIntrinsics.a
`Install libGenISAIntrinsics.a` needs to happen after `build_llvm`, or else `$PACKAGES_DIR/llvm/lib` is overwritten. 
Suggest to move the `Install libGenISAIntrinsics.a` step to the end of `build_llvm`.

2024-02-13 14:32 UTC, etiotto commented on scripts/compile-triton.sh
>  # Install libGenISAIntrinsics.a
done

2024-02-13 18:54 UTC, whitneywhtsang approved these changes

2024-02-13 20:30 UTC, merged