Avoid overriding user's existing PyTorch and IPEX by default
intel/intel-xpu-backend-for-triton pull request #616
Opened 2024-03-04 17:44 UTC by whitneywhtsang

2024-03-04 17:56 UTC, pbchekin approved these changes
Looks good, a couple of suggestions

2024-03-04 17:56 UTC, pbchekin commented on scripts/compile-triton.sh
> +  if [ $? != 0 ]; then
```suggestion
  if ! pip show torch &>/dev/null; then
```

2024-03-04 17:56 UTC, pbchekin commented on scripts/compile-triton.sh
> +  if [ $? != 0 ]; then
```suggestion
  if ! pip show intel_extension_for_pytorch &>/dev/null; then
```

2024-03-04 18:15 UTC, etiotto commented
The `compile_triton.sh` script should *not* build either IPES or PyTorch because those 2 component aren't needed to build the compiler. Please remove the code that was added to this script to build those components.  If you want to build IPEX/PyTorch please do it in another script.

2024-03-04 18:20 UTC, whitneywhtsang commented
The change is to make our local testing be similar to our CI testing: https://github.com/intel/intel-xpu-backend-for-triton/issues/560.

2024-03-04 18:25 UTC, etiotto commented
Please revert https://github.com/intel/intel-xpu-backend-for-triton/pull/608.

2024-03-04 18:26 UTC, etiotto requested changes
Please revert https://github.com/intel/intel-xpu-backend-for-triton/pull/608 and build IPEX/PyTorch in a separate script.

2024-03-04 19:20 UTC, pbchekin commented on scripts/compile-pytorch-ipex.sh
> +      echo "Example usage: ./compile-triton.sh [--pytorch | --ipex | --clean | --venv]"
```suggestion
      echo "Example usage: ./compile-pytorch-ipex.sh [--pytorch | --ipex | --clean | --venv]"
```

2024-03-04 19:20 UTC, pbchekin commented on scripts/compile-pytorch-ipex.sh
> +  python3 -m venv .venv --prompt triton
Not sure if this script should needs to handle venv. If a normal use case is calling from `compile-triton.sh`, then venv is already created and activated.

2024-03-04 19:32 UTC, pbchekin approved these changes

2024-03-04 19:32 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +  python3 -m venv .venv --prompt triton
Modified, it activates venv if `--venv` is given, and `test-triton.sh` doesn't call it with `--venv`.

2024-03-04 19:32 UTC, etiotto commented on scripts/compile-pytorch-ipex.sh
> +      echo "Example usage: ./compile-triton.sh [--pytorch | --ipex | --clean | --venv]"
`/compile-triton.sh` -> `/compile-pytorch-ipex.sh`

2024-03-04 19:32 UTC, etiotto commented on scripts/compile-pytorch-ipex.sh
> +  pip uninstall -y torch intel_extension_for_pytorch
Wait. If the user had a version of IPEX/pytorch installed already this would cause it to be removed. I suggest removing the --clean option.

2024-03-04 19:32 UTC, etiotto commented on scripts/compile-pytorch-ipex.sh
> +  python3 -m venv .venv --prompt triton
Let's remove venv for now.

2024-03-04 19:33 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +  pip uninstall -y torch intel_extension_for_pytorch
Yes, this is intentional, as `--clean` is to create a clean environment, it is not enabled by default.

2024-03-04 19:34 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +  python3 -m venv .venv --prompt triton
Why?

2024-03-04 19:37 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +  pip uninstall -y torch intel_extension_for_pytorch
A common use case is when a user cannot create a working environment from using the suggested scripts, so would like to create an new environment from scratch.

2024-03-04 19:41 UTC, etiotto commented on scripts/test-triton.sh
> +$SCRIPTS_DIR/compile-pytorch-ipex.sh
I have a bit of a concern. We used to know exactly what wheel (source level) we used for pytorch and IPEX. Now that those components are built from source we no longer know the commit levels used by a test run. 

What happens if we build those components and test start failing ? How do we easily know that the regression is caused by a new version of IPEX and/or pytorch  and not by the Triton compiler ?  How do we know the last "good" level of those 2 components ?

2024-03-04 20:02 UTC, whitneywhtsang commented on scripts/test-triton.sh
> +$SCRIPTS_DIR/compile-pytorch-ipex.sh
@pbchekin Can we do something like that?

2024-03-04 20:19 UTC, pbchekin commented on scripts/test-triton.sh
> +$SCRIPTS_DIR/compile-pytorch-ipex.sh
Yes, I am always for strict pinning of dependencies by commit id, including LLVM (we currently are not pinning LLVM by commit id, by the way, we use the latest commit from genx branch).

2024-03-04 20:36 UTC, pbchekin commented on scripts/test-triton.sh
> +$SCRIPTS_DIR/compile-pytorch-ipex.sh
@whitneywhtsang I'll add pins for PyTorch and IPEX for CI in a separate PR, we'll revisit this PR after that.

2024-03-04 21:02 UTC, etiotto commented on scripts/compile-pytorch-ipex.sh
> +  python3 -m venv .venv --prompt triton
Because I saw this comment https://github.com/intel/intel-xpu-backend-for-triton/pull/616#discussion_r1511681511 before you changed the script.

2024-03-04 21:06 UTC, etiotto commented on scripts/compile-pytorch-ipex.sh
> +  pip uninstall -y torch intel_extension_for_pytorch
I am concerned that --clean will uninstall IPEX/PyTorch from the user environment even when the script did not build IPEX and/or Triton from source.  The --clean flag IMO should only clean the build directory of IPEX/PyTorch and should not remove anything from the environment.  The user can manage that outside of the script if he/she desires.

2024-03-04 21:10 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +  python3 -m venv .venv --prompt triton
OK, resolving this conversation.

2024-03-04 21:28 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +  pip uninstall -y torch intel_extension_for_pytorch
It is only triggered when user do `compile-pytorch-ipex.sh --clean`. Given that they use `compile-pytorch-ipex.sh`,  it makes sense to believe they want to build IPEX and/or Torch from source. 

Changed the script to only clone the repos if they are build from source. Does that address your concern?

2024-03-04 22:41 UTC, etiotto commented on scripts/compile-pytorch-ipex.sh
> +  pip uninstall -y torch intel_extension_for_pytorch
ok I am fine with this now.

2024-03-04 23:57 UTC, pbchekin commented on scripts/test-triton.sh
> +$SCRIPTS_DIR/compile-pytorch-ipex.sh
Added pins for CI in #620.

2024-03-05 01:21 UTC, Stonepia requested changes
Thanks for the build scripts! Overall LGTM. I added some comments to avoid building failures.

2024-03-05 01:21 UTC, Stonepia commented on scripts/compile-pytorch-ipex.sh
> +    pip install -r requirements.txt
There are several dependencies need to be installed individually, you could refer to https://github.com/pytorch/pytorch?tab=readme-ov-file#install-dependencies for detail.

```Bash
conda install cmake ninja
pip install -r requirements.txt
conda install intel::mkl-static intel::mkl-include
```

2024-03-05 01:21 UTC, Stonepia commented on scripts/compile-pytorch-ipex.sh
> +build_ipex() {
One additional thought is that, I didn't find the place you source the oneAPI toolkit, so I assume you will source it globally. However, It is recommended to ONLY source oneAPI during the build IPEX (DO NOT source it when building pytorch / triton). 

You could find a reference at https://github.com/Stonepia/Tools/blob/main/build_env.sh#L58

2024-03-05 01:27 UTC, Stonepia commented
Another thought is, could you also pin the commit for PyTorch / IPEX? Because there are cases when the newest PyTorch/IPEX commits may cause problems. Pin on a fully tested commit would be better.

2024-03-05 01:29 UTC, whitneywhtsang commented
> Another thought is, could you also pin the commit for PyTorch / IPEX? Because there are cases when the newest PyTorch/IPEX commits may cause problems. Pin on a fully tested commit would be better.

Yes, will work on that.

2024-03-05 05:30 UTC, whitneywhtsang commented on scripts/test-triton.sh
> +$SCRIPTS_DIR/compile-pytorch-ipex.sh
Changed to use pinned commit.

2024-03-05 05:46 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +    pip install -r requirements.txt
The script may not be invoked in a conda environment, is there equivalent instructions without using `conda`? 
btw, pytorch can be built successfully currently.

2024-03-05 05:46 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +build_ipex() {
Users of the script may have sourced the oneAPI toolkit in their environment, what's the concern of sourcing when builting pytorch / triton?

2024-03-05 05:46 UTC, whitneywhtsang commented
> > Another thought is, could you also pin the commit for PyTorch / IPEX? Because there are cases when the newest PyTorch/IPEX commits may cause problems. Pin on a fully tested commit would be better.
> 
> Yes, will work on that.

Done, it is now using pinned commits.

2024-03-05 06:11 UTC, Stonepia commented on scripts/compile-pytorch-ipex.sh
> +build_ipex() {
In the former PyTorch building process, if you source the oneAPI, the LD_LIBRARY_PATH will be polluted,  so that you might experience some strange errors. In view of that, only source oneAPI at the IPEX building is recommended.

2024-03-05 06:24 UTC, Stonepia commented on scripts/compile-pytorch-ipex.sh
> +    pip install -r requirements.txt
Without mkl/mkl-include build could pass, but I didn't know if that would have side effect for performance.

I didn't try using pip, but you could have a try. I also found that there are `mkl-static` and `mkl-include` in pypi, maybe you could have a try, but stock PyTorch recommends using conda BTW.

2024-03-05 06:25 UTC, Stonepia approved these changes

2024-03-05 06:26 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +    pip install -r requirements.txt
FYI @pbchekin we probably want to do the same for CI.

2024-03-05 14:45 UTC, etiotto commented on scripts/compile-pytorch-ipex.sh
> +    pip install -r requirements.txt
I think the script should be used by the entire team to build pytorch so, if @Stonepia routinely installs the intel mkl libraries we should do the same here.  @Stonepia can you please advice?

2024-03-05 14:45 UTC, etiotto commented on scripts/compile-pytorch-ipex.sh
> +build_ipex() {
I don't think sourcing the oneAPI should be done in the script because one may want to run end-to-end (e.g. core) tests outside of scripts (e.g. on the command line) and to do that we need to have sourced the oneAPI in the user environment.

2024-03-05 14:46 UTC, etiotto commented
There are unresolved comments @Stonepia. Can you take a look at those comments.

2024-03-05 15:57 UTC, pbchekin commented on scripts/compile-pytorch-ipex.sh
> +    pip install -r requirements.txt
MKL is the part of oneAPI BaseKit which we already have.

2024-03-06 01:09 UTC, Stonepia commented on scripts/compile-pytorch-ipex.sh
> +build_ipex() {
I agree, just a reminder here. We don't need to put that sourcing into this script.

Add a debug detail here also: 
If you ever encountered the issue like something below,  you could `ldd` that `.so`. If you find that it is linked against the oneAPI things, then you may consider it is the problem of oneAPI environment.

```Bash
$python -c "import torch"
Import Error:  ../pytorch/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

$ldd libtorch_cpu.so
...
libmkl_intel_lp64.so => /home/.../intel/oneapi/.....
```

2024-03-06 01:14 UTC, Stonepia commented on scripts/compile-pytorch-ipex.sh
> +    pip install -r requirements.txt
Hello @pbchekin, well, PyTorch uses that static MKL installed in conda env, not the mkl provided in the oneAPI basekit. 

That's the reason why we always recommend not source oneAPI during the pytorch build process. In addition, that's why we install the static linked version of mkl/mkl-include, otherwise, the torch will get some error after sourcing the oneAPI.

Thus, to follow the stock PyTorch's behavior,  using methods listed in https://github.com/pytorch/pytorch?tab=readme-ov-file#install-dependencies  is more preferable to me.

2024-03-06 01:14 UTC, Stonepia commented
> There are unresolved comments @Stonepia. Can you take a look at those comments.

Thanks for the reminder, I added the comments, please take a look.

2024-03-06 03:32 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +build_ipex() {
Added the import checks in the script.

2024-03-06 04:15 UTC, whitneywhtsang commented on scripts/compile-pytorch-ipex.sh
> +    pip install -r requirements.txt
added `pip install mkl-static mkl-include`

2024-03-06 14:26 UTC, etiotto approved these changes

2024-03-06 15:16 UTC, merged