Fixed few of attention test failure
intel/intel-xpu-backend-for-triton pull request #634
Opened 2024-03-07 08:35 UTC by Sarbojit2019

PR fixes #598

2024-03-07 18:27 UTC, whitneywhtsang approved these changes

2024-03-08 06:37 UTC, whitneywhtsang approved these changes

2024-03-08 07:07 UTC, whitneywhtsang commented on .github/workflows/build_and_test.yml
> +          python3 -m pytest --junitxml=~/reports/flash_attention.xml -n 8 -m interpreter -vvv -s operators/test_flash_attention.py::test_op --device cpu
```suggestion
          python3 -m pytest --junitxml=~/reports/interpreter_flash_attention.xml -n 8 -m interpreter -vvv -s operators/test_flash_attention.py::test_op --device cpu
```

2024-03-08 16:08 UTC, pbchekin requested changes

2024-03-08 16:08 UTC, pbchekin commented on .github/workflows/build_and_test.yml
> +          python3 -m pytest --junitxml=~/reports/flash_attention.xml -n 8 -m interpreter -vvv -s operators/test_flash_attention.py::test_op --device cpu
Please also update scripts/test-triton.sh

2024-03-11 18:05 UTC, whitneywhtsang commented on .github/workflows/build_and_test.yml
> +          python3 -m pytest --junitxml=~/reports/flash_attention.xml -n 8 -m interpreter -vvv -s operators/test_flash_attention.py::test_op --device cpu
done.

2024-03-11 18:07 UTC, pbchekin approved these changes

2024-03-11 19:14 UTC, merged