Formalize Docs
intel/intel-xpu-backend-for-triton pull request #71
Opened 2023-08-07 08:27 UTC by Stonepia

2023-08-07 09:45 UTC, riverliuintel requested changes

2023-08-07 09:45 UTC, riverliuintel commented on README.md
> +This is the development repository of XPU Backend for Triton\*, a new [OpenAI Triton](https://github.com/openai/triton) backend for Intel GPUs. Triton is a language and compiler for writing highly ef
Intel® XPU to Intel XPU

2023-08-07 09:45 UTC, riverliuintel commented on README.md
> -# Intel® XPU Backend for Triton\*
Just keep Intel® XPU Backend for Triton\*, until got further clarification.

2023-08-07 09:45 UTC, riverliuintel commented on docs/test_docs/end_to_end_tests.md
> -This doc contains [Torchdynamo Benchmarks](https://github.com/pytorch/pytorch/tree/main/benchmarks/dynamo) setup for Intel® XPU Backend for Triton\*.
Intel® XPU -> Intel XPU

2023-08-08 01:26 UTC, Stonepia commented on README.md
> -# Intel® XPU Backend for Triton\*
Thanks for the comment, this is done by https://github.com/intel/intel-xpu-backend-for-triton/pull/71/commits/039f935289dd5af26adaf1e7b4b5393ceb9c696f

2023-08-08 01:32 UTC, Stonepia commented on README.md
> +This is the development repository of XPU Backend for Triton\*, a new [OpenAI Triton](https://github.com/openai/triton) backend for Intel GPUs. Triton is a language and compiler for writing highly ef
Thanks for the comment! This `Intel®` is for `Intel® XPU Backend for Triton*`. Thus I keep the `®` here.

2023-08-08 01:33 UTC, Stonepia commented on docs/test_docs/end_to_end_tests.md
> -This doc contains [Torchdynamo Benchmarks](https://github.com/pytorch/pytorch/tree/main/benchmarks/dynamo) setup for Intel® XPU Backend for Triton\*.
This `®` is also for `Intel® XPU Backend for Triton*`

2023-08-08 01:39 UTC, riverliuintel approved these changes
Looks good.

2023-08-08 01:40 UTC, merged