[TritonGEN]: Add 2d block prefetch operator
intel/intel-xpu-backend-for-triton pull request #751
Opened 2024-03-26 14:49 UTC by etiotto

2024-03-26 17:47 UTC, whitneywhtsang requested changes

2024-03-26 17:47 UTC, whitneywhtsang commented on test/TritonGEN/tritongen-to-llvm.mlir
> +  // CHECK-NEXT:  triton_gen.2Dblockprefetch %arg0, %arg1, %arg2, %arg3, %arg4, %arg5 {cache_control = L1UC_L3UC} : (!llvm.ptr, i32, i32, i32, i32, i32)
It is not lowered.

2024-03-26 23:11 UTC, etiotto commented on test/TritonGEN/tritongen-to-llvm.mlir
> +  // CHECK-NEXT:  triton_gen.2Dblockprefetch %arg0, %arg1, %arg2, %arg3, %arg4, %arg5 {cache_control = L1UC_L3UC} : (!llvm.ptr, i32, i32, i32, i32, i32)
done

2024-03-26 23:26 UTC, etiotto commented on lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
> -static std::optional<int> getConstantInt(Value v) {
Just moved these utility functions at the start of the file

2024-03-26 23:26 UTC, etiotto commented on lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
> +LogicalResult TritonGEN::Matrix2DBlockPrefetchOp::verify() {
Need to add more verification checks here (and expand the lit tests).

2024-03-26 23:26 UTC, etiotto commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> +createGenISA2DBlockPrefetch(TritonGEN::Matrix2DBlockPrefetchOp op,
Note that currently I have lowered the operator to a GenISA call. We will need to update the codegen to use OpenCL functions once they are available...

2024-03-27 00:16 UTC, chengjunlu commented on lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
> +      return op->emitOpError("tile_width for 32 bit elements should be equal "
Can we use a more flexible checking? The 2D block load/store is for general purpose. Just protect the user input fits the HW's limitation is simple.

2024-03-27 00:41 UTC, Dewei-Wang-sh commented on lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
> +static std::optional<int> getConstantInt(Value v) {
mlir has "std::optional<int64_t> getConstantIntValue", we can use that alternatively.

2024-03-27 00:41 UTC, Dewei-Wang-sh approved these changes
lgtm

2024-03-27 06:50 UTC, victor-eds commented on include/triton/Dialect/TritonGEN/IR/TritonGENOps.td
> +    $elem_size_in_bits - 32 for f32, bf32; 16 for f16, int16, bf16; 8 for int8 etc...
```suggestion
    $elem_size_in_bits - 32 for f32, bf32; 16 for f16, int16, bf16; 8 for int8, etc...
```

2024-03-27 06:50 UTC, victor-eds commented on lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
> +static std::optional<int> getConstantInt(Value v) {
[`constant_int_value_binder`](https://github.com/llvm/llvm-project/blob/577e0ef94fb0b4ba9f97a6f58a1961f7ba247d21/mlir/include/mlir/IR/Matchers.h#L176) and [`constant_int_predicate_matcher`](https://github.com/llvm/llvm-project/blob/577e0ef94fb0b4ba9f97a6f58a1961f7ba247d21/mlir/include/mlir/IR/Matchers.h#L208) might also be a good fit for this particular use case, but we can use what @Dewei-Wang-sh mentions.

2024-03-27 06:50 UTC, victor-eds commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> +  std::string funcName = "llvm.genx.GenISA.LSC2DBlockPrefetch.isVoid";
```suggestion
  constexpr StringLiteral funcName = "llvm.genx.GenISA.LSC2DBlockPrefetch.isVoid";
```

2024-03-27 14:20 UTC, etiotto commented on lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
> +static std::optional<int> getConstantInt(Value v) {
Changed to use `getConstantIntValue`

2024-03-27 14:23 UTC, etiotto commented on include/triton/Dialect/TritonGEN/IR/TritonGENOps.td
> +    $elem_size_in_bits - 32 for f32, bf32; 16 for f16, int16, bf16; 8 for int8 etc...
done

2024-03-27 14:23 UTC, etiotto commented on third_party/intel/lib/TritonGENToLLVM/TritonGENToLLVMPass.cpp
> +  std::string funcName = "llvm.genx.GenISA.LSC2DBlockPrefetch.isVoid";
done

2024-03-27 14:26 UTC, etiotto commented on lib/Dialect/TritonGEN/IR/TritonGENOps.cpp
> +      return op->emitOpError("tile_width for 32 bit elements should be equal "
Sure, this PR is for adding the prefetch operation. Added an issue to track this request.

2024-03-27 14:54 UTC, whitneywhtsang approved these changes

2024-03-27 15:36 UTC, merged