add e2e perf test to nightly
intel/intel-xpu-backend-for-triton pull request #81
Opened 2023-08-30 06:19 UTC by ESI-SYD

2023-08-30 07:12 UTC, chuanqi129 commented on .github/workflows/triton_xpu_backend_e2e_ci.yml
> +
Why we need this change? if the test failed to the check, then the test results can't be upload. Suggest to upload the test results before than the exit.

2023-08-30 07:12 UTC, chuanqi129 commented on .github/workflows/triton_xpu_backend_e2e_nightly.yml
> +          path: /home/gta/triton-nightly/frameworks.ai.pytorch.private-gpu/inductor_log/
TODO: add latency and compilation time regression check in the future

2023-08-30 07:13 UTC, chuanqi129 commented
Please check the pre-commit format failure with @Stonepia

2023-08-30 07:50 UTC, ESI-SYD commented on .github/workflows/triton_xpu_backend_e2e_ci.yml
> +
`upload` before step `check` will miss `e2e_summary.log` file

2023-08-30 08:14 UTC, chuanqi129 commented on .github/workflows/triton_xpu_backend_e2e_ci.yml
> +
Yes, I know. Compared with test results, the `e2e_summary.log` is not important, because it can be print in action log. But we need raw test result to check which model has issue. And we also can optimize the logic of the result check, summary - > upload -> set status (success or failed) according to the summary results

2023-08-31 02:14 UTC, Stonepia commented
There is build error because the libinfo is not correctly found.

Please add the following line when the triton is build. Note that for CI, this env name should be changed accordingly.

```
export LD_PRELOAD=$LD_PRELOAD:/home/gta/miniconda3/envs/triton-release/lib/libtinfow.so.6
```

2023-08-31 05:44 UTC, ESI-SYD commented
Addressed

2023-09-01 01:54 UTC, Stonepia requested changes

2023-09-01 01:54 UTC, Stonepia commented on .github/workflows/triton_xpu_backend_e2e_ci.yml
> +          export LD_PRELOAD=$LD_PRELOAD:/home/gta/miniconda3/envs/triton-preci/lib/libtinfow.so.6
Could you change the `/home/gta/miniconda3` to `${CONDA_PREFIX}` for more general user cases?

2023-09-01 01:54 UTC, Stonepia commented on .github/workflows/triton_xpu_backend_e2e_nightly.yml
> +          export LD_PRELOAD=$LD_PRELOAD:/home/gta/miniconda3/envs/triton-nightly-test/lib/libtinfow.so.6
same as before

2023-09-05 03:04 UTC, Stonepia approved these changes

2023-09-05 03:40 UTC, merged