add a script to automate compilation
intel/intel-xpu-backend-for-triton pull request #83
Opened 2023-08-31 06:55 UTC by jingxu10

as title

2023-09-06 05:58 UTC, EikanWang approved these changes

2023-09-08 12:20 UTC, fcharras commented
Is the script working at the moment ? the very last step (triton build) errors out with `/usr/bin/ld: cannot find -lz: No such file or directory`, but zlib is installed in my environment.

2023-10-06 09:04 UTC, fcharras commented
Hi, tried it again today but compilation of ipex failed with:

> no member named 'QXPU' in 'c10::QEngine'

```
[ 97%] Building CXX object csrc/gpu/CMakeFiles/intel-ext-pt-gpu.dir/aten/operators/SoftPlus.cpp.o
[ 97%] Building CXX object csrc/gpu/CMakeFiles/intel-ext-pt-gpu.dir/aten/operators/SoftShrink.cpp.o
[ 97%] Building CXX object csrc/gpu/CMakeFiles/intel-ext-pt-gpu.dir/aten/operators/SparseCsrTensorMath.cpp.o
/home/u103857/triton_compiler_2/intel-extension-for-pytorch/csrc/gpu/aten/operators/QConv_prepack.cpp:129:3: warning: use of function template name with no prior declaration in function call with explicit template arguments is a C++20 e
xtension [-Wc++20-extensions]
  register_prepack<2>(
  ^
/home/u103857/triton_compiler_2/intel-extension-for-pytorch/csrc/gpu/aten/operators/QConv_prepack.cpp:130:20: error: no member named 'QXPU' in 'c10::QEngine'
      at::QEngine::QXPU,
      ~~~~~~~~~~~~~^
/home/u103857/triton_compiler_2/intel-extension-for-pytorch/csrc/gpu/aten/operators/QConv_prepack.cpp:129:3: warning: use of function template name with no prior declaration in function call with explicit template arguments is a C++20 e
xtension [-Wc++20-extensions]
  register_prepack<2>(
  ^
/home/u103857/triton_compiler_2/intel-extension-for-pytorch/csrc/gpu/aten/operators/QConv_prepack.cpp:132:3: warning: use of function template name with no prior declaration in function call with explicit template arguments is a C++20 e
xtension [-Wc++20-extensions]
  register_prepack<3>(
  ^
/home/u103857/triton_compiler_2/intel-extension-for-pytorch/csrc/gpu/aten/operators/QConv_prepack.cpp:133:20: error: no member named 'QXPU' in 'c10::QEngine'
      at::QEngine::QXPU,
      ~~~~~~~~~~~~~^
/home/u103857/triton_compiler_2/intel-extension-for-pytorch/csrc/gpu/aten/operators/QConv_prepack.cpp:132:3: warning: use of function template name with no prior declaration in function call with explicit template arguments is a C++20 e
xtension [-Wc++20-extensions]
  register_prepack<3>(
  ^
/home/u103857/triton_compiler_2/intel-extension-for-pytorch/csrc/gpu/aten/operators/QConv_prepack.cpp:136:20: error: no member named 'QXPU' in 'c10::QEngine'
      at::QEngine::QXPU,
      ~~~~~~~~~~~~~^
4 warnings and 3 errors generated.
make[2]: *** [csrc/gpu/CMakeFiles/intel-ext-pt-gpu.dir/build.make:2721: csrc/gpu/CMakeFiles/intel-ext-pt-gpu.dir/aten/operators/QConv_prepack.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:594: csrc/gpu/CMakeFiles/intel-ext-pt-gpu.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

2023-10-09 09:00 UTC, Stonepia requested changes
Hello, this script is a little outdated and based on the previous BKC.

2023-10-09 09:00 UTC, Stonepia commented on tools/compile_bundle.sh
> +source ${ONEMKL_ENV}
The source of `DPCPP_ENV` and `ONEMKL_ENV` should be only during building the Intel® Extension for PyTorch, other components may link to the wrong mkl path if these two are sourced.
However, this error was only discovered when building PyTorch, so I think sourcing them here is acceptable. Just a note here.

2023-10-18 10:22 UTC, jingxu10 commented on tools/compile_bundle.sh
> +#  TorchVision
Since the PyTorch is a self compiled one. Torchvision and torchaudio have to be compiled against this pytorch binary, thus, include them both in this script.

2023-10-18 10:24 UTC, jingxu10 commented on tools/compile_bundle.sh
> +source ${ONEMKL_ENV}
It was because of https://github.com/intel/intel-extension-for-pytorch/pull/334/files#r1184418847.

2024-01-16 16:28 UTC, etiotto commented
Can we close this PR? Is old and there is no recent activity.

2024-01-22 17:53 UTC, etiotto commented
Closing (see https://github.com/intel/intel-xpu-backend-for-triton/pull/83#issuecomment-1894090738).

2024-01-22 17:53 UTC, closed without merging