[Performance] xetla kernels benchmark integration
intel/intel-xpu-backend-for-triton pull request #877
Opened 2024-04-16 03:19 UTC by ESI-SYD

2024-04-16 17:54 UTC, pbchekin commented on python/tutorials/install_xetla_kernels.sh
> +git submodule update --init --recursive
This repository has a submodule in intel-innersource, this will not work without proper credentials.

2024-04-17 04:51 UTC, chengjunlu commented on python/tutorials/install_xetla_kernels.sh
> +git submodule update --init --recursive
I removed the changes in the scripts to integrate the benchmark running in this PR. We need further discussion about how to add a new job in the CI for benchmark.

2024-04-18 17:31 UTC, pbchekin requested changes

2024-04-18 17:31 UTC, pbchekin commented on .gitmodules
> +[submodule "benchmark/third_party/xetla"]
Please don't use submodules. Instead consider using an external repository in the same way as we currently use llvm, e2e benchmarks, and so on.

2024-04-19 04:07 UTC, chengjunlu commented on .gitmodules
> +[submodule "benchmark/third_party/xetla"]
I remove the git submodule. Download the XeTLA library when building.

2024-05-06 09:41 UTC, ESI-SYD commented
Is there a runner that includes available oneapi `dnnl` which is a dependency of this benchmark?

```
/home/runner/intel/oneapi/dnnl/latest/env/vars.sh: No such file or directory
```

2024-05-06 14:06 UTC, chengjunlu commented
Hi @pbchekin,
Could you please help to review the work flow yaml?

2024-05-06 18:20 UTC, pbchekin commented
> Is there a runner that includes available oneapi `dnnl` which is a dependency of this benchmark?
> 
> ```
> /home/runner/intel/oneapi/dnnl/latest/env/vars.sh: No such file or directory
> ```

[PyTorch Prerequisites for Intel GPUs](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpus.html) does not have dnnl, I think, but you can install one in the runner in runtime (with sudo apt update; sudo apt install ...), or we can have a custom runner image with pre-installed dnnl, see https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/.github/dockerfiles/runner-base/Dockerfile.

2024-05-08 01:32 UTC, ESI-SYD commented
> > Is there a runner that includes available oneapi `dnnl` which is a dependency of this benchmark?
> > ```
> > /home/runner/intel/oneapi/dnnl/latest/env/vars.sh: No such file or directory
> > ```
> 
> [PyTorch Prerequisites for Intel GPUs](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpus.html) does not have dnnl, I think, but you can install one in the runner in runtime (with sudo apt update; sudo apt install ...), or we can have a custom runner image with pre-installed dnnl, see https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/.github/dockerfiles/runner-base/Dockerfile.

Thanks, workaround to use actually compatible 2024.1 oneapi basekit in runtime

2024-05-08 06:14 UTC, chengjunlu commented on python/tutorials/install_xetla_kernels.sh
> +git submodule update --init --recursive
The `triton-benchmark.yaml` has been added.

2024-05-08 14:33 UTC, pbchekin commented on .github/workflows/triton-benchmarks.yml
> +      - llvm-target
Do you want to remove this before merging? Running manually is fine, you can also run it daily/nightly if you want but running for each commit is too much IMHO.

2024-05-08 14:34 UTC, pbchekin approved these changes
Looks good! You will probably need to disable running the workflow on each commit and add a cron similar to https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/.github/workflows/nightly-wheels.yml#L5-L6.

2024-05-09 01:20 UTC, ESI-SYD commented on .github/workflows/triton-benchmarks.yml
> +      - llvm-target
Done

2024-05-09 01:57 UTC, merged