load / store with alignment
intel/intel-xpu-backend-for-triton pull request #91
Opened 2023-09-11 08:17 UTC by retonym

Explicitly set alignment attribute for load / store op.
Improve DistilBert BF16 Training with 8%, and single Gelu op with 100%.

2023-09-12 03:07 UTC, EikanWang commented on lib/Conversion/TritonGPUToSPIRV/LoadStoreOpToSPIRV.cpp
> +      uint32_t alignment = 4 * nWords;
What's the exact mean of `4`? Does it mean 4 bytes? Could you please add some comments here to explain why we need this alignment.

2023-09-12 06:41 UTC, EikanWang requested changes

2023-09-12 06:41 UTC, EikanWang commented on lib/Conversion/TritonGPUToSPIRV/LoadStoreOpToSPIRV.cpp
> +      uint32_t alignment = 4 * nWords;
4 bytes alignment might not be valid for other data types like fp16, bf16, int8, etc. So we need to add an optimization pass to decide the load/load alignment.

2023-09-12 06:41 UTC, EikanWang commented
https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpLoad

2023-09-13 05:07 UTC, retonym commented on lib/Conversion/TritonGPUToSPIRV/LoadStoreOpToSPIRV.cpp
> +      uint32_t alignment = 4 * nWords;
Modified to `alignment = nWords * width / 8` for better code readability.

Triton will use "alignment/divisibility" as condition to calculate the length of vectorization in load / store. 
It can be safe to directly use the vector length as alignment attr in lowering to spirv dialect.

`getVectorSize` -> ... -> `getPtrAlignment` -> `getDivisibility`
https://github.com/openai/triton/blob/1465b573e8d8e4c707d579092001bcff0f1523ed/lib/Analysis/AxisInfo.cpp#L967

2023-09-20 04:37 UTC, chengjunlu approved these changes

2023-09-21 04:50 UTC, EikanWang approved these changes

2023-09-21 17:49 UTC, merged